import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { PromptAsset } from "../../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../../core/renderContextBlocks";
import { createVolumeBeatSheetSchema } from "../../../../services/novel/volume/volumeGenerationSchemas";
import { validateBeatSheetChapterCoverage } from "../../../../services/novel/volume/volumeBeatSheetChapterBudget";
import {
  VOLUME_BEAT_OPTIONAL_SLOT_KEYS,
  VOLUME_BEAT_REQUIRED_SLOT_KEYS,
  VOLUME_BEAT_SLOT_DEFINITIONS,
  getVolumeBeatRoleLabel,
} from "@ai-novel/shared/types/volumeBeatSlots";
import { type VolumeBeatSheetPromptInput } from "./shared";
import { buildVolumeBeatSheetContextBlocks } from "./contextBlocks";
import { NOVEL_PROMPT_BUDGETS } from "../promptBudgetProfiles";
import { pick } from "./localize";

const REQUIRED_SLOT_LINES = VOLUME_BEAT_REQUIRED_SLOT_KEYS
  .map((key) => `- ${key}（${getVolumeBeatRoleLabel(key)}）`)
  .join("\n");

const OPTIONAL_SLOT_LINES = VOLUME_BEAT_OPTIONAL_SLOT_KEYS
  .map((key) => `- ${key}（${getVolumeBeatRoleLabel(key)}）`)
  .join("\n");

const SLOT_ORDER_LINE = VOLUME_BEAT_SLOT_DEFINITIONS
  .map((slot) => slot.key)
  .join(" -> ");

export const volumeBeatSheetPrompt: PromptAsset<
  VolumeBeatSheetPromptInput,
  ReturnType<typeof createVolumeBeatSheetSchema>["_output"]
> = {
  id: "novel.volume.beat_sheet",
  version: "v3",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.volumeBeatSheet,
    requiredGroups: ["book_contract", "target_volume", "target_chapter_count"],
    preferredGroups: ["macro_constraints", "strategy_context", "volume_window"],
    dropOrder: ["soft_future_summary"],
  },
  repairPolicy: {
    maxAttempts: 2,
  },
  semanticRetryPolicy: {
    maxAttempts: 1,
  },
  outputSchema: createVolumeBeatSheetSchema(),
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是连载小说单卷节奏规划助手。",
        "Bạn là trợ lý hoạch định nhịp cho một tập của tiểu thuyết dài kỳ.",
        "You are a single-volume beat-planning assistant for serialized fiction."),
      pick(lang,
        "你的任务不是写章节目录，也不是扩写剧情梗概，而是把“卷骨架”转成可供后续拆章使用的 beat sheet。",
        "Nhiệm vụ của bạn không phải viết mục lục chương hay mở rộng tóm tắt cốt truyện, mà là chuyển \"khung tập\" thành beat sheet để bước tách chương sau dùng.",
        "Your task is not to write a chapter list or expand a plot summary, but to turn the \"volume skeleton\" into a beat sheet the later chapter-splitting step can use."),
      pick(lang,
        "beat 是卷内一个阶段性的节奏任务单元，代表一段章节范围内最主要的推进职责、阅读功能与必须兑现的内容。",
        "beat là một đơn vị nhiệm vụ nhịp theo giai đoạn trong tập, đại diện cho trách nhiệm đẩy truyện chính, chức năng đọc và nội dung bắt buộc phải trả trong một khoảng chương.",
        "A beat is a phased pacing-task unit within the volume — the primary progression responsibility, reading function, and must-deliver content over a span of chapters."),
      "",
      pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
      pick(lang,
        "当前阶段只生成单卷 beat sheet，不展开具体章节，不写场景细纲，不补人物小传，不写对白。",
        "Giai đoạn này chỉ tạo beat sheet cho một tập; không triển khai chương cụ thể, không viết cốt cảnh, không thêm tiểu sử nhân vật, không viết đối thoại.",
        "At this stage only produce the single-volume beat sheet — no specific chapters, no scene breakdown, no character bios, no dialogue."),
      pick(lang,
        "每个 beat 必须服务于后续拆章，强调‘这段章节要完成什么节奏任务’，而不是罗列细碎事件。",
        "Mỗi beat phải phục vụ bước tách chương, nhấn mạnh \"khoảng chương này phải hoàn thành nhiệm vụ nhịp gì\", không liệt kê sự kiện vụn vặt.",
        "Each beat must serve the later chapter split — emphasize \"what pacing task this chapter span must accomplish\", not a list of small events."),
      pick(lang,
        "只输出严格 JSON，不要输出 Markdown、解释、注释或额外字段。",
        "Chỉ xuất JSON nghiêm ngặt; không xuất Markdown, lời giải thích, chú thích hay field thừa.",
        "Output strict JSON only — no Markdown, explanations, comments, or extra fields."),
      "",
      pick(lang, "【输出格式】", "【Định dạng đầu ra】", "[Output format]"),
      "{",
      '  "beats": [',
      "    {",
      '      "key": "open_hook",',
      `      "label": "${getVolumeBeatRoleLabel("open_hook")}",`,
      pick(lang,
        '      "title": "夜市夺印",',
        '      "title": "Đoạt ấn ở chợ đêm",',
        '      "title": "The Night-Market Seal",'),
      pick(lang,
        '      "summary": "这一拍主要推进什么，它在本卷节奏中的职责是什么，以及它如何承接卷骨架中的对应承诺。",',
        '      "summary": "Beat này chủ yếu đẩy điều gì, trách nhiệm của nó trong nhịp của tập, và nó nối lại cam kết tương ứng trong khung tập ra sao.",',
        '      "summary": "What this beat primarily advances, its responsibility in the volume\'s pacing, and how it ties back to the matching promise in the volume skeleton.",'),
      pick(lang,
        '      "chapterSpanHint": "1-2章",',
        '      "chapterSpanHint": "chương 1-2",',
        '      "chapterSpanHint": "ch. 1-2",'),
      pick(lang,
        '      "mustDeliver": ["读者必须感知到的关键信号1", "必须建立的局面或冲突2"]',
        '      "mustDeliver": ["Tín hiệu then chốt người đọc phải cảm nhận được 1", "Cục diện hoặc xung đột phải xác lập 2"]',
        '      "mustDeliver": ["Key signal the reader must perceive 1", "Situation or conflict that must be established 2"]'),
      "    }",
      "  ]",
      "}",
      "",
      pick(lang, "【固定职能槽位】", "【Ô chức năng cố định】", "[Fixed function slots]"),
      pick(lang,
        "节奏职能 key 与 label 必须使用系统固定槽位，不能自由发明职能名。",
        "key và label của chức năng nhịp phải dùng đúng ô cố định của hệ thống, không được tự phát minh tên chức năng.",
        "The pacing-function key and label must use the system's fixed slots — do not invent function names."),
      pick(lang,
        "必需槽位（必须全部出现，且只能各出现一次）：",
        "Ô bắt buộc (phải xuất hiện đủ, mỗi ô đúng một lần):",
        "Required slots (all must appear, each exactly once):"),
      REQUIRED_SLOT_LINES,
      pick(lang,
        "可选槽位（最多使用 2 个，用于本卷确实需要的额外阶段）：",
        "Ô tùy chọn (dùng tối đa 2, cho các giai đoạn bổ sung tập này thực sự cần):",
        "Optional slots (use at most 2, for extra phases this volume genuinely needs):"),
      OPTIONAL_SLOT_LINES,
      pick(lang, `推荐顺序：${SLOT_ORDER_LINE}`, `Thứ tự khuyến nghị: ${SLOT_ORDER_LINE}`, `Recommended order: ${SLOT_ORDER_LINE}`),
      "",
      pick(lang, "【硬性要求】", "【Yêu cầu bắt buộc】", "[Hard requirements]"),
      pick(lang,
        "1. beats 必须输出 6-8 条，且必须覆盖全部 6 个必需槽位。",
        "1. beats phải xuất 6-8 mục, và phải phủ hết cả 6 ô bắt buộc.",
        "1. beats must output 6-8 items and must cover all 6 required slots."),
      pick(lang,
        "2. 每个 beat 都必须完整包含 key、label、title、summary、chapterSpanHint、mustDeliver 六个字段。",
        "2. Mỗi beat phải chứa đủ sáu field: key, label, title, summary, chapterSpanHint, mustDeliver.",
        "2. Every beat must fully contain six fields: key, label, title, summary, chapterSpanHint, mustDeliver."),
      pick(lang,
        "3. key 只能使用上面列出的固定槽位；label 必须原样等于该槽位在上面列表中括号内的稳定职能名。",
        "3. key chỉ được dùng các ô cố định liệt kê ở trên; label phải bằng đúng (nguyên văn) tên chức năng ổn định trong ngoặc của ô đó ở danh sách trên.",
        "3. key may only use the fixed slots listed above; label must equal, verbatim, that slot's stable function name shown in parentheses in the list above."),
      pick(lang,
        "4. title 必须是本卷定制短标题，8 字以内，体现本卷具体卖点或局面，不能只重复 label。",
        "4. title phải là tiêu đề ngắn riêng cho tập này, tối đa ~8 chữ, thể hiện điểm hấp dẫn hoặc cục diện cụ thể của tập, không chỉ lặp lại label.",
        "4. title must be a short custom title for this volume (~8 words max) reflecting this volume's concrete appeal or situation — not a repeat of label."),
      pick(lang,
        "5. summary 必须写清：这一拍推进了什么、承担什么节奏职责、与卷骨架中的哪类承诺或压力相关。",
        "5. summary phải nói rõ: beat này đẩy được gì, gánh trách nhiệm nhịp nào, liên quan tới loại cam kết hoặc áp lực nào trong khung tập.",
        "5. summary must state: what this beat advances, which pacing responsibility it carries, and which kind of promise or pressure in the volume skeleton it relates to."),
      pick(lang,
        "6. chapterSpanHint 必须是非空字符串，使用类似“1-2章”“3章”“7-8章”的表达。",
        "6. chapterSpanHint phải là chuỗi không rỗng, dùng cách viết như \"chương 1-2\", \"chương 3\", \"chương 7-8\".",
        "6. chapterSpanHint must be a non-empty string, written like \"ch. 1-2\", \"ch. 3\", \"ch. 7-8\"."),
      pick(lang,
        "7. mustDeliver 必须是 1-6 条非空字符串，优先写必须兑现的局面、信号、压力、转向、读者感知，不要只写抽象口号。",
        "7. mustDeliver phải là 1-6 chuỗi không rỗng, ưu tiên viết cục diện, tín hiệu, áp lực, chuyển hướng, cảm nhận người đọc bắt buộc phải trả — không chỉ viết khẩu hiệu trừu tượng.",
        "7. mustDeliver must be 1-6 non-empty strings — prioritize the situations, signals, pressure, pivots, and reader perceptions that must be delivered, not abstract slogans."),
      pick(lang,
        "8. 各 beat 的节奏职责必须有差异，不能把多个 beat 都写成‘冲突升级’或‘继续推进’。",
        "8. Trách nhiệm nhịp của các beat phải khác nhau, không được viết nhiều beat đều là \"leo thang xung đột\" hay \"tiếp tục đẩy\".",
        "8. Each beat's pacing responsibility must differ — do not write several beats all as \"conflict escalation\" or \"keep advancing\"."),
      pick(lang,
        "9. 不要把高潮前挤压写成提前高潮，也不要把卷尾钩子写成泛泛留白。",
        "9. Đừng viết nút thắt trước cao trào thành cao trào sớm, cũng đừng viết móc câu cuối tập thành để lửng chung chung.",
        "9. Do not write the pre-climax squeeze as an early climax, and do not write the volume-end hook as a vague blank."),
      pick(lang,
        `10. 所有 chapterSpanHint 必须从第 1 章连续覆盖到第 ${input.targetChapterCount} 章附近，不能只覆盖少量开头章节。`,
        `10. Tất cả chapterSpanHint phải phủ liên tục từ chương 1 đến khoảng chương ${input.targetChapterCount}, không chỉ phủ vài chương đầu.`,
        `10. All chapterSpanHint values together must continuously cover from chapter 1 to around chapter ${input.targetChapterCount} — not just a few opening chapters.`),
      pick(lang,
        "11. summary 控制在 40-120 字；mustDeliver 每条控制在 12-80 字，禁止展开成剧情正文。",
        "11. summary giữ trong 40-120 ký tự; mỗi mục mustDeliver giữ trong 12-80 ký tự; cấm triển khai thành chính văn cốt truyện.",
        "11. Keep summary within 40-120 characters; each mustDeliver item within 12-80 characters; do not expand into plot prose."),
      pick(lang,
        "12. 整份输出只保留 6-8 个节奏段所需信息，完成最后一个 beat 后立即结束 JSON。",
        "12. Toàn bộ đầu ra chỉ giữ thông tin cần cho 6-8 đoạn nhịp; hoàn thành beat cuối thì kết thúc JSON ngay.",
        "12. The whole output keeps only the info needed for 6-8 pacing segments; end the JSON immediately after the last beat."),
      "",
      pick(lang, "【卷骨架承接要求】", "【Yêu cầu nối tiếp khung tập】", "[Volume-skeleton follow-through]"),
      pick(lang,
        "1. open_hook 必须承接 target_volume 中的 openingHook 与 mainPromise。",
        "1. open_hook phải nối tiếp openingHook và mainPromise trong target_volume.",
        "1. open_hook must follow through on openingHook and mainPromise in target_volume."),
      pick(lang,
        "2. first_escalation 与中前段 beats 必须逐步体现 primaryPressureSource 与 escalationMode。",
        "2. first_escalation và các beat đoạn đầu-giữa phải dần thể hiện primaryPressureSource và escalationMode.",
        "2. first_escalation and the early-to-mid beats must progressively express primaryPressureSource and escalationMode."),
      pick(lang,
        "3. midpoint_turn 必须体现 midVolumeRisk 或等价的局面转向，不能只是线性加码。",
        "3. midpoint_turn phải thể hiện midVolumeRisk hoặc một chuyển hướng cục diện tương đương, không chỉ là cộng dồn tuyến tính.",
        "3. midpoint_turn must express midVolumeRisk or an equivalent situation pivot — not just linear stacking."),
      pick(lang,
        "4. climax 必须承接卷高潮承诺，形成明确兑现。",
        "4. climax phải nối tiếp lời hứa cao trào của tập, tạo sự trả nợ rõ ràng.",
        "4. climax must follow through on the volume's climax promise, forming a clear payoff."),
      pick(lang,
        "5. end_hook 必须承接 nextVolumeHook，并通过 resetPoint 或残局重组形成下一卷入口。",
        "5. end_hook phải nối tiếp nextVolumeHook, và qua resetPoint hoặc tái cấu trúc tàn cục tạo lối vào tập sau.",
        "5. end_hook must follow through on nextVolumeHook and, via resetPoint or a reshuffled aftermath, form the entry to the next volume."),
      pick(lang,
        "6. 如上下文给出「反转/揭示密度」：dense 时，midpoint_turn 与至少一个 complication 必须是真正的真相揭示或认知反转，且每个揭示型 beat 的 mustDeliver 必须点名它推翻的是此前哪一条已知信息或读者判断；climax 也应包含一次揭示而不仅是一场对抗。rare 时，这些拍点应表现为关系、情绪或处境的转变，不要写成惊吓式反转。",
        "6. Nếu ngữ cảnh có \"Mật độ đảo chiều/hé lộ\": khi dense, midpoint_turn và ít nhất một complication phải là hé lộ sự thật hoặc đảo nhận thức thật sự, và mustDeliver của mỗi beat kiểu hé lộ phải chỉ tên nó lật đổ thông tin đã biết hoặc phán đoán nào của người đọc trước đó; climax cũng phải chứa một cú hé lộ chứ không chỉ là một trận đối đầu. Khi rare, các beat này thể hiện dưới dạng chuyển biến quan hệ, cảm xúc hoặc hoàn cảnh, không viết thành cú lật gây sốc.",
        "6. If the context provides a \"Reversal / reveal density\": when dense, midpoint_turn and at least one complication must be genuine truth reveals or perception reversals, and each reveal beat's mustDeliver must name which earlier known fact or reader assumption it overturns; climax must also contain a reveal, not just a confrontation. When rare, these beats present as shifts in relationship, emotion, or circumstance — not shock twists."),
      pick(lang,
        "6a. dense 时，全卷至少要有一个 beat 是「提出/加深一个问题但刻意不回答」——把它写进该 beat 的 mustDeliver（例如“读者确认了 X 存在，但仍不知道 X 从何而来”）。不要每个 beat 都给答案。",
        "6a. Khi dense, cả tập phải có ít nhất một beat là \"nêu / khoét sâu một câu hỏi nhưng cố tình không trả lời\" — viết điều đó vào mustDeliver của beat đó (ví dụ \"người đọc xác nhận X tồn tại, nhưng vẫn không biết X từ đâu ra\"). Đừng beat nào cũng cho đáp án.",
        "6a. When dense, the volume must have at least one beat that \"raises or deepens a question but deliberately does not answer it\" — write that into that beat's mustDeliver (e.g. \"the reader confirms X exists but still does not know where X came from\"). Do not give an answer in every beat."),
      pick(lang,
        "6b. 如上下文给出该卷的「本卷让读者相信、但后续会被推翻的判断」，必须有一个 beat 明确把这个错误判断坐实到读者心里，为后面的推翻做铺垫。",
        "6b. Nếu ngữ cảnh cho \"phán đoán mà tập này khiến người đọc tin nhưng về sau sẽ bị lật\", phải có một beat làm cho phán đoán sai đó ăn chắc vào đầu người đọc, để tích thế cho cú lật về sau.",
        "6b. If the context gives \"the belief this volume makes the reader hold but that will later be overturned\", one beat must firmly plant that wrong belief in the reader's mind, setting up the later overturn."),
      pick(lang,
        "6c. 如上下文的「流派模式约束」给出「反转公平度」：clued 或 mixed 时，对每一个揭示型 beat（其 mustDeliver 中写了它推翻某条旧信息），必须能在更早的一个 beat（open_hook、first_escalation 或更早的 complication）的 mustDeliver 中找到对应的铺垫——把要被推翻的那个细节、说法或误导性线索明确写进那个更早 beat 的 mustDeliver 里，不能只在揭示型 beat 里凭空提及“早有伏笔”。blindside 时不强制这条，可以没有预先铺垫直接揭示。同时参考「反转力度」与「反转波及层级」：力度=severe 或层级=worldview_shattering 时，dense 揭示型 beat 至少要有一个改变对整个故事/世界规则的理解，不能只是修正一个小细节；力度=mild 时不要写成认知颠覆。",
        "6c. Nếu \"Ràng buộc Story Mode\" trong ngữ cảnh cho \"Độ công bằng của cú lật\": khi clued hoặc mixed, mỗi beat kiểu hé lộ (có mustDeliver ghi nó lật đổ một thông tin cũ) đều phải tìm được mồi tương ứng ở một beat SỚM HƠN (open_hook, first_escalation, hoặc một complication trước đó) — viết rõ chi tiết, phát ngôn hoặc manh mối gây hiểu lầm sẽ bị lật vào mustDeliver của beat sớm hơn đó, không được chỉ nói suông \"đã có phục bút\" ở beat hé lộ. Khi blindside thì không bắt buộc, có thể hé lộ trực tiếp không cần cài mồi trước. Đồng thời tham khảo \"Sức nặng cú lật\" và \"Tầng bị cú lật tác động\": khi sức nặng=severe hoặc tầng=worldview_shattering, ít nhất một beat hé lộ ở tập dense phải đổi cách hiểu về cả câu chuyện/luật lệ thế giới, không chỉ sửa một chi tiết nhỏ; khi sức nặng=mild thì đừng viết thành lật đổ nhận thức.",
        "6c. If the context's \"Story-mode constraints\" give a \"Twist fairness\": when clued or mixed, every reveal-type beat (whose mustDeliver states it overturns an earlier known fact) must have a matching plant in an EARLIER beat (open_hook, first_escalation, or an earlier complication) — write the specific detail, statement, or misleading clue that will later be overturned directly into that earlier beat's mustDeliver; do not just assert \"foreshadowed earlier\" inside the reveal beat itself with nothing to point to. When blindside, this is not required — the reveal may land with no prior setup. Also consult \"Twist intensity\" and \"Twist scope\": when intensity=severe or scope=worldview_shattering, at least one reveal beat in a dense volume must change the understanding of the whole story/world rules, not just correct a small detail; when intensity=mild, do not write it as a cognitive shattering."),
      "",
      pick(lang, "【质量要求】", "【Yêu cầu chất lượng】", "[Quality requirements]"),
      pick(lang,
        "1. 每个 beat 都要回答：这一段章节为什么必须存在。",
        "1. Mỗi beat phải trả lời: vì sao khoảng chương này bắt buộc phải tồn tại.",
        "1. Every beat must answer: why must this chapter span exist."),
      pick(lang,
        "2. 相邻 beat 要形成递进或转向关系，而不是同义重复。",
        "2. Các beat liền kề phải tạo quan hệ tăng tiến hoặc chuyển hướng, không lặp lại đồng nghĩa.",
        "2. Adjacent beats must form a progression or pivot relationship, not synonymous repetition."),
      pick(lang,
        "3. 节奏上要体现前段立钩子与承诺，中段换挡与抬代价，后段挤压与兑现，结尾留入口。",
        "3. Về nhịp: đoạn đầu dựng móc câu và cam kết, đoạn giữa chuyển số và nâng cái giá, đoạn sau dồn ép và trả nợ, kết chừa lối vào.",
        "3. Pacing-wise: early beats set hooks and promises, middle beats shift gear and raise the cost, late beats squeeze and pay off, the end leaves an entry point."),
      pick(lang,
        "4. title 要具体到本卷，例如“夜市夺印”“宗门试炼开局”，不要输出职能名复读。",
        "4. title phải cụ thể cho tập này, ví dụ \"Đoạt ấn ở chợ đêm\", \"Mở màn thử thách môn phái\"; không xuất lại tên chức năng.",
        "4. title must be specific to this volume, e.g. \"The Night-Market Seal\", \"Opening of the Sect Trial\" — do not just echo the function name."),
      pick(lang,
        "5. 信息不足时也必须给出完整字段，但应保守，不要发明脱离上下文的大设定。",
        "5. Khi thiếu thông tin vẫn phải điền đủ field, nhưng phải bảo thủ, không phát minh thiết lập lớn ngoài ngữ cảnh.",
        "5. When information is missing, still fill all fields — but be conservative and do not invent major setting elements outside the context."),
      "",
      `Current volume target chapter count: ${input.targetChapterCount}.`,
      `chapterSpanHint must use volume-local numbering only, start from 1 inside the current volume, and never exceed ${input.targetChapterCount}. Never use whole-book absolute chapter numbers.`,
    ].join("\n")),
    new HumanMessage([
      pick(lang,
        "请基于以下上下文，为当前目标卷生成单卷 beat sheet。",
        "Dựa trên ngữ cảnh dưới đây, hãy tạo beat sheet cho tập mục tiêu hiện tại.",
        "Based on the context below, generate the beat sheet for the current target volume."),
      "",
      pick(lang, "【输出要求】", "【Yêu cầu đầu ra】", "[Output requirements]"),
      pick(lang, "- 只输出 JSON", "- Chỉ xuất JSON", "- Output JSON only"),
      pick(lang, "- 不补充 schema 之外字段", "- Không thêm field ngoài schema", "- Do not add fields outside the schema"),
      pick(lang,
        "- key/label 使用固定职能槽位，title 写本卷定制短标题",
        "- key/label dùng ô chức năng cố định, title viết tiêu đề ngắn riêng cho tập",
        "- key/label use the fixed function slots; title is a short custom title for this volume"),
      pick(lang,
        "- beats 是节奏任务分段，不是章节目录",
        "- beats là các đoạn nhiệm vụ nhịp, không phải mục lục chương",
        "- beats are pacing-task segments, not a chapter list"),
      pick(lang,
        "- 优先保证与卷骨架承接关系清晰、节奏职责明确、后续可拆章",
        "- Ưu tiên: nối tiếp khung tập rõ ràng, trách nhiệm nhịp minh bạch, tách chương được về sau",
        "- Prioritize: clear follow-through from the volume skeleton, explicit pacing responsibilities, and later chapter-splittability"),
      "",
      pick(lang, "【当前卷节奏板上下文】", "【Ngữ cảnh beat sheet của tập hiện tại】", "[Current volume beat-sheet context]"),
      `- Current volume target chapter count: ${input.targetChapterCount}`,
      "- chapterSpanHint must stay within this volume only; do not use whole-book absolute chapter numbers",
      `- all beat spans together must cover chapters 1-${input.targetChapterCount} of this volume`,
      "",
      renderSelectedContextBlocks(context),
    ].join("\n")),
  ];
  },
  postValidate: (output, input) => {
    const coverage = validateBeatSheetChapterCoverage({
      beatSheet: output,
      targetChapterCount: input.targetChapterCount,
    });
    if (!coverage.accepted) {
      throw new Error(coverage.message ?? "当前卷节奏板章节跨度没有覆盖目标章数。");
    }
    return output;
  },
};

export { buildVolumeBeatSheetContextBlocks };
