import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { PromptAsset } from "../../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../../core/renderContextBlocks";
import { createBookVolumeSkeletonSchema } from "../../../../services/novel/volume/volumeGenerationSchemas";
import { type VolumeSkeletonPromptInput } from "./shared";
import { buildVolumeSkeletonContextBlocks } from "./contextBlocks";
import { NOVEL_PROMPT_BUDGETS } from "../promptBudgetProfiles";
import { pick } from "./localize";

// export function createVolumeSkeletonPrompt(
//   targetVolumeCount: number,
// ): PromptAsset<
//   VolumeSkeletonPromptInput,
//   ReturnType<typeof createBookVolumeSkeletonSchema>["_output"]
// > {
//   return {
//     id: "novel.volume.skeleton",
//     version: "v2",
//     taskType: "planner",
//     mode: "structured",
//     language: "zh",
//     contextPolicy: {
//       maxTokensBudget: NOVEL_PROMPT_BUDGETS.volumeSkeleton,
//       requiredGroups: ["book_contract", "strategy_context", "chapter_budget"],
//       preferredGroups: ["macro_constraints", "existing_volume_window", "guidance"],
//     },
//     outputSchema: createBookVolumeSkeletonSchema(targetVolumeCount),
//     render: (_input, context) => [
//       new SystemMessage([
//         "你是长篇网文分卷骨架规划助手。",
//         "当前阶段只做卷级骨架，不展开章节。",
//         "",
//         `必须严格输出 ${targetVolumeCount} 卷。`,
//         "每卷必须包含 title、summary、openingHook、mainPromise、primaryPressureSource、coreSellingPoint、escalationMode、protagonistChange、midVolumeRisk、climax、payoffType、nextVolumeHook、resetPoint、openPayoffs。",
//         "骨架必须服从上游策略，特别是 hard/soft 规划分层。",
//       ].join("\n")),
//       new HumanMessage([
//         "分卷骨架上下文：",
//         renderSelectedContextBlocks(context),
//       ].join("\n")),
//     ],
//   };
// }
export function createVolumeSkeletonPrompt(
  targetVolumeCount: number,
): PromptAsset<
  VolumeSkeletonPromptInput,
  ReturnType<typeof createBookVolumeSkeletonSchema>["_output"]
> {
  return {
    id: "novel.volume.skeleton",
    version: "v3",
    taskType: "planner",
    mode: "structured",
    language: "zh",
    contextPolicy: {
      maxTokensBudget: NOVEL_PROMPT_BUDGETS.volumeSkeleton,
      requiredGroups: ["book_contract", "strategy_context", "chapter_budget"],
      preferredGroups: ["macro_constraints", "existing_volume_window", "guidance"],
    },
    outputSchema: createBookVolumeSkeletonSchema(targetVolumeCount),
    render: (_input, context) => {
      const lang = context.promptLanguage;
      return [
      new SystemMessage([
        pick(lang,
          "你是长篇连载小说分卷骨架规划助手，负责把整本书的上游策略拆解为可执行的卷级骨架。",
          "Bạn là trợ lý hoạch định khung phân tập cho tiểu thuyết dài kỳ, chịu trách nhiệm tách chiến lược tổng thể của cả sách thành khung cấp tập khả thi.",
          "You are a volume-skeleton planning assistant for long-form serialized fiction, responsible for breaking the book's upstream strategy into an executable per-volume skeleton."),
        "",
        pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
        pick(lang,
          `必须严格输出 ${targetVolumeCount} 卷，数量不得多也不得少。`,
          `Phải xuất đúng ${targetVolumeCount} tập, không nhiều không ít.`,
          `Output exactly ${targetVolumeCount} volumes — no more, no fewer.`),
        pick(lang,
          "当前阶段只做“卷级骨架规划”，不得展开为章节大纲、场景细纲、人物小传或具体对话。",
          "Giai đoạn này chỉ làm \"khung cấp tập\", không được triển khai thành dàn ý chương, cốt cảnh chi tiết, tiểu sử nhân vật hay đối thoại cụ thể.",
          "At this stage produce only the per-volume skeleton — do not expand into a chapter outline, scene breakdown, character bios, or specific dialogue."),
        pick(lang,
          "每卷 summary 必须是卷级概括，不得写成详细剧情复述。",
          "summary của mỗi tập phải là khái quát cấp tập, không viết thành thuật lại tình tiết chi tiết.",
          "Each volume's summary must be a volume-level overview, not a detailed plot retelling."),
        pick(lang,
          "每个文本字段只写 1-2 句，单字段不超过 120 字；openPayoffs 最多 8 条，每条不超过 80 字。",
          "Mỗi field văn bản chỉ viết 1-2 câu, không quá 120 ký tự mỗi field; openPayoffs tối đa 8 mục, mỗi mục không quá 80 ký tự.",
          "Each text field is 1-2 sentences, at most 120 characters; openPayoffs has at most 8 items, each at most 80 characters."),
        pick(lang,
          "完成最后一卷后立即结束 JSON，禁止续写章节、正文、自我检查过程或同义复述。",
          "Hoàn thành tập cuối thì kết thúc JSON ngay; cấm viết tiếp chương, chính văn, quá trình tự kiểm hay diễn giải lặp lại.",
          "Once the last volume is done, end the JSON immediately — do not continue with chapters, prose, a self-check process, or synonymous restatement."),
        "",
        pick(lang, "【字段要求】", "【Yêu cầu field】", "[Field requirements]"),
        pick(lang,
          "每卷必须完整包含以下字段，不得缺漏、合并或改名：",
          "Mỗi tập phải chứa đủ các field sau, không thiếu, không gộp, không đổi tên:",
          "Each volume must fully contain the following fields — none missing, merged, or renamed:"),
        "title, summary, openingHook, mainPromise, primaryPressureSource, coreSellingPoint, escalationMode, protagonistChange, midVolumeRisk, climax, payoffType, nextVolumeHook, resetPoint, openPayoffs.",
        "",
        pick(lang, "【规划原则】", "【Nguyên tắc lập kế hoạch】", "[Planning principles]"),
        pick(lang,
          "1. 骨架必须严格服从上游策略与书籍契约。",
          "1. Khung phải tuân thủ nghiêm ngặt chiến lược tổng thể và book contract.",
          "1. The skeleton must strictly obey the upstream strategy and the book contract."),
        pick(lang,
          "2. hard 规划决定不可违背的主线推进、阶段目标、核心因果与关键兑现顺序。",
          "2. Kế hoạch cứng quyết định các thứ không được vi phạm: đẩy tuyến chính, mục tiêu giai đoạn, nhân quả cốt lõi và thứ tự trả nợ then chốt.",
          "2. Hard planning fixes the inviolable main-line progression, phase goals, core causality, and key payoff order."),
        pick(lang,
          "3. soft 规划决定每卷的节奏包装、冲突表现方式、情绪色彩与卖点呈现方式。",
          "3. Kế hoạch mềm quyết định cách đóng gói nhịp, cách thể hiện xung đột, sắc thái cảm xúc và cách trình bày điểm hấp dẫn của mỗi tập.",
          "3. Soft planning decides each volume's pacing packaging, how conflict is expressed, emotional color, and how the appeal is presented."),
        pick(lang,
          "4. 输出时必须体现：硬推进连续，软体验变化。",
          "4. Đầu ra phải thể hiện: đẩy cứng thì liên tục, trải nghiệm mềm thì thay đổi.",
          "4. The output must show: hard progression is continuous, soft experience varies."),
        "",
        pick(lang, "【分卷质量要求】", "【Yêu cầu chất lượng phân tập】", "[Volume quality requirements]"),
        pick(lang,
          "1. 每卷都要有独立成立的阅读承诺，不能只是过渡卷。",
          "1. Mỗi tập phải có một lời hứa đọc tự thân đứng vững, không chỉ là tập chuyển tiếp.",
          "1. Every volume must have a self-standing reading promise — not just a transitional volume."),
        pick(lang,
          "2. 相邻两卷的 coreSellingPoint 不应重复，必须体现卖点差异。",
          "2. coreSellingPoint của hai tập liền kề không nên trùng, phải thể hiện khác biệt điểm hấp dẫn.",
          "2. Adjacent volumes' coreSellingPoint must not repeat — they must show differentiated appeal."),
        pick(lang,
          "3. 相邻两卷的 primaryPressureSource 或 escalationMode 应尽量变化，避免同质化升级。",
          "3. primaryPressureSource hoặc escalationMode của hai tập liền kề nên thay đổi, tránh leo thang đồng nhất.",
          "3. Adjacent volumes' primaryPressureSource or escalationMode should vary — avoid homogeneous escalation."),
        pick(lang,
          "4. 每卷都必须回答：这卷为什么值得单独存在。",
          "4. Mỗi tập phải trả lời: vì sao tập này đáng tồn tại riêng.",
          "4. Every volume must answer: why does this volume deserve to exist on its own."),
        pick(lang,
          "5. 分卷整体必须形成清晰递进：开局立钩子，中段抬代价，后段放大不可逆风险，临近结尾增强兑现密度。",
          "5. Toàn bộ phân tập phải tạo tăng tiến rõ ràng: đầu dựng móc câu, giữa nâng cái giá, sau khuếch đại rủi ro không thể đảo ngược, gần kết tăng mật độ trả nợ.",
          "5. The volumes overall must form clear progression: opening sets hooks, the middle raises the cost, the late run amplifies irreversible risk, and near the end payoff density increases."),
        pick(lang,
          "6. 如果目标卷数为 3-4 卷，必须体现清晰三幕式或四段式结构，不能压成开局卷加结局卷。",
          "6. Nếu số tập mục tiêu là 3-4, phải thể hiện cấu trúc ba hồi hoặc bốn đoạn rõ ràng, không được ép thành tập mở đầu cộng tập kết.",
          "6. If the target is 3-4 volumes, show a clear three-act or four-part structure — do not collapse into an opening volume plus an ending volume."),
        pick(lang,
          "7. 如果目标卷数为 12 卷以上，必须体现卖点轮换、压力源轮换和阶段兑现密度，避免多卷只重复同一种升级。",
          "7. Nếu số tập mục tiêu từ 12 trở lên, phải thể hiện luân phiên điểm hấp dẫn, luân phiên nguồn áp lực và mật độ trả nợ theo giai đoạn, tránh nhiều tập chỉ lặp lại một kiểu leo thang.",
          "7. If the target is 12+ volumes, show rotation of appeal, rotation of pressure sources, and phased payoff density — avoid many volumes repeating the same one escalation."),
        "",
        pick(lang, "【节奏要求】", "【Yêu cầu nhịp】", "[Pacing requirements]"),
        pick(lang,
          "1. 第一卷必须承担强开书职能，快速建立主卖点、核心困境和追更理由。",
          "1. Tập một phải gánh chức năng mở sách mạnh: nhanh chóng dựng điểm hấp dẫn chính, thế bí cốt lõi và lý do đọc tiếp.",
          "1. Volume one must carry a strong opening function — quickly establish the core appeal, the core dilemma, and a reason to keep reading."),
        pick(lang,
          "2. 中段卷不能只承担搬运剧情，必须提供新的局面变化、新压力或新兑现。",
          "2. Các tập giữa không được chỉ làm nhiệm vụ vận chuyển cốt truyện, phải cung cấp biến chuyển cục diện mới, áp lực mới hoặc trả nợ mới.",
          "2. Middle volumes must not just transport plot — they must provide new situation changes, new pressure, or new payoff."),
        pick(lang,
          "3. 后段卷必须加强不可回退感，避免只是重复前中期套路。",
          "3. Các tập đoạn sau phải tăng cảm giác không thể lùi lại, tránh chỉ lặp lại mô-típ đoạn đầu-giữa.",
          "3. Late volumes must intensify the sense of no-going-back — avoid just repeating early/mid patterns."),
        pick(lang,
          "4. nextVolumeHook 必须推动读者自然进入下一卷，不能只是泛泛留悬念。",
          "4. nextVolumeHook phải đẩy người đọc vào tập sau một cách tự nhiên, không chỉ là để lửng nghi vấn chung chung.",
          "4. nextVolumeHook must naturally push the reader into the next volume — not just leave a vague suspense."),
        "",
        pick(lang, "【禁止事项】", "【Cấm kỵ】", "[Prohibitions]"),
        pick(lang,
          "禁止脱离上下文自行发明大设定。",
          "Cấm tự ý phát minh thiết lập lớn ngoài ngữ cảnh.",
          "Do not invent major setting elements outside the context."),
        pick(lang,
          "禁止提前透支上游未允许兑现的核心 payoff。",
          "Cấm vắt trước các payoff cốt lõi mà chiến lược tổng thể chưa cho phép trả.",
          "Do not spend core payoffs early that the upstream strategy has not authorized."),
        pick(lang,
          "禁止让多卷承担同一种冲突功能而缺乏层次变化。",
          "Cấm để nhiều tập gánh cùng một chức năng xung đột mà thiếu thay đổi tầng lớp.",
          "Do not let multiple volumes carry the same conflict function without layered variation."),
        pick(lang,
          "禁止把 resetPoint 写成“回归平静”式空话，必须说明卷末状态如何重组下一卷起点。",
          "Cấm viết resetPoint kiểu câu rỗng \"trở lại yên bình\"; phải nói rõ trạng thái cuối tập tái cấu trúc điểm khởi đầu tập sau như thế nào.",
          "Do not write resetPoint as an empty \"return to calm\" phrase — state how the volume-end state reconstitutes the next volume's starting point."),
        "",
        pick(lang,
          "你的目标不是把剧情写长，而是把整本书的分卷结构搭稳。",
          "Mục tiêu của bạn không phải viết cốt truyện cho dài, mà là dựng vững cấu trúc phân tập của cả cuốn sách.",
          "Your goal is not to make the plot longer, but to make the book's volume structure solid."),
      ].join("\n")),
      new HumanMessage([
        pick(lang,
          "请基于以下上下文，为整本书规划分卷骨架。",
          "Dựa trên ngữ cảnh dưới đây, hãy hoạch định khung phân tập cho cả cuốn sách.",
          "Based on the context below, plan the volume skeleton for the whole book."),
        "",
        pick(lang, "【输出要求】", "【Yêu cầu đầu ra】", "[Output requirements]"),
        pick(lang, `- 严格输出 ${targetVolumeCount} 卷`, `- Xuất đúng ${targetVolumeCount} tập`, `- Output exactly ${targetVolumeCount} volumes`),
        pick(lang, "- 不补充 schema 之外的字段", "- Không thêm field ngoài schema", "- Do not add fields outside the schema"),
        pick(lang, "- 每卷信息要简洁、明确、可执行", "- Thông tin mỗi tập phải ngắn gọn, rõ ràng, khả thi", "- Each volume's info must be concise, clear, and actionable"),
        pick(lang,
          "- 优先保证分卷差异性、递进关系与商业可读性",
          "- Ưu tiên bảo đảm khác biệt giữa các tập, quan hệ tăng tiến và tính hấp dẫn thương mại",
          "- Prioritize inter-volume differentiation, progression, and commercial readability"),
        "",
        pick(lang, "【分卷骨架上下文】", "【Ngữ cảnh khung phân tập】", "[Volume-skeleton context]"),
        renderSelectedContextBlocks(context),
      ].join("\n")),
    ];
    },
  };
}
export { buildVolumeSkeletonContextBlocks };
