import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { PromptAsset } from "../../../core/promptTypes";
import type { VolumeCountRange } from "@ai-novel/shared/types/novel";
import { MAX_VOLUME_COUNT } from "@ai-novel/shared/types/volumePlanning";
import { renderSelectedContextBlocks } from "../../../core/renderContextBlocks";
import {
  createVolumeStrategyCritiqueSchema,
  createVolumeStrategySchema,
} from "../../../../services/novel/volume/volumeGenerationSchemas";
import {
  type VolumeStrategyCritiquePromptInput,
  type VolumeStrategyPromptInput,
} from "./shared";
import {
  buildVolumeStrategyContextBlocks,
  buildVolumeStrategyCritiqueContextBlocks,
} from "./contextBlocks";
import { NOVEL_PROMPT_BUDGETS } from "../promptBudgetProfiles";
import { pick } from "./localize";

interface CreateVolumeStrategyPromptConfig {
  maxVolumeCount?: number;
  allowedVolumeCountRange?: VolumeCountRange | null;
  decisionVolumeCountRange?: VolumeCountRange | null;
  fixedRecommendedVolumeCount?: number | null;
  hardPlannedVolumeRange?: VolumeCountRange | null;
}

export function createVolumeStrategyPrompt(
  config: CreateVolumeStrategyPromptConfig = {},
): PromptAsset<
  VolumeStrategyPromptInput,
  ReturnType<typeof createVolumeStrategySchema>["_output"]
> {
  const maxVolumeCount = config.maxVolumeCount ?? MAX_VOLUME_COUNT;
  const allowedVolumeCountRange = config.allowedVolumeCountRange ?? {
    min: 1,
    max: maxVolumeCount,
  };
  const decisionVolumeCountRange = config.decisionVolumeCountRange ?? allowedVolumeCountRange;
  const fixedRecommendedVolumeCount = typeof config.fixedRecommendedVolumeCount === "number"
    ? config.fixedRecommendedVolumeCount
    : null;
  const hardPlannedVolumeRange = config.hardPlannedVolumeRange ?? {
    min: 1,
    max: maxVolumeCount,
  };

  return {
    id: "novel.volume.strategy",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "zh",
    contextPolicy: {
      maxTokensBudget: NOVEL_PROMPT_BUDGETS.volumeStrategy,
      requiredGroups: ["book_contract", "volume_count_guidance"],
      preferredGroups: ["macro_constraints", "existing_volume_window", "guidance"],
      dropOrder: ["existing_volume_window"],
    },
    outputSchema: createVolumeStrategySchema({
      maxVolumeCount,
      allowedVolumeCountRange,
      decisionVolumeCountRange,
      fixedRecommendedVolumeCount,
      hardPlannedVolumeRange,
    }),
    render: (_input, context) => {
      const lang = context.promptLanguage;
      return [
      new SystemMessage([
        pick(lang,
          "你是长篇连载小说分卷策略规划助手。",
          "Bạn là trợ lý hoạch định chiến lược phân tập cho tiểu thuyết dài kỳ.",
          "You are a volume-strategy planning assistant for long-form serialized fiction."),
        pick(lang,
          "你的任务不是直接生成最终分卷骨架，而是先确定整本书应分几卷、哪些卷需要硬规划、哪些卷只保留软规划，并给出一套适合连载推进的分卷策略。",
          "Nhiệm vụ của bạn không phải tạo ngay khung phân tập cuối cùng, mà trước tiên xác định cả cuốn sách nên chia bao nhiêu tập, tập nào cần lập kế hoạch cứng, tập nào chỉ giữ kế hoạch mềm, và đưa ra một chiến lược phân tập phù hợp cho việc ra chương dài kỳ.",
          "Your task is not to produce the final volume skeleton, but first to decide how many volumes the book should have, which volumes need hard planning, which stay soft, and to give a volume strategy suited to a long serialized run."),
        "",
        pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
        pick(lang,
          "当前阶段只做整书层面的分卷策略，不展开单卷骨架，不展开章节，不补写剧情细纲。",
          "Giai đoạn này chỉ làm chiến lược phân tập ở cấp cả sách; không triển khai khung từng tập, không triển khai chương, không viết cốt truyện chi tiết.",
          "At this stage only produce the book-level volume strategy — do not expand per-volume skeletons, chapters, or detailed plot outlines."),
        pick(lang,
          "你的输出应服务后续分卷骨架生成，因此重点是：卷数、阶段划分、规划深度、前后期控制方式。",
          "Đầu ra của bạn phục vụ bước tạo khung phân tập sau đó, nên trọng tâm là: số tập, cách chia giai đoạn, độ sâu kế hoạch, cách kiểm soát đoạn đầu và đoạn sau.",
          "Your output feeds the later volume-skeleton step, so focus on: volume count, phase division, planning depth, and how the early vs. late run is controlled."),
        pick(lang,
          "只输出严格 JSON，不要输出 Markdown、解释、注释或额外文本。",
          "Chỉ xuất JSON nghiêm ngặt; không xuất Markdown, lời giải thích, chú thích hay văn bản thừa.",
          "Output strict JSON only — no Markdown, explanations, comments, or extra text."),
        "",
        pick(lang, "【硬性要求】", "【Yêu cầu bắt buộc】", "[Hard requirements]"),
        fixedRecommendedVolumeCount == null
          ? pick(lang,
            `recommendedVolumeCount 必须落在结构建议区间 ${decisionVolumeCountRange.min}-${decisionVolumeCountRange.max} 之间，且等于 volumes.length。`,
            `recommendedVolumeCount phải nằm trong khoảng đề xuất cấu trúc ${decisionVolumeCountRange.min}-${decisionVolumeCountRange.max}, và bằng volumes.length.`,
            `recommendedVolumeCount must fall within the structural suggestion range ${decisionVolumeCountRange.min}-${decisionVolumeCountRange.max}, and equal volumes.length.`)
          : pick(lang,
            `recommendedVolumeCount 必须严格等于 ${fixedRecommendedVolumeCount}，且等于 volumes.length。`,
            `recommendedVolumeCount phải bằng đúng ${fixedRecommendedVolumeCount}, và bằng volumes.length.`,
            `recommendedVolumeCount must be exactly ${fixedRecommendedVolumeCount}, and equal volumes.length.`),
        pick(lang,
          `hardPlannedVolumeCount 必须落在 ${hardPlannedVolumeRange.min}-${hardPlannedVolumeRange.max} 之间，且不能大于 recommendedVolumeCount。`,
          `hardPlannedVolumeCount phải nằm trong khoảng ${hardPlannedVolumeRange.min}-${hardPlannedVolumeRange.max}, và không được lớn hơn recommendedVolumeCount.`,
          `hardPlannedVolumeCount must fall within ${hardPlannedVolumeRange.min}-${hardPlannedVolumeRange.max}, and must not exceed recommendedVolumeCount.`),
        pick(lang,
          "前 hardPlannedVolumeCount 卷的 planningMode 必须是 hard，后续卷必须是 soft。",
          "planningMode của hardPlannedVolumeCount tập đầu phải là hard, các tập sau phải là soft.",
          "The first hardPlannedVolumeCount volumes must have planningMode hard; the rest must be soft."),
        pick(lang,
          "如果 recommendedVolumeCount 较多，后半部分必须保留足够软规划空间，不能提前写死。",
          "Nếu recommendedVolumeCount lớn, nửa sau phải chừa đủ khoảng kế hoạch mềm, không được chốt cứng trước.",
          "If recommendedVolumeCount is large, the back half must keep enough soft-planning room — do not lock it down early."),
        pick(lang,
          "如果上下文给出了 user preferred volume count，必须严格采用，不得擅自改卷数。",
          "Nếu ngữ cảnh có user preferred volume count, phải dùng đúng, không được tự đổi số tập.",
          "If the context gives a user preferred volume count, adopt it exactly — do not change the count."),
        pick(lang,
          "如果上下文给出了 respected existing volume count，也必须严格沿用，该卷数代表作者已确认的草稿结构。",
          "Nếu ngữ cảnh có respected existing volume count, cũng phải giữ đúng — số tập đó là cấu trúc bản nháp tác giả đã xác nhận.",
          "If the context gives a respected existing volume count, keep it exactly — that count is the author's confirmed draft structure."),
        pick(lang,
          "如果没有固定卷数，必须在结构建议区间内结合故事结构决策，不要只按章节数平均除法切卷。",
          "Nếu không có số tập cố định, phải quyết định trong khoảng đề xuất cấu trúc dựa trên cấu trúc truyện — không chia tập bằng phép chia đều số chương.",
          "If there is no fixed count, decide within the suggested range based on story structure — do not split volumes by evenly dividing the chapter count."),
        pick(lang,
          "60 章以上默认至少保留三段结构，避免压成“开局卷 + 结局卷”导致中段失焦。",
          "Từ 60 chương trở lên, mặc định giữ ít nhất ba đoạn cấu trúc, tránh ép thành \"tập mở đầu + tập kết\" khiến đoạn giữa mất trọng tâm.",
          "For 60+ chapters, default to at least a three-part structure — avoid collapsing into \"opening volume + ending volume\" and losing the middle."),
        pick(lang,
          "超长篇必须避免把大量章节压成少数巨卷；不要让单卷粗到失去阶段感、回报节点和卷级工作台意义。",
          "Truyện siêu dài phải tránh dồn nhiều chương vào vài tập khổng lồ; đừng để một tập thô đến mức mất cảm giác giai đoạn, mất mốc phần thưởng và mất ý nghĩa của không gian làm việc cấp tập.",
          "Very long books must avoid packing many chapters into a few giant volumes — a volume must not be so coarse that it loses its sense of phase, its reward beats, and its per-volume-workspace value."),
        pick(lang,
          "如果 Story macro 存在，每个 volume.roleLabel 都必须能映射到主线卖点、冲突升级、成长路径或结尾风味之一。",
          "Nếu có Story macro, mỗi volume.roleLabel phải ánh xạ được về một trong: điểm hấp dẫn tuyến chính, leo thang xung đột, lộ trình trưởng thành, hoặc phong vị kết truyện.",
          "If a Story macro exists, every volume.roleLabel must map to one of: the main-line appeal, conflict escalation, the growth path, or the ending flavor."),
        pick(lang,
          "如果 Story macro 为 none，不要臆造精细主线阶段；应采用更保守的卷数与更高 uncertainty，说明缺少主线骨架带来的风险。",
          "Nếu Story macro là none, đừng bịa các giai đoạn tuyến chính tinh vi; hãy dùng số tập bảo thủ hơn và uncertainty cao hơn, nêu rõ rủi ro do thiếu bộ khung tuyến chính.",
          "If Story macro is none, do not invent fine-grained main-line phases — use a more conservative volume count and higher uncertainty, and state the risk from the missing main-line spine."),
        "",
        pick(lang, "【核心目标】", "【Mục tiêu cốt lõi】", "[Core goals]"),
        pick(lang,
          "1. strategy 必须优先服务连载追读动力，而不是一次性写死后半本。",
          "1. strategy phải ưu tiên phục vụ động lực đọc tiếp dài kỳ, không phải chốt chết nửa sau một lần.",
          "1. The strategy must serve sustained read-on momentum first, not lock down the back half in one shot."),
        pick(lang,
          "2. 分卷策略必须兼顾开书抓力、中段续航、后段升级空间与长期连载可调度性。",
          "2. Chiến lược phân tập phải cân bằng: lực hút lúc mở sách, sức bền đoạn giữa, không gian nâng cấp đoạn sau, và khả năng điều chỉnh khi ra chương dài kỳ.",
          "2. The strategy must balance opening pull, mid-run stamina, late-run escalation room, and long-run schedulability."),
        pick(lang,
          "3. hard 规划用于锁定前期最关键的承诺、卖点、推进秩序与节奏稳定性。",
          "3. Kế hoạch cứng dùng để chốt các cam kết, điểm hấp dẫn, trật tự đẩy truyện và sự ổn định nhịp quan trọng nhất ở đoạn đầu.",
          "3. Hard planning locks the most critical early promises, appeal, progression order, and pacing stability."),
        pick(lang,
          "4. soft 规划用于保留后续卷的弹性，方便根据连载反馈、篇幅变化、卖点强化和剧情自然增长进行调整。",
          "4. Kế hoạch mềm giữ độ co giãn cho các tập sau, để điều chỉnh theo phản hồi khi ra chương, thay đổi độ dài, tăng cường điểm hấp dẫn và sự phát triển tự nhiên của cốt truyện.",
          "4. Soft planning preserves flexibility for later volumes so they can adjust to reader feedback, length changes, sharpened appeal, and the story's natural growth."),
        "",
        pick(lang, "【规划原则】", "【Nguyên tắc lập kế hoạch】", "[Planning principles]"),
        pick(lang,
          "1. recommendedVolumeCount 不是均分剧情，而是按阶段承诺、卖点切换、局面升级和阶段性兑现来决定。",
          "1. recommendedVolumeCount không phải chia đều cốt truyện, mà quyết định theo cam kết giai đoạn, chuyển điểm hấp dẫn, leo thang cục diện và trả nợ theo giai đoạn.",
          "1. recommendedVolumeCount is not an even split of plot — decide it by phase promises, appeal shifts, situation escalation, and phased payoffs."),
        pick(lang,
          "2. hardPlannedVolumeCount 只覆盖真正需要提前锁定的前期卷数，不要机械求多。",
          "2. hardPlannedVolumeCount chỉ bao phủ số tập đầu thực sự cần chốt trước, đừng máy móc lấy nhiều.",
          "2. hardPlannedVolumeCount covers only the early volumes that genuinely need locking early — do not mechanically maximize it."),
        pick(lang,
          "3. 越靠前的卷，越需要明确控制；越靠后的卷，越应保留调整空间。",
          "3. Tập càng ở trước càng cần kiểm soát rõ ràng; tập càng ở sau càng nên chừa khoảng điều chỉnh.",
          "3. The earlier the volume, the more it needs explicit control; the later the volume, the more adjustment room it should keep."),
        pick(lang,
          "4. 分卷策略必须让前几卷具备清晰的抓手、承诺和递进，避免刚开书就陷入长线铺陈。",
          "4. Chiến lược phân tập phải để vài tập đầu có móc hút, cam kết và tăng tiến rõ ràng, tránh vừa mở sách đã sa vào dàn trải dài dòng.",
          "4. The strategy must give the first few volumes a clear hook, promise, and progression — avoid sinking into long setup right after the book opens."),
        pick(lang,
          "5. 不要让 soft 卷变成空白占位，它们仍应保留明确阶段职责，只是不预先写死具体细节。",
          "5. Đừng để tập mềm thành ô trống giữ chỗ — chúng vẫn phải giữ trách nhiệm giai đoạn rõ ràng, chỉ là không chốt trước chi tiết cụ thể.",
          "5. Do not let soft volumes become blank placeholders — they must still hold a clear phase responsibility, just without pre-locking specific details."),
        "",
        pick(lang, "【重点判断项】", "【Các điểm cần cân nhắc】", "[Key judgment points]"),
        pick(lang,
          "1. 这本书适合短卷数强推进，还是较多卷数分阶段展开，但决策必须尊重上下文给出的允许区间与固定卷数约束。",
          "1. Sách này hợp với ít tập đẩy mạnh, hay nhiều tập triển khai theo giai đoạn — nhưng quyết định phải tôn trọng khoảng cho phép và ràng buộc số tập cố định trong ngữ cảnh.",
          "1. Is this book better with few volumes and strong drive, or more volumes unfolding in phases — but the decision must respect the allowed range and fixed-count constraints in the context."),
        pick(lang,
          "2. 前几卷是否承担开书、立主卖点、第一阶段兑现、世界扩展、格局升级等关键任务，是否必须硬规划。",
          "2. Vài tập đầu có gánh các nhiệm vụ then chốt (mở sách, dựng điểm hấp dẫn chính, trả nợ giai đoạn một, mở rộng thế giới, nâng cấp cục diện) không, và có bắt buộc lập kế hoạch cứng không.",
          "2. Do the first few volumes carry key tasks (opening the book, establishing the core appeal, first-phase payoff, world expansion, scale escalation), and must they be hard-planned."),
        pick(lang,
          "3. 中后段是否存在较大弹性，适合保留软规划，以避免早期过度透支。",
          "3. Đoạn giữa-sau có độ co giãn lớn phù hợp giữ kế hoạch mềm không, để tránh vắt kiệt quá sớm.",
          "3. Does the mid-to-late run have enough flexibility to stay soft-planned, so it isn't over-spent early."),
        pick(lang,
          "4. 分卷数量是否与题材、主卖点密度、成长跨度、冲突层级和连载模式匹配。",
          "4. Số tập có khớp với đề tài, mật độ điểm hấp dẫn chính, biên độ trưởng thành, tầng xung đột và mô thức ra chương không.",
          "4. Does the volume count match the subject, the density of the core appeal, the growth span, the conflict tiers, and the serialization mode."),
        pick(lang,
          "5. 判断故事是否需要三幕式、阶段副本、地图/势力扩展、能力成长阶梯、关系阶段变化或长期反派层级。",
          "5. Xác định truyện có cần cấu trúc ba hồi, các chặng thử thách theo giai đoạn, mở rộng bản đồ/thế lực, thang trưởng thành năng lực, thay đổi quan hệ theo giai đoạn, hay tầng phản diện dài hạn không.",
          "5. Judge whether the story needs a three-act structure, phased trials, map/faction expansion, a capability-growth ladder, phased relationship change, or a long-term antagonist hierarchy."),
        pick(lang,
          "6. 每卷 roleLabel 是否能回扣 Story macro 的卖点、长期冲突、推进回路、成长路径或结尾风味；缺少 Story macro 时，必须把该不确定性写入 uncertainties。",
          "6. roleLabel của mỗi tập có nối lại được về điểm hấp dẫn, xung đột dài hạn, vòng đẩy truyện, lộ trình trưởng thành hoặc phong vị kết của Story macro không; khi thiếu Story macro, phải ghi sự bất định đó vào uncertainties.",
          "6. Can each volume's roleLabel tie back to the Story macro's appeal, long-term conflict, progression loop, growth path, or ending flavor; when Story macro is missing, write that uncertainty into uncertainties."),
        "",
        pick(lang, "【质量要求】", "【Yêu cầu chất lượng】", "[Quality requirements]"),
        pick(lang,
          "1. 整体策略必须体现阶段递进，不能只是‘前面 hard，后面 soft’的空泛分配。",
          "1. Chiến lược tổng thể phải thể hiện tăng tiến theo giai đoạn, không chỉ là phân bổ chung chung \"trước hard, sau soft\".",
          "1. The overall strategy must show phase-by-phase progression, not just a vague \"hard in front, soft in back\" split."),
        pick(lang,
          "2. 每个 volume 项都应体现该卷在整书中的阶段职责，而不是泛泛写成‘推进剧情’。",
          "2. Mỗi mục volume phải thể hiện trách nhiệm giai đoạn của tập đó trong cả sách, không viết chung chung là \"đẩy cốt truyện\".",
          "2. Every volume entry must express that volume's phase responsibility within the whole book, not generically \"advance the plot\"."),
        pick(lang,
          "3. hard 卷要更明确，soft 卷要保留方向但不写死细节。",
          "3. Tập hard phải rõ ràng hơn; tập soft giữ hướng nhưng không chốt chi tiết.",
          "3. Hard volumes must be more definite; soft volumes keep a direction but do not lock details."),
        pick(lang,
          "4. 不要脱离上下文臆造重大设定或额外主线。",
          "4. Không được bịa thiết lập lớn hay tuyến chính bổ sung ngoài ngữ cảnh.",
          "4. Do not invent major setting elements or extra main lines outside the context."),
        pick(lang,
          "5. 在信息不足时，也要给出保守但完整的策略。",
          "5. Khi thiếu thông tin, vẫn phải đưa ra chiến lược bảo thủ nhưng đầy đủ.",
          "5. When information is missing, still produce a conservative but complete strategy."),
        pick(lang,
          "6. 如果 chapter budget 很大，默认应通过增加卷数来保持每卷的阶段颗粒度，而不是把超长篇压成几卷巨无霸。",
          "6. Nếu chapter budget lớn, mặc định nên tăng số tập để giữ độ mịn giai đoạn của mỗi tập, thay vì dồn truyện siêu dài vào vài tập khổng lồ.",
          "6. If the chapter budget is large, default to more volumes to keep each volume's phase granularity, rather than packing a very long book into a few giant volumes."),
      ].join("\n")),
      new HumanMessage([
        pick(lang,
          "请基于以下上下文，输出整本书的分卷策略。",
          "Dựa trên ngữ cảnh dưới đây, hãy xuất chiến lược phân tập cho cả cuốn sách.",
          "Based on the context below, output the whole-book volume strategy."),
        "",
        pick(lang, "【输出要求】", "【Yêu cầu đầu ra】", "[Output requirements]"),
        pick(lang, "- 只输出严格 JSON", "- Chỉ xuất JSON nghiêm ngặt", "- Output strict JSON only"),
        fixedRecommendedVolumeCount == null
          ? pick(lang,
            `- recommendedVolumeCount 必须落在结构建议区间 ${decisionVolumeCountRange.min}-${decisionVolumeCountRange.max} 之间`,
            `- recommendedVolumeCount phải nằm trong khoảng đề xuất cấu trúc ${decisionVolumeCountRange.min}-${decisionVolumeCountRange.max}`,
            `- recommendedVolumeCount must fall within the structural suggestion range ${decisionVolumeCountRange.min}-${decisionVolumeCountRange.max}`)
          : pick(lang,
            `- recommendedVolumeCount 必须严格等于 ${fixedRecommendedVolumeCount}`,
            `- recommendedVolumeCount phải bằng đúng ${fixedRecommendedVolumeCount}`,
            `- recommendedVolumeCount must be exactly ${fixedRecommendedVolumeCount}`),
        pick(lang,
          "- volumes.length 必须等于 recommendedVolumeCount",
          "- volumes.length phải bằng recommendedVolumeCount",
          "- volumes.length must equal recommendedVolumeCount"),
        pick(lang,
          `- hardPlannedVolumeCount 必须落在 ${hardPlannedVolumeRange.min}-${hardPlannedVolumeRange.max} 之间`,
          `- hardPlannedVolumeCount phải nằm trong khoảng ${hardPlannedVolumeRange.min}-${hardPlannedVolumeRange.max}`,
          `- hardPlannedVolumeCount must fall within ${hardPlannedVolumeRange.min}-${hardPlannedVolumeRange.max}`),
        pick(lang,
          "- 前 hardPlannedVolumeCount 卷必须为 hard，后续卷必须为 soft",
          "- hardPlannedVolumeCount tập đầu phải là hard, các tập sau phải là soft",
          "- The first hardPlannedVolumeCount volumes must be hard; the rest must be soft"),
        pick(lang,
          "- 优先保证前期抓力、中期续航与后期可调度性",
          "- Ưu tiên bảo đảm lực hút đoạn đầu, sức bền đoạn giữa và khả năng điều chỉnh đoạn sau",
          "- Prioritize opening pull, mid-run stamina, and late-run schedulability"),
        "",
        pick(lang, "【规划上下文】", "【Ngữ cảnh lập kế hoạch】", "[Planning context]"),
        renderSelectedContextBlocks(context),
      ].join("\n")),
    ];
    },
  };
}

export const volumeStrategyCritiquePrompt: PromptAsset<
  VolumeStrategyCritiquePromptInput,
  ReturnType<typeof createVolumeStrategyCritiqueSchema>["_output"]
> = {
  id: "novel.volume.strategy.critique",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.volumeStrategyCritique,
    requiredGroups: ["book_contract", "strategy_context"],
    preferredGroups: ["macro_constraints", "existing_volume_window", "guidance"],
  },
  outputSchema: createVolumeStrategyCritiqueSchema(),
  render: (_input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是长篇连载小说分卷策略审查助手。",
        "Bạn là trợ lý rà soát chiến lược phân tập cho tiểu thuyết dài kỳ.",
        "You are a volume-strategy review assistant for long-form serialized fiction."),
      pick(lang,
        "你的任务不是重写分卷策略，而是识别当前策略中会影响长期连载稳定性的关键问题，并输出可供后续修正的结构化审查结果。",
        "Nhiệm vụ của bạn không phải viết lại chiến lược phân tập, mà nhận diện các vấn đề then chốt ảnh hưởng đến sự ổn định khi ra chương dài kỳ, và xuất kết quả rà soát có cấu trúc để chỉnh sửa sau.",
        "Your task is not to rewrite the volume strategy, but to identify the key problems in it that hurt long-run serialization stability, and output a structured review for later correction."),
      "",
      pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
      pick(lang,
        "只审查当前分卷策略是否存在：过早锁死、前后期规划失衡、回报同质、阶段升级断裂、卷数分配失真、软规划失去意义、不确定性声明不足等问题。",
        "Chỉ rà soát xem chiến lược phân tập hiện tại có các vấn đề: chốt cứng quá sớm, mất cân bằng kế hoạch đầu/sau, phần thưởng đồng nhất, đứt gãy leo thang giai đoạn, phân bổ số tập lệch, kế hoạch mềm mất ý nghĩa, thiếu khai báo bất định.",
        "Only review whether the current volume strategy has: locking down too early, imbalance between early/late planning, homogeneous payoffs, broken phase escalation, distorted volume-count allocation, meaningless soft planning, or insufficient uncertainty declarations."),
      pick(lang,
        "不要改写整套策略，不要输出新的完整分卷方案，不要输出 Markdown、解释、注释或额外文本。",
        "Không viết lại toàn bộ chiến lược, không xuất phương án phân tập hoàn chỉnh mới, không xuất Markdown, lời giải thích, chú thích hay văn bản thừa.",
        "Do not rewrite the whole strategy, do not output a new complete volume plan, and do not output Markdown, explanations, comments, or extra text."),
      pick(lang, "只输出严格 JSON。", "Chỉ xuất JSON nghiêm ngặt.", "Output strict JSON only."),
      "",
      pick(lang, "【输出要求】", "【Yêu cầu đầu ra】", "[Output requirements]"),
      pick(lang,
        "issues 中的每条问题都必须完整包含 targetRef、severity、title、detail 四个字段，不能缺漏、不能改名。",
        "Mỗi mục trong issues phải chứa đủ bốn field targetRef, severity, title, detail — không thiếu, không đổi tên.",
        "Every item in issues must fully contain targetRef, severity, title, detail — none missing, none renamed."),
      pick(lang,
        "severity 使用 low、medium、high 之一。",
        "severity dùng một trong low, medium, high.",
        "severity is one of low, medium, high."),
      pick(lang,
        "如果策略整体可接受，也可以输出空 issues，但不要为了凑问题而制造伪问题。",
        "Nếu chiến lược tổng thể chấp nhận được, có thể xuất issues rỗng — nhưng đừng bịa vấn đề giả cho đủ số.",
        "If the strategy is acceptable overall, an empty issues array is fine — but do not fabricate fake problems to fill it."),
      "",
      pick(lang, "【审查目标】", "【Mục tiêu rà soát】", "[Review goal]"),
      pick(lang,
        "重点判断当前分卷策略是否真正服务于长期连载，而不是表面上完成了 hard / soft 切分。",
        "Trọng tâm là đánh giá chiến lược phân tập có thực sự phục vụ việc ra chương dài kỳ không, chứ không phải chỉ hoàn thành bề mặt việc chia hard / soft.",
        "Focus on judging whether the volume strategy genuinely serves a long serialized run, not whether it superficially completed a hard/soft split."),
      pick(lang,
        "你的审查要关注结构风险，而不是措辞好不好看。",
        "Rà soát của bạn phải chú ý rủi ro cấu trúc, không phải câu chữ đẹp hay không.",
        "Your review must attend to structural risk, not to whether the wording is pretty."),
      "",
      pick(lang, "【重点检查项】", "【Các điểm kiểm tra chính】", "[Key checks]"),
      pick(lang,
        "1. 是否过早锁死后半本，导致 soft 规划名义存在、实质失效。",
        "1. Có chốt cứng nửa sau quá sớm khiến kế hoạch mềm chỉ tồn tại trên danh nghĩa, thực chất vô hiệu không.",
        "1. Is the back half locked down too early, so soft planning exists in name but is effectively void."),
      pick(lang,
        "2. hardPlannedVolumeCount 是否过多或过少，导致前期不稳或后期弹性不足。",
        "2. hardPlannedVolumeCount có quá nhiều hoặc quá ít, khiến đoạn đầu bất ổn hoặc đoạn sau thiếu co giãn không.",
        "2. Is hardPlannedVolumeCount too high or too low, making the early run unstable or the late run inflexible."),
      pick(lang,
        "3. recommendedVolumeCount 是否与题材体量、卖点密度、成长跨度和冲突层级明显失配。",
        "3. recommendedVolumeCount có lệch rõ so với dung lượng đề tài, mật độ điểm hấp dẫn, biên độ trưởng thành và tầng xung đột không.",
        "3. Is recommendedVolumeCount clearly mismatched with the subject's scale, appeal density, growth span, and conflict tiers."),
      pick(lang,
        "4. 前几卷是否承担了清晰的开书抓手、主卖点建立和阶段承诺推进；若没有，应视为高优先级问题。",
        "4. Vài tập đầu có gánh được móc hút mở sách rõ ràng, dựng điểm hấp dẫn chính và đẩy cam kết giai đoạn không; nếu không, coi là vấn đề ưu tiên cao.",
        "4. Do the first few volumes carry a clear opening hook, establish the core appeal, and advance phase promises; if not, treat it as high priority."),
      pick(lang,
        "5. 各卷阶段职责是否过于同质，例如连续多卷都只是“继续推进”“继续升级”。",
        "5. Trách nhiệm giai đoạn của các tập có quá đồng nhất không, ví dụ nhiều tập liên tiếp chỉ là \"tiếp tục đẩy\" \"tiếp tục nâng cấp\".",
        "5. Are the volumes' phase responsibilities too homogeneous, e.g. several consecutive volumes are just \"keep advancing\" / \"keep escalating\"."),
      pick(lang,
        "6. 分卷之间是否存在升级断裂、阶段目标断层、回报密度失衡或卷间功能重复。",
        "6. Giữa các tập có đứt gãy leo thang, đứt tầng mục tiêu giai đoạn, mất cân bằng mật độ phần thưởng, hay trùng lặp chức năng không.",
        "6. Between volumes, is there broken escalation, a gap in phase goals, imbalanced payoff density, or repeated function."),
      pick(lang,
        "7. soft 卷是否只有空泛方向，没有保留真正可调度的弹性。",
        "7. Tập soft có chỉ có hướng chung chung, không giữ được độ co giãn thực sự điều chỉnh được không.",
        "7. Do soft volumes have only a vague direction, without keeping genuinely schedulable flexibility."),
      pick(lang,
        "8. 策略中是否缺少对不确定性的承认，例如把尚未稳定的中后期发展写得过死。",
        "8. Chiến lược có thiếu thừa nhận sự bất định không, ví dụ viết quá chết phần phát triển giữa-sau chưa ổn định.",
        "8. Does the strategy fail to acknowledge uncertainty, e.g. writing the not-yet-stable mid-to-late development too rigidly."),
      "",
      pick(lang, "【targetRef 规则】", "【Quy tắc targetRef】", "[targetRef rules]"),
      pick(lang,
        "targetRef 必须尽量精确指向问题位置。可以指向整体策略，例如：strategy / recommendedVolumeCount / hardPlannedVolumeCount。也可以指向具体卷，例如：volumes[0] / volumes[3] / volumes[5].planningMode。不要使用模糊指代，例如“前面部分”“后面那里”。",
        "targetRef phải chỉ vào vị trí vấn đề càng chính xác càng tốt. Có thể chỉ vào chiến lược tổng thể, ví dụ: strategy / recommendedVolumeCount / hardPlannedVolumeCount. Cũng có thể chỉ vào tập cụ thể, ví dụ: volumes[0] / volumes[3] / volumes[5].planningMode. Không dùng chỉ định mơ hồ như \"phần trước\" \"chỗ sau kia\".",
        "targetRef must point at the problem location as precisely as possible. It may point at the overall strategy, e.g. strategy / recommendedVolumeCount / hardPlannedVolumeCount. It may point at a specific volume, e.g. volumes[0] / volumes[3] / volumes[5].planningMode. Do not use vague references like \"the front part\" or \"over in the back\"."),
      "",
      pick(lang, "【detail 要求】", "【Yêu cầu detail】", "[detail requirements]"),
      pick(lang,
        "detail 必须说明：问题是什么，为什么这是结构风险，它会造成什么连载后果。不要只写“节奏有问题”“规划偏死”“需要优化”这类空泛判断。要尽量指出问题的结构性质，例如：",
        "detail phải nói rõ: vấn đề là gì, vì sao đó là rủi ro cấu trúc, nó gây hệ quả gì khi ra chương dài kỳ. Đừng chỉ viết \"nhịp có vấn đề\" \"kế hoạch hơi chết\" \"cần tối ưu\". Hãy chỉ ra bản chất cấu trúc của vấn đề, ví dụ:",
        "detail must state: what the problem is, why it is a structural risk, and what serialization consequence it causes. Do not just write \"pacing issue\", \"planning is rigid\", \"needs optimization\". Point at the structural nature of the problem, e.g.:"),
      pick(lang,
        "- 前期承诺不足，导致读者难以建立追读理由",
        "- Cam kết đoạn đầu không đủ, khiến người đọc khó có lý do đọc tiếp",
        "- Early promises are insufficient, so the reader struggles to form a reason to keep reading"),
      pick(lang,
        "- 中后段被过早写死，削弱连载中途调整空间",
        "- Đoạn giữa-sau bị viết chết quá sớm, làm yếu không gian điều chỉnh giữa chừng khi ra chương",
        "- The mid-to-late run is fixed too early, weakening room to adjust mid-serialization"),
      pick(lang,
        "- 相邻卷阶段职责重复，导致回报体验同质化",
        "- Trách nhiệm giai đoạn của các tập liền kề trùng nhau, khiến trải nghiệm phần thưởng bị đồng nhất",
        "- Adjacent volumes' phase responsibilities repeat, homogenizing the payoff experience"),
      "",
      pick(lang, "【质量要求】", "【Yêu cầu chất lượng】", "[Quality requirements]"),
      pick(lang,
        "1. 只抓真正影响结构的关键问题，避免细枝末节泛滥。",
        "1. Chỉ bắt các vấn đề then chốt thực sự ảnh hưởng cấu trúc, tránh sa vào tiểu tiết.",
        "1. Catch only the key problems that genuinely affect structure — avoid a flood of trivia."),
      pick(lang,
        "2. 同类问题不要重复拆成多条近义 issue。",
        "2. Vấn đề cùng loại đừng tách thành nhiều issue gần nghĩa.",
        "2. Do not split one kind of problem into several near-synonymous issues."),
      pick(lang,
        "3. 如果一个问题会影响整套策略，应优先以更高层 targetRef 指出，而不是碎片化报错。",
        "3. Nếu một vấn đề ảnh hưởng cả chiến lược, hãy chỉ ra bằng targetRef ở cấp cao hơn, không báo lỗi vụn vặt.",
        "3. If one problem affects the whole strategy, point at it with a higher-level targetRef rather than reporting fragmented errors."),
      pick(lang,
        "4. 审查结论要有长期连载视角，优先考虑抓力、续航、升级、兑现与可调度性。",
        "4. Kết luận rà soát phải có góc nhìn ra chương dài kỳ, ưu tiên: lực hút, sức bền, leo thang, trả nợ và khả năng điều chỉnh.",
        "4. The review conclusion must take a long-serialization view — prioritize pull, stamina, escalation, payoff, and schedulability."),
      pick(lang,
        "5. 在信息不足时可以保守，但不要放过明显的结构隐患。",
        "5. Khi thiếu thông tin có thể bảo thủ, nhưng đừng bỏ qua các nguy cơ cấu trúc rõ ràng.",
        "5. When information is missing you may be conservative, but do not let obvious structural hazards slip by."),
    ].join("\n")),
    new HumanMessage([
      pick(lang,
        "请基于以下上下文，审查当前分卷策略的结构风险，并输出问题列表。",
        "Dựa trên ngữ cảnh dưới đây, hãy rà soát rủi ro cấu trúc của chiến lược phân tập hiện tại và xuất danh sách vấn đề.",
        "Based on the context below, review the current volume strategy's structural risk and output the problem list."),
      "",
      pick(lang, "【输出要求】", "【Yêu cầu đầu ra】", "[Output requirements]"),
      pick(lang, "- 只输出严格 JSON", "- Chỉ xuất JSON nghiêm ngặt", "- Output strict JSON only"),
      pick(lang,
        "- 每条 issue 必须包含 targetRef、severity、title、detail",
        "- Mỗi issue phải chứa targetRef, severity, title, detail",
        "- Each issue must contain targetRef, severity, title, detail"),
      pick(lang,
        "- 只指出真正影响分卷策略稳定性的关键问题",
        "- Chỉ nêu các vấn đề then chốt thực sự ảnh hưởng sự ổn định của chiến lược phân tập",
        "- Only raise key problems that genuinely affect the volume strategy's stability"),
      pick(lang, "- 不重写策略，只做审查", "- Không viết lại chiến lược, chỉ rà soát", "- Do not rewrite the strategy, only review"),
      "",
      pick(lang, "【待审查的分卷策略上下文】", "【Ngữ cảnh chiến lược phân tập cần rà soát】", "[Volume-strategy context under review]"),
      renderSelectedContextBlocks(context),
    ].join("\n")),
  ];
  },
};

export {
  buildVolumeStrategyContextBlocks,
  buildVolumeStrategyCritiqueContextBlocks,
};
