import {
  deriveTwistDefaultsFromCadence,
  type StoryModeConflictCeiling,
  type StoryModeEndingHookStyle,
  type StoryModeForeshadowHold,
  type StoryModeProfile,
  type StoryModeTwistCadence,
} from "@ai-novel/shared/types/storyMode";

export interface StoryModeSeedNode {
  id: string;
  name: string;
  description: string;
  template: string;
  profile: StoryModeProfile;
  children: Array<{
    id: string;
    name: string;
    description: string;
    template: string;
    profile: StoryModeProfile;
  }>;
}

/** Mặc định 3 field engine theo trần xung đột khi seed không nêu rõ. */
function engineDefaultsFor(ceiling: StoryModeConflictCeiling): {
  twistCadence: StoryModeTwistCadence;
  foreshadowHold: StoryModeForeshadowHold;
  endingHookStyle: StoryModeEndingHookStyle;
} {
  if (ceiling === "low") {
    return { twistCadence: "rare", foreshadowHold: "short", endingHookStyle: "emotional_pull" };
  }
  if (ceiling === "high") {
    return { twistCadence: "periodic", foreshadowHold: "arc", endingHookStyle: "escalation" };
  }
  return { twistCadence: "periodic", foreshadowHold: "arc", endingHookStyle: "cliffhanger" };
}

function buildProfile(input: Partial<StoryModeProfile> & Pick<StoryModeProfile, "coreDrive" | "readerReward">): StoryModeProfile {
  const conflictCeiling = input.conflictCeiling ?? "medium";
  const engine = engineDefaultsFor(conflictCeiling);
  const resolvedTwistCadence = input.twistCadence ?? engine.twistCadence;
  const twist = deriveTwistDefaultsFromCadence(resolvedTwistCadence);
  return {
    coreDrive: input.coreDrive,
    readerReward: input.readerReward,
    progressionUnits: input.progressionUnits ?? ["Đẩy quan hệ tiến lên", "Trả một mục tiêu giai đoạn"],
    allowedConflictForms: input.allowedConflictForms ?? ["Xung đột cường độ vừa và thấp, ăn khớp với động lực chính"],
    forbiddenConflictForms: input.forbiddenConflictForms ?? ["Xung đột cẩu huyết cao áp không liên quan"],
    conflictCeiling,
    resolutionStyle: input.resolutionStyle ?? "Ưu tiên giải quyết vấn đề theo cách hợp với mode này, không cố đẩy mâu thuẫn leo thang.",
    chapterUnit: input.chapterUnit ?? "Mỗi chương cần có một diễn biến chính rõ ràng.",
    volumeReward: input.volumeReward ?? "Cuối tập trả một kết quả giai đoạn, để người đọc thấy tuyến này đáng theo tiếp.",
    mandatorySignals: input.mandatorySignals ?? ["Động lực chính xuất hiện liên tục", "Kỳ vọng của người đọc được xác nhận lặp lại"],
    antiSignals: input.antiSignals ?? ["Lệch khỏi động lực chính trong thời gian dài", "Cường độ xung đột vượt tầm kiểm soát"],
    momentumSource: input.momentumSource ?? "goal_pursuit",
    perChapterChangeMenu: input.perChapterChangeMenu ?? [
      "Đẩy một mục tiêu giai đoạn rõ ràng",
      "Quan hệ hoặc lập trường thay đổi thấy được",
      "Có thông tin mới hoặc sửa một phán đoán sai",
      "Mức rủi ro hoặc cái giá phải trả tăng lên",
    ],
    twistCadence: resolvedTwistCadence,
    twistIntensity: input.twistIntensity ?? twist.twistIntensity,
    twistFairness: input.twistFairness ?? twist.twistFairness,
    twistScope: input.twistScope ?? twist.twistScope,
    allowedTwistMechanisms: input.allowedTwistMechanisms ?? twist.allowedTwistMechanisms,
    foreshadowHold: input.foreshadowHold ?? engine.foreshadowHold,
    endingHookStyle: input.endingHookStyle ?? engine.endingHookStyle,
  };
}

export const BUILT_IN_STORY_MODE_SEEDS: StoryModeSeedNode[] = [
  {
    id: "story_mode_battle_root",
    name: "Chiến đấu nhiệt huyết",
    description: "Lấy chiến đấu, đối thủ, thắng thua và sự tăng tiến sức mạnh làm động lực đọc tiếp liên tục.",
    template: "Làm nổi bật mục tiêu trận đấu, biến hoá chiêu thức, đối thủ nâng cấp và thắng thua theo từng giai đoạn.",
    profile: buildProfile({
      coreDrive: "Thúc đẩy câu chuyện bằng chuỗi trận đấu liên tiếp, đối thủ ngày càng mạnh và năng lực mới được thể hiện đúng lúc.",
      readerReward: "Người đọc liên tục nhận được cao trào giao chiến, lật ngược thắng thua và cảm giác nhân vật chính mạnh lên.",
      progressionUnits: ["Mục tiêu trận đấu", "Phô diễn năng lực", "Đối thủ nâng cấp", "Trả kết quả thắng thua"],
      allowedConflictForms: ["Đối đầu trực diện", "Khắc chế năng lực", "Đánh theo đội", "Thử thách thi đấu"],
      forbiddenConflictForms: ["Đời thường dài dòng không liên quan", "Đánh nhau xong không có kết quả", "Chỉ bị đánh mà không trưởng thành"],
      conflictCeiling: "high",
      resolutionStyle: "Dùng chiến thuật, năng lực, ý chí và phối hợp đồng đội để chốt kết quả trận đấu.",
      chapterUnit: "Mỗi chương đẩy một trận đấu, một buổi tập luyện hoặc một thay đổi trong quan hệ với đối thủ.",
      volumeReward: "Cuối tập hoàn thành một chiến thắng then chốt, một cú đột phá sức mạnh hoặc một lần cường địch nâng cấp.",
      mandatorySignals: ["Mục tiêu trận đấu", "Chiêu thức hoặc năng lực", "Kết quả thắng thua"],
      antiSignals: ["Trận đấu lê thê", "Thắng thua nhờ may rủi", "Sức mạnh tăng mà không trả giá"],
    }),
    children: [
      { id: "story_mode_tournament", name: "Đại hội võ đạo thiên hạ đệ nhất", description: "Đẩy truyện liên tục qua thi đấu, loại trực tiếp và những trận so tài với cường địch.", template: "Nhấn vào lịch thi đấu, đặc điểm từng đối thủ, biến hoá chiến thuật và những trận thắng thua then chốt.", profile: buildProfile({ coreDrive: "Đẩy sự trưởng thành của nhân vật chính qua từng vòng đấu và những trận so tài với cường địch.", readerReward: "Người đọc liên tục có cảm giác mong đợi trận đấu, những cú lật ngược bất ngờ và niềm vui thăng hạng.", progressionUnits: ["Đăng ký, vào giải", "Đấu vòng bảng", "Cường địch thăng hạng", "Trả kết quả trận chung kết"], allowedConflictForms: ["So tài thi đấu", "Giới hạn luật lệ", "Thách đấu tử địch"], forbiddenConflictForms: ["Bỏ qua kết quả trận đấu", "Đối thủ không có nét riêng"], conflictCeiling: "high", resolutionStyle: "Dùng sự chuẩn bị, chiến thuật và khả năng ứng biến tại chỗ để thắng trận.", chapterUnit: "Mỗi chương đẩy một trận đấu hoặc một đoạn chuẩn bị trước trận.", volumeReward: "Cuối tập hoàn thành việc vượt qua giải đấu then chốt hoặc giành ngôi vô địch.", mandatorySignals: ["Luật thi đấu", "Nét riêng của đối thủ", "Áp lực thăng hạng"], antiSignals: ["Trận đấu không có kịch tính", "Thắng thua do trọng tài cưỡng ép quyết định"] }) },
      { id: "story_mode_training_arc", name: "Tu luyện khổ tập", description: "Thúc đẩy sự trưởng thành bằng quá trình tập luyện, thử thách và vượt qua giới hạn năng lực.", template: "Mỗi lần tập luyện phải có mục tiêu, phương pháp, cái giá và kết quả cụ thể.", profile: buildProfile({ coreDrive: "Đưa nhân vật chính từng bước vươn lên bằng tập luyện, thử thách và những lần đột phá năng lực.", readerReward: "Người đọc được thấy nỗ lực tích lũy thành sức mạnh và những khoảnh khắc vượt qua giới hạn.", progressionUnits: ["Đặt mục tiêu", "Tập luyện và thử thách", "Vượt qua điểm nghẽn", "Kiểm chứng thành quả"], allowedConflictForms: ["Giới hạn năng lực", "Bài thử sức", "Điểm nghẽn trong tu luyện"], forbiddenConflictForms: ["Tự nhiên mạnh lên mà không trải qua quá trình", "Tập luyện không liên quan đến tuyến truyện chính"], conflictCeiling: "high", resolutionStyle: "Giúp nhân vật đột phá bằng phương pháp đúng, sự kiên trì và cái giá tương xứng.", chapterUnit: "Mỗi chương có một lần tập luyện, vượt thử thách hoặc kiểm chứng năng lực mới.", volumeReward: "Cuối tập, năng lực của nhân vật chính tăng lên một bậc rõ rệt.", mandatorySignals: ["Phương pháp tập luyện", "Cái giá của sức mạnh", "Kiểm chứng năng lực mới"], antiSignals: ["Tăng sức mạnh vô cớ", "Tập luyện xong nhưng nhân vật không thay đổi"] }) },
    ],
  },
  {
    id: "story_mode_quest_root",
    name: "Nhiệm vụ phiêu lưu",
    description: "Lấy nhiệm vụ, hành trình, thám hiểm và việc hoàn thành mục tiêu làm động lực chính của câu chuyện.",
    template: "Mỗi nhiệm vụ phải mang lại địa điểm mới, thông tin mới, đồng đội mới hoặc cái giá mới.",
    profile: buildProfile({ coreDrive: "Đưa câu chuyện tới một thế giới lớn hơn qua chuỗi nhiệm vụ và mục tiêu hành trình nối tiếp.", readerReward: "Người đọc liên tục có cảm giác thoả mãn khi khám phá điều chưa biết, hoàn thành mục tiêu và mở ra bản đồ mới.", progressionUnits: ["Nhận nhiệm vụ", "Thám hiểm địa điểm", "Vượt qua trở ngại", "Nhận phần thưởng nhiệm vụ"], allowedConflictForms: ["Trở ngại nhiệm vụ", "Hiểm nguy dọc đường", "Giới hạn tài nguyên", "Câu đố chưa biết"], forbiddenConflictForms: ["Nhiệm vụ không có mục tiêu", "Thám hiểm không phát hiện được gì", "Dừng quá lâu ở cùng một chỗ"], conflictCeiling: "medium", resolutionStyle: "Hoàn thành nhiệm vụ bằng quan sát, chuẩn bị, phối hợp và hành động.", chapterUnit: "Mỗi chương đẩy một mắt xích nhiệm vụ hoặc một phát hiện khi thám hiểm.", volumeReward: "Cuối tập hoàn thành một nhiệm vụ lớn và mở ra mục tiêu hành trình mới.", mandatorySignals: ["Nhiệm vụ rõ ràng", "Phát hiện khi thám hiểm", "Phần thưởng nhiệm vụ"], antiSignals: ["Mục tiêu thay đổi liên tục", "Kết quả nhiệm vụ không tác động gì"] }),
    children: [
      { id: "story_mode_dungeon", name: "Phó bản mê cung", description: "Tạo thử thách liên tục qua phó bản, mê cung, màn chơi và cạm bẫy.", template: "Nhấn vào luật của màn chơi, tiêu hao tài nguyên, phối hợp đội và phần thưởng thông quan.", profile: buildProfile({ coreDrive: "Đẩy chuyện sinh tồn, giải đố và trưởng thành qua từng phó bản và màn chơi.", readerReward: "Người đọc liên tục có cảm giác thoả mãn khi thông quan, thu thập phần thưởng và giải mã cơ chế.", progressionUnits: ["Vào phó bản", "Giải mã cơ chế", "Hạ gục kẻ giữ cửa", "Nhận thưởng thông quan"], allowedConflictForms: ["Thử thách màn chơi", "Câu đố cạm bẫy", "Quản lý tài nguyên", "Trùm phó bản"], forbiddenConflictForms: ["Luật phó bản không rõ", "Thông quan nhờ may mắn", "Phần thưởng không có giá trị"], conflictCeiling: "high", resolutionStyle: "Thông quan bằng cách hiểu luật, phân công đội hình và bố trí tài nguyên.", chapterUnit: "Mỗi chương đẩy một màn chơi, một câu đố hoặc một điểm giao chiến.", volumeReward: "Cuối tập thông quan phó bản và nhận phần thưởng làm thay đổi mạch truyện sau này.", mandatorySignals: ["Mục tiêu màn chơi", "Manh mối cơ chế", "Phần thưởng thông quan"], antiSignals: ["Phó bản lặp lại", "Luật thay đổi tuỳ tiện"] }) },
      { id: "story_mode_hero_journey", name: "Hành trình anh hùng", description: "Nhân vật rời khỏi môi trường quen thuộc, trưởng thành trên đường đi và hoàn thành sứ mệnh.", template: "Dùng các cột mốc hành trình để đẩy sự trưởng thành nhân vật, quan hệ đồng hành và sứ mệnh nâng cấp.", profile: buildProfile({ coreDrive: "Hoàn thành sự trưởng thành anh hùng của nhân vật chính qua các chặng rời đi, thử luyện, đồng đội và trở về.", readerReward: "Người đọc thấy nhân vật thay đổi từ một người bình thường thành người gánh vác sứ mệnh.", progressionUnits: ["Rời khỏi đời thường", "Gặp đồng đội", "Trải qua thử luyện", "Gánh vác sứ mệnh"], allowedConflictForms: ["Thử luyện dọc đường", "Lựa chọn giá trị", "Bất đồng với đồng đội", "Áp lực sứ mệnh"], forbiddenConflictForms: ["Hành trình không có thay đổi", "Nhân vật chính mãi không đưa ra lựa chọn"], conflictCeiling: "high", resolutionStyle: "Hoàn thành sự trưởng thành qua trải nghiệm, lựa chọn và gánh vác trách nhiệm.", chapterUnit: "Mỗi chương đẩy một cột mốc hành trình hoặc một lựa chọn của nhân vật.", volumeReward: "Cuối tập cho nhân vật chính hoàn thành một bước nhảy về danh phận, năng lực hoặc sứ mệnh.", mandatorySignals: ["Thay đổi dọc đường", "Quan hệ đồng đội", "Sứ mệnh nâng cấp"], antiSignals: ["Địa điểm chỉ là thay vỏ", "Trưởng thành không có khác biệt trước sau"] }) },
    ],
  },
  {
    id: "story_mode_system_root",
    name: "Hệ thống dưỡng thành",
    description: "Đẩy truyện liên tục bằng nhiệm vụ, kỹ năng, phần thưởng và sự trưởng thành theo luật hệ thống.",
    template: "Luật hệ thống phải rõ ràng, phần thưởng phải phục vụ tuyến chính, không thay nhân vật chính đưa ra lựa chọn.",
    profile: buildProfile({ coreDrive: "Giữ nhịp truyện bằng các nhiệm vụ, kỹ năng mới và phần thưởng cụ thể từ hệ thống.", readerReward: "Người đọc được thấy nhiệm vụ hoàn thành, chỉ số tăng và năng lực mới được mở khóa.", progressionUnits: ["Nhận nhiệm vụ", "Hoàn thành mục tiêu", "Nhận phần thưởng", "Mở khóa năng lực"], allowedConflictForms: ["Áp lực từ nhiệm vụ", "Giới hạn của luật hệ thống", "Lựa chọn phần thưởng", "Cái giá phải trả"], forbiddenConflictForms: ["Hệ thống làm thay mọi việc", "Chỉ số không có tác dụng", "Luật hệ thống thay đổi tùy tiện"], conflictCeiling: "high", resolutionStyle: "Để nhân vật chính hiểu rõ luật hệ thống rồi tự mình hoàn thành mục tiêu.", chapterUnit: "Mỗi chương giải quyết một nhiệm vụ, mở một kỹ năng hoặc nhận một phần thưởng đáng kể.", volumeReward: "Cuối tập, nhân vật hoàn thành mục tiêu lớn của giai đoạn và tiếp cận một tầng luật cao hơn.", mandatorySignals: ["Mục tiêu nhiệm vụ", "Phần thưởng cụ thể", "Năng lực thay đổi"], antiSignals: ["Không có nhiệm vụ mà nhân vật vẫn tự nhiên mạnh lên", "Hệ thống tước mất quyền chủ động của nhân vật chính"] }),
    children: [
      { id: "story_mode_leveling", name: "Lên cấp đánh quái", description: "Mạnh lên liên tục qua chiến đấu, kinh nghiệm, trang bị và đột phá cấp bậc.", template: "Mỗi lần lên cấp phải gắn với lựa chọn khi giao chiến, thay đổi năng lực và thử thách mới.", profile: buildProfile({ coreDrive: "Tích luỹ kinh nghiệm, trang bị và cấp bậc qua chiến đấu, từng bước thách thức đối thủ mạnh hơn.", readerReward: "Người đọc liên tục thoả mãn khi lên cấp, nhặt đồ rơi và thách thức vượt cấp.", progressionUnits: ["Thách thức kẻ địch", "Nhận kinh nghiệm", "Lên cấp, đổi trang bị", "Thách thức độ khó cao hơn"], allowedConflictForms: ["Chênh lệch cấp bậc", "Giới hạn trang bị", "Cạnh tranh tài nguyên", "Thách thức vượt cấp"], forbiddenConflictForms: ["Lên cấp không qua quá trình", "Trang bị chỉ nêu tên mà không có tác dụng"], conflictCeiling: "high", resolutionStyle: "Phá vỡ giới hạn cấp bậc bằng chuẩn bị, chiến đấu và phân bổ tài nguyên.", chapterUnit: "Mỗi chương đẩy một lần trưởng thành qua chiến đấu hoặc một lựa chọn trang bị.", volumeReward: "Cuối tập hoàn thành một bước nhảy cấp bậc và bước vào bản đồ hoặc độ khó mới.", mandatorySignals: ["Phản hồi trưởng thành", "Tác dụng của trang bị", "Thử thách mới"], antiSignals: ["Chồng chất chỉ số", "Mạnh yếu của kẻ địch mất đi sự khác biệt"] }) },
      { id: "story_mode_skill_tree", name: "Dưỡng thành cây kỹ năng", description: "Định hình nhân vật chính qua lựa chọn kỹ năng, phối hợp lưu phái và lộ trình chuyên sâu.", template: "Lựa chọn kỹ năng phải có đánh đổi, thay đổi lưu phái phải ảnh hưởng tới chiến đấu và cốt truyện.", profile: buildProfile({ coreDrive: "Xây dựng một cách trưởng thành riêng biệt qua lựa chọn kỹ năng và đánh đổi lộ trình.", readerReward: "Người đọc liên tục mong đợi kỹ năng mới, các bộ combo và bản dựng thành hình.", progressionUnits: ["Nhận kỹ năng", "Chọn lộ trình", "Kiểm chứng combo", "Lưu phái thành hình"], allowedConflictForms: ["Khắc chế kỹ năng", "Đánh đổi tài nguyên", "Thử sai khi dựng build"], forbiddenConflictForms: ["Kỹ năng không có khác biệt", "Mọi vấn đề chỉ một kỹ năng giải quyết hết"], conflictCeiling: "high", resolutionStyle: "Phá cục bằng cách hiểu giới hạn năng lực, phối hợp kỹ năng và chấp nhận đánh đổi.", chapterUnit: "Mỗi chương đẩy một lần lựa chọn, phối hợp hoặc kiểm chứng kỹ năng.", volumeReward: "Cuối tập hoàn thiện một lưu phái năng lực có thể nhận diện được.", mandatorySignals: ["Đánh đổi khi lựa chọn", "Phối hợp kỹ năng", "Giới hạn năng lực"], antiSignals: ["Không trả giá mà muốn ôm hết", "Kỹ năng chỉ để trang trí"] }) },
    ],
  },
  {
    id: "story_mode_revenge_root",
    name: "Báo thù lật ngược",
    description: "Đẩy truyện bằng phản bội, mất mát, mục tiêu báo thù và sự phản kích từng bước.",
    template: "Mỗi bước báo thù phải có mục tiêu, cái giá và kết quả cụ thể; mức độ đáp trả cần tăng dần.",
    profile: buildProfile({ coreDrive: "Hoàn thành mục tiêu báo thù bằng điều tra, tích lũy sức mạnh và từng bước phản công.", readerReward: "Người đọc được chứng kiến sự thật hé lộ, kẻ thù phải trả giá và nhân vật chính dần lật ngược thế cờ.", progressionUnits: ["Xác định kẻ thù", "Thu thập chứng cứ", "Phản công từng bước", "Thanh toán món nợ báo thù"], allowedConflictForms: ["Bị chèn ép vì thân phận", "Điều tra âm mưu", "Tranh giành nguồn lực", "Đối đầu công khai"], forbiddenConflictForms: ["Mục tiêu báo thù mơ hồ", "Kẻ thù nhiều lần thoát nạn mà không chịu hậu quả", "Nhân vật chính chỉ bị động chịu đựng"], conflictCeiling: "high", resolutionStyle: "Mỗi lần phản công đều dựa trên sự chuẩn bị, chứng cứ, sức mạnh và một lựa chọn then chốt.", chapterUnit: "Mỗi chương có một bước điều tra, một màn phản công hoặc một lần kẻ thù phải trả giá.", volumeReward: "Cuối tập, nhân vật chính hoàn thành một chặng báo thù và phát hiện mục tiêu lớn hơn phía sau.", mandatorySignals: ["Mục tiêu thù hận", "Chuẩn bị phản công", "Kẻ thù chịu hậu quả"], antiSignals: ["Báo thù không tiến triển", "Kẻ thù hành xử ngu ngốc vô lý", "Nỗi đau không bao giờ được giải quyết"] }),
    children: [],
  },
  {
    id: "story_mode_romcom_root",
    name: "Ngôn tình hài hước",
    description: "Lấy tương tác yêu đương, hiểu lầm, tình huống hài đời thường và quan hệ ấm dần làm cốt lõi.",
    template: "Tiếng cười phải phục vụ cho thay đổi quan hệ, hiểu lầm phải đẩy hai người lại gần chứ không kéo dài vô hạn.",
    profile: buildProfile({ coreDrive: "Giữ người đọc muốn đọc tiếp bằng những tương tác đời thường, hiểu lầm đáng yêu và một mối quan hệ dần ấm lên.", readerReward: "Người đọc được tận hưởng tiếng cười, sự rung động, những khoảnh khắc ngượng ngùng và các bước tiến tình cảm.", progressionUnits: ["Tình cờ gặp gỡ", "Hiểu lầm nảy sinh", "Khoảng cách được rút ngắn", "Xác nhận tình cảm"], allowedConflictForms: ["Tính cách trái ngược", "Hiểu lầm nhẹ", "Cạnh tranh tình cảm", "Những tình huống ngượng ngùng"], forbiddenConflictForms: ["Ngược đãi ác ý", "Hiểu lầm kéo dài mà không giải thích", "Mảng miếng hài không liên quan đến nhân vật"], conflictCeiling: "medium", resolutionStyle: "Để mối quan hệ tiến triển tự nhiên qua tương tác, sự thẳng thắn và những hành động bất ngờ.", chapterUnit: "Mỗi chương có một tình huống hài, một tương tác đáng nhớ hoặc một thay đổi trong quan hệ.", volumeReward: "Cuối tập, hai nhân vật xác nhận tình cảm hoặc bước vào một thế cạnh tranh tình yêu mới.", mandatorySignals: ["Tiếng cười xuất phát từ tương tác", "Cảm xúc thay đổi", "Quan hệ có bước tiến"], antiSignals: ["Chỉ có trò đùa mà không phát triển quan hệ", "Nhân vật hành xử ngớ ngẩn vô lý"], momentumSource: "relationship_emotion", perChapterChangeMenu: ["Khoảng cách giữa hai người gần thêm hoặc xa ra một bước", "Một rung động hoặc cơn ghen được bộc lộ", "Một hiểu lầm nảy sinh hoặc được giải thích", "Một tín hiệu tình cảm mới hoặc tình địch xuất hiện", "Nhân vật để lộ một điểm yếu thật lòng"], twistCadence: "rare", foreshadowHold: "short", endingHookStyle: "emotional_pull" }),
    children: [],
  },
  {
    id: "story_mode_adult_relationship_root",
    name: "Quan hệ người trưởng thành",
    description: "Đẩy truyện bằng quan hệ thân mật, ham muốn, ranh giới và lựa chọn thực tế của người trưởng thành.",
    template: "Tác giả tự quyết cường độ thể hiện thân mật, và giữ nhất quán ý muốn nhân vật, ranh giới và hậu quả của quan hệ.",
    profile: buildProfile({ coreDrive: "Để nhân vật thay đổi qua sức hút, ham muốn, ranh giới và những lựa chọn thực tế trong một mối quan hệ trưởng thành.", readerReward: "Người đọc cảm nhận được sự thân mật chân thực, phản ứng cảm xúc và những thay đổi trong quan hệ.", progressionUnits: ["Hình thành sức hút", "Xác định ranh giới", "Sự thân mật thay đổi", "Lựa chọn tương lai"], allowedConflictForms: ["Khác biệt về giá trị sống", "Ranh giới thân mật", "Áp lực thực tế", "Cam kết trong quan hệ"], forbiddenConflictForms: ["Phớt lờ mong muốn của nhân vật", "Cảnh thân mật không phục vụ câu chuyện", "Chỉ dùng miêu tả nhục cảm để kéo dài truyện"], conflictCeiling: "medium", resolutionStyle: "Đưa quan hệ tiến lên bằng trò chuyện, lựa chọn, cam kết và việc chấp nhận hậu quả.", chapterUnit: "Mỗi chương có một thay đổi về sự thân mật, ranh giới hoặc lựa chọn thực tế.", volumeReward: "Cuối tập, nhân vật xác nhận quan hệ, chia tay hoặc đưa ra một lựa chọn trưởng thành mới.", mandatorySignals: ["Mong muốn của nhân vật", "Ranh giới trong quan hệ", "Hậu quả cảm xúc"], antiSignals: ["Biến nhân vật thành công cụ thỏa mãn", "Quan hệ không có thay đổi"], momentumSource: "relationship_emotion", perChapterChangeMenu: ["Mức độ bị thu hút hoặc kháng cự thay đổi", "Một ranh giới được thăm dò, xác nhận hoặc vượt qua", "Áp lực thực tế xen vào quan hệ", "Một lựa chọn về cam kết hoặc tương lai", "Hậu quả cảm xúc xuất hiện"], twistCadence: "rare", foreshadowHold: "arc", endingHookStyle: "decision" }),
    children: [],
  },
  {
    id: "story_mode_power_root",
    name: "Sảng văn",
    description: "Mô thức này tạo cảm giác hả hê bằng ưu thế rõ rệt, những màn khẳng định vị thế và các lần đảo chiều có nhịp độ.",
    template: "Tập trung thể hiện năng lực, lật ngược thế cờ và đem lại kết quả thỏa mãn rõ ràng cho người đọc.",
    profile: buildProfile({
      coreDrive: "Tạo cảm giác hả hê bằng cách liên tục cho thấy nhân vật chính chiếm ưu thế, trong khi người khác phải thay đổi cách nhìn về họ.",
      readerReward: "Người đọc liên tục thấy sự áp chế, lập uy, đảo chiều và luật lệ bị viết lại.",
      progressionUnits: ["Lập uy", "Đập tan nghi ngờ", "Mở rộng tầm ảnh hưởng", "Áp đảo theo giai đoạn"],
      allowedConflictForms: ["Áp chế bằng thân phận", "Sai lệch nhận thức", "Thách thức quyền lực", "Viết lại luật chơi"],
      forbiddenConflictForms: ["Yếu thế cầu sinh trong thời gian dài", "Liên tục chịu thiệt mà không phản kích"],
      conflictCeiling: "high",
      resolutionStyle: "Nhanh chóng đưa nhân vật chính trở lại thế chủ động, biến xung đột thành dịp thể hiện sức mạnh và địa vị.",
      chapterUnit: "Mỗi chương đẩy một lần áp chế, đảo chiều hoặc một kết quả lập uy.",
      volumeReward: "Cuối tập hình thành sự công nhận, sợ hãi, quy phục hoặc viết lại trật tự trên phạm vi rộng hơn.",
      mandatorySignals: ["Cảm giác ưu thế", "Cảm giác tương phản", "Cảnh lập uy"],
      antiSignals: ["Nhân vật chính bị động trong thời gian dài", "Cứ tạo kỳ vọng nhưng không đem lại màn thể hiện xứng đáng"],
    }),
    children: [
      {
        id: "story_mode_invincible",
        name: "Nhân vật chính vô địch",
        description: "Nhân vật chính áp đảo ngay từ đầu; sức hút của truyện nằm ở những màn thể hiện năng lực và thay đổi cục diện, không phải ở nguy cơ sống còn.",
        template: "Cho thấy năng lực vượt trội của nhân vật chính từ sớm, rồi tập trung vào việc phá thế bí, khiến đối thủ khuất phục và thay đổi luật chơi.",
        profile: buildProfile({
          coreDrive: "Để nhân vật chính dùng năng lực vượt trội vượt qua mọi trở ngại và liên tục khiến người khác phải nhìn nhận lại mình.",
          readerReward: "Cứ vài chương, người đọc lại được chứng kiến một màn áp đảo và một bước tiến mới về danh tiếng hoặc địa vị.",
          progressionUnits: ["Cho thấy năng lực thật", "Đánh bại đối thủ", "Mở rộng ảnh hưởng", "Thay đổi luật chơi"],
          allowedConflictForms: ["Bị hiểu lầm về thân phận", "Thế lực khác khiêu khích", "Cao thủ đến thăm dò"],
          forbiddenConflictForms: ["Trốn tránh và âm thầm tích lũy quá lâu", "Bị dồn ép liên tục nhưng không thể phản công"],
          conflictCeiling: "high",
          resolutionStyle: "Xung đột được giải quyết bằng một màn phản công nhanh và cách biệt năng lực rõ ràng.",
          chapterUnit: "Mỗi chương có một lần nhân vật chính thể hiện năng lực, vượt qua thử thách hoặc khẳng định vị thế.",
          volumeReward: "Cuối tập, nhân vật chính tạo ra một trật tự quyền lực mới hoặc được công nhận ở quy mô lớn hơn.",
          mandatorySignals: ["Khí chất của người mạnh", "Người chứng kiến kinh ngạc", "Đánh bại đối thủ mạnh hơn"],
          antiSignals: ["Nhân vật chính yếu thế quá lâu như truyện tu luyện thông thường", "Cố tình làm mất tác dụng năng lực cốt lõi"],
        }),
      },
      {
        id: "story_mode_face_slap",
        name: "Màn đáp trả",
        description: "Lấy sự phán đoán sai, xem thường và cú lật ngược nhục mặt làm điểm sảng tần suất cao.",
        template: "Trước hết để đối phương hiểu lầm và xem thường, sau đó lật ngược tình thế thật gọn; màn đáp trả phải đến đúng lúc.",
        profile: buildProfile({
          coreDrive: "Tạo cảm giác hả hê bằng những lần đối phương hiểu sai, xem thường rồi bị nhân vật chính lật ngược tình thế.",
          readerReward: "Người đọc liên tục được chứng kiến kẻ xem thường nhân vật chính phải trả giá và bị đáp trả ngay tại chỗ.",
          progressionUnits: ["Để đối phương hiểu lầm", "Lộ thân phận thật", "Đáp trả công khai", "Danh tiếng lan rộng"],
          allowedConflictForms: ["Xem thường", "Sỉ nhục công khai", "Tranh giành tài nguyên"],
          forbiddenConflictForms: ["Để đối phương hiểu lầm quá lâu mà chưa đáp trả", "Vạch mặt xong nhưng không tạo ra thay đổi thực tế"],
          resolutionStyle: "Lật ngược tình thế và đáp trả ngay tại nơi nhân vật chính cần chứng minh bản thân nhất.",
          chapterUnit: "Mỗi chương khép lại một vòng: đối phương hiểu lầm, nhân vật chính lật ngược tình thế và đáp trả.",
          volumeReward: "Cuối tập, nhân vật chính từ người bị xem nhẹ trở thành nhân vật trung tâm không ai dám phớt lờ.",
          mandatorySignals: ["Đối phương hiểu lầm", "Tình thế đảo chiều", "Màn đáp trả tại chỗ"],
          antiSignals: ["Chỉ bị chèn ép mà không phản đòn", "Đáp trả quá nhẹ, không tạo được cảm giác hả hê"],
        }),
      },
      {
        id: "story_mode_misread",
        name: "Hiểu lầm dây chuyền",
        description: "Tạo sức hút từ việc người khác hiểu sai nhân vật chính, tự suy diễn rồi đẩy sự việc đi xa hơn dự tính.",
        template: "Mỗi hiểu lầm cần phát triển hợp lý và cuối cùng đem lại lợi thế cho nhân vật chính.",
        profile: buildProfile({
          coreDrive: "Khai thác những suy diễn quá đà của người khác để nhân vật chính liên tục có được lợi thế ngoài dự tính.",
          readerReward: "Người đọc liên tục có cảm giác tương phản kiểu 'người ta tự suy diễn quá đà'.",
          progressionUnits: ["Hiểu sai", "Suy diễn quá đà", "Đám đông hùa theo", "Hiểu lầm được giải tỏa"],
          allowedConflictForms: ["Bất đối xứng thông tin", "Hiểu lầm dây chuyền", "Đám đông đọc lệch"],
          forbiddenConflictForms: ["Giải thích rõ ngay lập tức", "Hiểu lầm chỉ kéo dài một lần rồi kết thúc"],
          conflictCeiling: "medium",
          resolutionStyle: "Để hiểu lầm tự nhiên lăn lớn, và chuyển hoá thành tài nguyên hoặc danh tiếng cho nhân vật chính.",
          chapterUnit: "Một chương xoay quanh một lần hiểu lầm leo thang và một khoản lợi bất ngờ.",
          volumeReward: "Cuối tập hệ thống hiểu lầm hình thành một sự đồng thuận ổn định hoặc một hình tượng truyền kỳ.",
          mandatorySignals: ["Tự suy diễn", "Lan truyền mất kiểm soát", "Nhân vật chính hưởng lợi bị động"],
          antiSignals: ["Hiểu lầm gượng ép", "Ai cũng nhìn thấu quá nhanh"],
        }),
      },
      {
        id: "story_mode_secret_identity",
        name: "Giấu thân phận",
        description: "Dùng nhiều thân phận, bí mật chưa được hé lộ và nguy cơ bị phát hiện để giữ người đọc muốn biết tiếp.",
        template: "Mỗi thân phận giả phải có mục đích riêng; nguy cơ bị phát hiện cần liên tục tạo áp lực cho câu chuyện.",
        profile: buildProfile({
          coreDrive: "Tạo sự căng liên tục qua việc chuyển đổi giữa nhiều thân phận, ẩn giấu và nguy cơ lộ vỏ bọc.",
          readerReward: "Người đọc liên tục thấy khoảng cách thân phận, khoảng cách thông tin và cảm giác kích thích bên bờ lộ vỏ bọc.",
          progressionUnits: ["Tạo thân phận giả", "Đổi thân phận", "Suýt bị phát hiện", "Bí mật bị hé lộ"],
          allowedConflictForms: ["Ẩn giấu thân phận", "Lệch pha quan hệ", "Phán đoán sai về nguồn gốc năng lực"],
          forbiddenConflictForms: ["Mọi vỏ bọc chức năng trùng nhau", "Lộ vỏ bọc không có hậu quả"],
          conflictCeiling: "medium",
          resolutionStyle: "Giải quyết vấn đề xoay quanh việc chuyển đổi thân phận, rồi chuyển áp lực sang nguy cơ lộ vỏ bọc ở tầng tiếp theo.",
          chapterUnit: "Mỗi chương đẩy ít nhất một lần tận dụng thân phận hoặc một lần nguy cơ áp sát.",
          volumeReward: "Cuối tập hình thành một cú lộ vỏ bọc then chốt hoặc một mạng lưới thân phận phức tạp hơn.",
          mandatorySignals: ["Khoảng cách thông tin", "Chuyển đổi thân phận", "Móc câu lộ vỏ bọc"],
          antiSignals: ["Tuyến thân phận đứng yên trong thời gian dài", "Vỏ bọc chỉ khác tên chứ không có công dụng"],
        }),
      },
    ],
  },
  {
    id: "story_mode_build_root",
    name: "Xây dựng kinh doanh",
    description: "Kiểu đọc lấy tích luỹ, xây dựng, kinh doanh và thu hoạch theo giai đoạn làm cách đẩy truyện chính.",
    template: "Cho thế giới trở nên phong phú hơn, vững chắc hơn, đáng giá hơn theo từng hành động của nhân vật chính.",
    profile: buildProfile({
      coreDrive: "Tạo cảm giác thành tựu liên tục qua tích luỹ, mở rộng, kinh doanh và thành quả xây dựng.",
      readerReward: "Người đọc thấy được cảm giác tài nguyên nhiều lên, địa bàn vững lên, hệ thống hoàn chỉnh hơn.",
      progressionUnits: ["Tích luỹ tài nguyên", "Xây dựng công trình", "Nâng cấp kinh doanh", "Thu hoạch theo giai đoạn"],
      allowedConflictForms: ["Áp lực tài nguyên", "Cạnh tranh kinh doanh", "Trở ngại phát triển"],
      forbiddenConflictForms: ["Phản diện lấn át tuyến xây dựng trong thời gian dài", "Chỉ đẩy truyện bằng đại chiến"],
      conflictCeiling: "medium",
      resolutionStyle: "Ưu tiên hoá giải vấn đề bằng kinh doanh, tổ chức, xây dựng và điều phối tài nguyên.",
      chapterUnit: "Mỗi chương đẩy một đơn vị kinh doanh hoặc xây dựng thấy được.",
      volumeReward: "Cuối tập cho ra một diện mạo thành quả vững hơn, lớn hơn, phong phú hơn.",
      mandatorySignals: ["Tích luỹ", "Quá trình xây dựng", "Phô bày thành quả"],
      antiSignals: ["Động lực chính biến thành văn thuần chiến đấu", "Lâu không thấy thu hoạch"],
    }),
    children: [
      {
        id: "story_mode_farming",
        name: "Điền văn (trồng trọt)",
        description: "Kiểu xây dựng coi trọng sản xuất, tích luỹ, trật tự đời sống và cảm giác ấm dần về lâu dài.",
        template: "Tập trung viết vòng tuần hoàn tài nguyên, kinh doanh đất đai hoặc cứ điểm, quan hệ chín dần và thu hoạch theo giai đoạn.",
        profile: buildProfile({
          coreDrive: "Từng chút một làm sống lại đời sống và sản xuất, mang lại cho người đọc cảm giác ấm dần và tích luỹ ổn định.",
          readerReward: "Người đọc liên tục thoả mãn với cảm giác 'ngày tháng khá lên' và 'của nả dày lên'.",
          progressionUnits: ["Chuẩn bị gieo trồng", "Tích luỹ sản xuất", "Tương tác láng giềng", "Trả về thu hoạch"],
          allowedConflictForms: ["Thiếu hụt tài nguyên", "Áp lực thời tiết và môi trường", "Va chạm lợi ích quy mô nhỏ"],
          forbiddenConflictForms: ["Lằn ranh sinh tử cao áp kéo dài", "Tuyến đại phản diện không hồi kết"],
          conflictCeiling: "low",
          resolutionStyle: "Từ từ giải quyết vấn đề bằng sự chăm chỉ, tổ chức, tương trợ và kinh doanh.",
          chapterUnit: "Một chương xoay quanh một việc lao động, một hạng mục xây dựng hoặc một đoạn đời sống khá lên.",
          volumeReward: "Cuối tập hình thành một giai đoạn đời sống rõ ràng ổn định hơn, ấm áp hơn.",
          mandatorySignals: ["Cảm giác đời sống", "Chi tiết lao động", "Thu hoạch theo giai đoạn"],
          antiSignals: ["Chỉ còn đánh quái và âm mưu", "Không thấy đời sống khá lên"],
        }),
      },
      {
        id: "story_mode_management",
        name: "Xây dựng cơ nghiệp",
        description: "Đẩy cốt truyện bằng vận hành thương mại, tổ chức, thương hiệu hoặc hệ thống.",
        template: "Nhấn vào ra quyết định, vận hành, mở rộng, danh tiếng và kết quả kinh doanh theo giai đoạn.",
        profile: buildProfile({
          coreDrive: "Tạo cảm giác đi lên liên tục qua quyết định kinh doanh và mở rộng tổ chức.",
          readerReward: "Người đọc liên tục thấy việc kinh doanh chạy được, tổ chức thành hình và danh tiếng tăng lên.",
          progressionUnits: ["Tìm ra điểm đột phá", "Dựng quy trình", "Mở rộng quy mô", "Thắng thị trường"],
          allowedConflictForms: ["Cạnh tranh kinh doanh", "Điều phối tài nguyên", "Ăn ý trong đội ngũ"],
          forbiddenConflictForms: ["Tình cảm cẩu huyết không liên quan lấn át lâu dài", "Quá trình kinh doanh bị lướt qua"],
          resolutionStyle: "Giải quyết vấn đề bằng chiến lược, vận hành, phân công và quản lý nhịp độ.",
          chapterUnit: "Một chương đẩy một động tác kinh doanh hoặc một vấn đề tổ chức.",
          volumeReward: "Cuối tập hình thành sự nâng cấp về nghiệp vụ, xác lập thương hiệu hoặc một bước nhảy về tổ chức.",
          mandatorySignals: ["Cảm giác chiến lược", "Động tác kinh doanh", "Phản hồi kết quả"],
          antiSignals: ["Chỉ kể kết quả không kể quá trình", "Tuyến kinh doanh bị tuyến phản diện nuốt chửng"],
        }),
      },
      {
        id: "story_mode_territory_building",
        name: "Xây dựng lãnh địa",
        description: "Đẩy truyện liên tục xoay quanh cứ điểm, thị trấn, bản đồ thế lực và dựng trật tự.",
        template: "Tập trung viết nâng cấp lãnh địa, quy tụ dân cư, thiết lập luật lệ và củng cố phòng tuyến.",
        profile: buildProfile({
          coreDrive: "Tạo cảm giác thành tựu về mở rộng và củng cố liên tục qua việc từng bước gây dựng một mảnh đất, một toà thành hoặc một cứ điểm thành hình.",
          readerReward: "Người đọc liên tục thấy lãnh địa mạnh lên, trật tự thành hình và cảm giác an toàn tăng lên.",
          progressionUnits: ["Chiêu mộ và an cư", "Xây dựng cơ sở", "Luật lệ đi vào vận hành", "Đánh trả sự thăm dò từ bên ngoài"],
          allowedConflictForms: ["Căng thẳng tài nguyên", "Va chạm biên giới", "Áp lực quản lý", "Khủng hoảng an ninh"],
          forbiddenConflictForms: ["Lãnh địa lâu dài như không tồn tại", "Tuyến chính bị ân oán cá nhân thuần tuý cuốn đi hoàn toàn"],
          conflictCeiling: "medium",
          resolutionStyle: "Ưu tiên ổn định cục diện bằng xây dựng, quản trị, tổ chức và phản kích cục bộ.",
          chapterUnit: "Một chương đẩy một động tác xây dựng lãnh địa, một vấn đề quản trị hoặc một lần ứng phó thăm dò từ bên ngoài.",
          volumeReward: "Cuối tập cho quy mô, trật tự hoặc tầm ảnh hưởng của lãnh địa có một bước nhảy rõ ràng.",
          mandatorySignals: ["Cứ điểm lớn lên", "Động tác quản trị", "Trật tự thành hình"],
          antiSignals: ["Chỉ có chiến tranh không có xây dựng", "Sự hiện diện của lãnh địa ngày càng mờ nhạt"],
        }),
      },
      {
        id: "story_mode_family_management",
        name: "Kinh doanh gia tộc",
        description: "Đẩy sự đọc tiếp liên tục bằng cơ nghiệp gia tộc, quan hệ trong nhà và trách nhiệm giữa các thế hệ.",
        template: "Viết sống động cùng lúc cả kinh doanh tài nguyên, phân công trong gia tộc và thay đổi quan hệ nội bộ.",
        profile: buildProfile({
          coreDrive: "Duy trì mạch truyện qua mở rộng cơ nghiệp, tái cấu trúc quan hệ gia tộc và truyền thừa trách nhiệm.",
          readerReward: "Người đọc vừa thấy của nả dày lên, vừa thấy quan hệ giữa các thành viên gia tộc ngày càng thành hệ thống.",
          progressionUnits: ["Điều chỉnh cơ nghiệp", "Các thành viên ăn ý dần", "Tích luỹ tài nguyên", "Địa vị gia tộc nâng lên"],
          allowedConflictForms: ["Bất đồng việc nhà", "Phân chia lợi ích", "Cạnh tranh bên ngoài", "Xung đột quan niệm giữa các thế hệ"],
          forbiddenConflictForms: ["Xé nát cẩu huyết lấn át tuyến kinh doanh lâu dài", "Thành viên gia tộc chỉ có chức năng công cụ, không có thay đổi quan hệ"],
          conflictCeiling: "medium",
          resolutionStyle: "Hoàn thành việc hàn gắn qua thương lượng, phân công, kết quả kinh doanh và cùng nhau ứng phó khủng hoảng.",
          chapterUnit: "Một chương đẩy một động tác về cơ nghiệp, một lần tương tác gia tộc hoặc một lần thực hiện trách nhiệm.",
          volumeReward: "Cuối tập cho gia tộc vững hơn, gắn kết hơn, hoặc hoàn thành một bước nhảy về địa vị.",
          mandatorySignals: ["Phối hợp gia tộc", "Động tác cơ nghiệp", "Tái cấu trúc quan hệ"],
          antiSignals: ["Chỉ còn cãi vã không thấy kinh doanh", "Tuyến gia tộc không có cảm giác truyền thừa"],
        }),
      },
    ],
  },
  {
    id: "story_mode_healing_root",
    name: "Đời thường chữa lành",
    description: "Lấy sự đồng hành, hàn gắn, đời sống ấm dần và cảm giác đồng hành nhẹ nhàng bền bỉ làm động lực cốt lõi.",
    template: "Mâu thuẫn có thể có, nhưng không được phá vỡ cảm giác ấm dần và cảm giác đồng hành.",
    profile: buildProfile({
      coreDrive: "Thu hút người đọc liên tục qua sự đồng hành, hàn gắn, chi tiết đời sống và quan hệ ấm dần.",
      readerReward: "Người đọc liên tục có cảm giác thoả mãn khi thấy yên ổn, dịu dàng, ấm dần và cảm xúc được đặt xuống.",
      progressionUnits: ["Đời thường", "Đồng hành và hàn gắn", "Giải quyết vấn đề nhỏ", "Quan hệ ấm lại"],
      allowedConflictForms: ["Khó khăn cường độ thấp đến vừa", "Lệch pha quan hệ", "Áp lực đời sống"],
      forbiddenConflictForms: ["Đối đầu cao áp liên tục", "Đẩy truyện kiểu hắc hoá", "Đâm sau lưng không hồi kết"],
      conflictCeiling: "low",
      resolutionStyle: "Ưu tiên hoá giải vấn đề bằng đồng hành, thấu hiểu, hành động đời thường và hàn gắn phạm vi nhỏ.",
      chapterUnit: "Mỗi chương xoay quanh một mảnh đời sống hoặc một điểm hàn gắn cảm xúc.",
      volumeReward: "Cuối tập cho người đọc cảm giác trạng thái nhân vật vững hơn, ấm hơn, sẵn lòng sống tiếp hơn.",
      mandatorySignals: ["Cảm giác đời sống", "Điểm xoa dịu", "Quan hệ ấm lại"],
      antiSignals: ["Tuyến chính cao áp lấn át", "Cảm giác chữa lành bị ngắt quãng liên tục"],
      momentumSource: "relationship_emotion",
      perChapterChangeMenu: ["Một vấn đề nhỏ được giải quyết một cách dịu dàng", "Quan hệ ấm lại hoặc sâu thêm một tầng", "Chi tiết đời sống mang lại một lần cảm xúc được đặt xuống", "Một vết thương cũ của nhân vật được chạm nhẹ hoặc hàn gắn"],
      twistCadence: "rare",
      foreshadowHold: "short",
      endingHookStyle: "emotional_pull",
    }),
    children: [
      {
        id: "story_mode_healing_daily",
        name: "Nhật thường chữa lành",
        description: "Kiểu chữa lành lấy tương tác đời thường, sự đồng hành và cảm xúc ấm lại làm điểm nhìn chính.",
        template: "Giữ khó khăn ở cường độ thấp và điểm xoa dịu ở mật độ cao, để người đọc muốn nán lại.",
        profile: buildProfile({
          coreDrive: "Dùng sự đồng hành đời thường và những lần hàn gắn nhỏ để từ từ đưa nhân vật về trạng thái ổn định.",
          readerReward: "Cứ vài chương người đọc lại có một lần trải nghiệm cảm xúc được vỗ về.",
          progressionUnits: ["Tương tác đời thường", "Xoa dịu cảm xúc", "Quan hệ chín dần", "Đời sống khá lên"],
          allowedConflictForms: ["Trắc trở nhỏ trong đời sống", "Quan hệ ngượng ngập", "Vết thương cũ vọng lại"],
          forbiddenConflictForms: ["Đại phản diện đè xuống", "Nỗi đau cực đoan kéo dài không thu hồi"],
          conflictCeiling: "low",
          resolutionStyle: "Cho nhân vật được chữa lành từng chút một qua đồng hành, lắng nghe và hành động cụ thể.",
          chapterUnit: "Mỗi chương xoay quanh một điểm cảm xúc và một điểm xoa dịu.",
          volumeReward: "Cuối tập cho cả nhân vật lẫn người đọc cảm thấy trạng thái ấm lại rõ rệt.",
          mandatorySignals: ["Cảm giác được xoa dịu", "Chi tiết đời sống", "Tương tác dịu dàng"],
          antiSignals: ["Xung đột leo thang thành đại kịch cao áp", "Đọc xong một chương chỉ còn lại lo âu"],
        }),
      },
      {
        id: "story_mode_shop_daily",
        name: "Nhật thường quán nhỏ",
        description: "Lấy việc kinh doanh cửa tiệm và sự qua lại giữa người với người tạo thành nhịp đọc tiếp ổn định, chữa lành.",
        template: "Khách hàng, láng giềng và chuyện vặt kinh doanh đều phải trở thành cỗ máy đẩy truyện dịu dàng.",
        profile: buildProfile({
          coreDrive: "Tạo cảm giác mới mẻ liên tục qua kinh doanh cửa tiệm, câu chuyện của khách ghé và tương tác cộng đồng.",
          readerReward: "Người đọc vừa thấy thay đổi trong kinh doanh, vừa nhận được những câu chuyện ấm áp của người lạ.",
          progressionUnits: ["Sự kiện khách ghé", "Điều chỉnh kinh doanh", "Tương tác cộng đồng", "Khép lại một ngày"],
          allowedConflictForms: ["Áp lực kinh doanh quán nhỏ", "Va chạm nhân tình", "Chuyện vặt đời sống"],
          forbiddenConflictForms: ["Chèn ép ác tính liên tục", "Trinh thám nặng hoặc âm mưu cao áp chi phối"],
          resolutionStyle: "Hoá giải tự nhiên qua cách đối nhân xử thế, điều chỉnh kinh doanh và tương trợ cộng đồng.",
          chapterUnit: "Mỗi chương đẩy một lần tương tác với khách hoặc một sự kiện kinh doanh nhỏ.",
          volumeReward: "Cuối tập cho quán nhỏ đông khách hơn, có cảm giác thuộc về hơn.",
          mandatorySignals: ["Cảm giác không gian quán nhỏ", "Câu chuyện của khách ghé", "Hơi ấm cộng đồng"],
          antiSignals: ["Chỉ còn số liệu kinh doanh không còn tình người", "Sự hiện diện của cửa tiệm ngày càng mờ nhạt"],
        }),
      },
      {
        id: "story_mode_slow_life",
        name: "Sống chậm",
        description: "Tạo sức hút đọc bằng nhịp chậm lại, chi tiết đời sống và việc phục hồi trật tự thường nhật.",
        template: "Cho phong cảnh, lao động, ăn uống và cách sống chung đều trở thành một phần của trải nghiệm bình yên.",
        profile: buildProfile({
          coreDrive: "Giữ người đọc nán lại qua sự cải thiện đời sống chậm mà bền và cảm giác thân tâm an định.",
          readerReward: "Người đọc liên tục có cảm giác thư giãn, đắm chìm và 'cuối cùng cũng chậm lại được'.",
          progressionUnits: ["Sinh hoạt hằng ngày", "Quen dần với môi trường", "Đời sống khá lên", "Cảm xúc ổn lại"],
          allowedConflictForms: ["Chưa quen chút ít", "Vướng bận nhỏ trong đời sống", "Ăn ý lại sau khi quan hệ xa cách"],
          forbiddenConflictForms: ["Đếm ngược cao áp liên tục", "Phản diện mạnh truy sát dài hạn hoặc âm mưu đè xuống"],
          conflictCeiling: "low",
          resolutionStyle: "Từ từ hoá giải vấn đề bằng thời gian, sự đồng hành, nếp sống đều đặn và những bước hàn gắn nhỏ.",
          chapterUnit: "Một chương xoay quanh một mảnh đời sống, một cải thiện nhỏ hoặc một lần cảm xúc được đệm lại.",
          volumeReward: "Cuối tập cho nhân vật thật sự có được một trạng thái sống vững hơn, dễ chịu hơn.",
          mandatorySignals: ["Trật tự đời sống", "Cảm giác thư thả", "Sự đắm chìm vào chi tiết"],
          antiSignals: ["Vì muốn kích thích mà liên tục gượng ép xung đột lớn", "Nhịp ngày càng gấp, không có khoảng thở"],
        }),
      },
      {
        id: "story_mode_companion_healing",
        name: "Đồng hành trị liệu",
        description: "Lấy sự đồng hành ổn định, chăm sóc và cùng nhau hồi phục giữa người với người làm cỗ máy đẩy truyện chính.",
        template: "Mâu thuẫn phải phục vụ cho sự lại gần, tin tưởng và hàn gắn, chứ không phải xé nát liên tục.",
        profile: buildProfile({
          coreDrive: "Dẫn dắt sự trả về cảm xúc qua việc quan hệ đồng hành từng bước hình thành và cảm giác an toàn từng bước tích luỹ.",
          readerReward: "Người đọc liên tục nhận được sự thoả mãn dịu dàng khi được thấu hiểu, được có người đi cùng qua giai đoạn thấp nhất.",
          progressionUnits: ["Lại gần và thăm dò", "Chăm sóc đời thường", "Cảm xúc lỏng ra", "Xác nhận quan hệ"],
          allowedConflictForms: ["Né tránh vết thương cũ", "Giao tiếp trì trệ", "Áp lực đời sống", "Hiểu lầm ngắn ngủi"],
          forbiddenConflictForms: ["Đâm sau lưng lặp đi lặp lại", "Điểm ngược lâu không thu hồi", "Quan hệ giằng co ác tính mất kiểm soát"],
          conflictCeiling: "low",
          resolutionStyle: "Hoàn thành hàn gắn bằng sự kiên nhẫn, đồng hành, hỗ trợ bằng hành động và hồi đáp cảm xúc.",
          chapterUnit: "Một chương đẩy một hành động đồng hành, một lần quan hệ lỏng ra hoặc một lần cảm xúc được đặt xuống.",
          volumeReward: "Cuối tập cho quan hệ then chốt ấm lên rõ rệt, nhân vật sẵn lòng tin người khác và tin vào cuộc sống hơn.",
          mandatorySignals: ["Cảm giác đồng hành", "Sự tin tưởng lớn lên", "Hàn gắn thành hiện thực"],
          antiSignals: ["Tuyến chữa lành bỗng biến thành giằng co ngược luyến", "Quan hệ đồng hành không có tiến triển thực chất"],
        }),
      },
    ],
  },
  {
    id: "story_mode_comedy_root",
    name: "Hài hước tấu hài",
    description: "Lấy tương phản, mảng miếng, hiểu lầm và thu hồi từ những pha mất kiểm soát làm động lực đọc tiếp chính.",
    template: "Nhẹ nhàng không phải là nhãn giọng điệu, mà là cơ chế tiếng cười được trả về liên tục trong kết cấu chương.",
    profile: buildProfile({
      coreDrive: "Tạo cảm giác nhẹ nhàng sảng khoái liên tục qua tương phản, mảng miếng, hiểu lầm và nhịp tấu hài.",
      readerReward: "Người đọc thường xuyên nhận được tiếng cười, sự phản mô-típ và trải nghiệm giải toả cảm xúc.",
      progressionUnits: ["Gài mảng miếng", "Hiểu lầm leo thang", "Thu hồi tương phản", "Cục diện mất kiểm soát"],
      allowedConflictForms: ["Hiểu lầm", "Tương phản", "Ngượng chín người", "Tấu hài lật xe"],
      forbiddenConflictForms: ["Tuyến u ám nặng nề chiếm ưu thế lâu dài", "Tiếng cười không được thu hồi"],
      conflictCeiling: "medium",
      resolutionStyle: "Hoàn thành sự giải toả qua việc thu hồi mảng miếng và những cảnh mất kiểm soát.",
      chapterUnit: "Mỗi chương ít nhất phải đẩy một kết cấu tiếng cười có hiệu quả.",
      volumeReward: "Cuối tập hình thành một cảnh tấu hài kinh điển lớn hơn hoặc một cộng đồng hiểu lầm.",
      mandatorySignals: ["Tương phản", "Thu hồi", "Giải toả nhẹ nhàng"],
      antiSignals: ["Nghiêm túc quá lâu không có mảng miếng", "Tiếng cười chỉ dựa vào tật nói và mẩu chuyện chồng chất"],
      momentumSource: "comedic_situation",
      perChapterChangeMenu: ["Một mảng miếng được bung ra", "Hiểu lầm leo thang hoặc tương phản được thu hồi", "Cục diện mất kiểm soát một cách hài hước rồi lại được đỡ lấy", "Quan hệ nhân vật thay đổi ngầm trong lúc cười đùa"],
      twistCadence: "rare",
      foreshadowHold: "short",
      endingHookStyle: "emotional_pull",
    }),
    children: [
      {
        id: "story_mode_comedy",
        name: "Hài tình huống",
        description: "Tiếng cười tần suất cao, tương phản và sự thu hồi nhẹ nhàng là cốt lõi của việc đọc.",
        template: "Tiếng cười phải xuất hiện có kết cấu, không thể chỉ dựa vào những câu thoại đắt giá rời rạc.",
        profile: buildProfile({
          coreDrive: "Duy trì niềm vui đọc qua mảng miếng tần suất cao, tương phản và những cảnh mất kiểm soát.",
          readerReward: "Mỗi chương người đọc đều thu được sự nhẹ nhàng và điểm buồn cười rõ ràng.",
          progressionUnits: ["Gài mảng miếng", "Tương phản leo thang", "Thu hồi tiếng cười", "Cảnh lật xe"],
          allowedConflictForms: ["Hiểu lầm", "Ngượng chín người", "Tương phản thân phận", "Lệch pha nhận thức"],
          forbiddenConflictForms: ["Tuyến bi lụy nặng nề kéo dài", "Tiếng cười loãng lại không đẩy được cốt truyện"],
          resolutionStyle: "Dùng thu hồi và leo thang để tiếp tục đẩy tiếng cười lên cao thay vì chuyển sang nặng nề.",
          chapterUnit: "Mỗi chương xoay quanh ít nhất một vòng khép kín mảng miếng có hiệu quả.",
          volumeReward: "Cuối tập hình thành một cảnh kinh điển hoặc một mẩu chuyện cười được lưu truyền.",
          mandatorySignals: ["Mảng miếng", "Thu hồi", "Cảm giác cảnh"],
          antiSignals: ["Cả đoạn đều rất nghiêm túc", "Chỉ có bắt bẻ mà không có kết cấu"],
        }),
      },
      {
        id: "story_mode_misunderstanding_comedy",
        name: "Hài hiểu lầm",
        description: "Tạo hiệu ứng hài liên tục nhờ khoảng cách thông tin giữa các bên và sự lan rộng của hiểu lầm.",
        template: "Hiểu lầm phải được phóng đại từng tầng, nhưng mỗi lần đều phải mang lại một cục diện mới.",
        profile: buildProfile({
          coreDrive: "Duy trì nhịp hài qua sự lan rộng của hiểu lầm do khoảng cách thông tin giữa các bên gây ra.",
          readerReward: "Người đọc liên tục thấy hiểu lầm càng lăn càng lớn mà lại càng thú vị.",
          progressionUnits: ["Dựng hiểu lầm", "Nhiều bên đọc sai", "Lan rộng mất kiểm soát", "Thu hồi hài hước"],
          allowedConflictForms: ["Hiểu lầm", "Giao tiếp lệch pha", "Cả đám đọc sai"],
          forbiddenConflictForms: ["Hiểu lầm được làm rõ quá nhanh", "Hiểu lầm chỉ lặp lại cùng một trò"],
          resolutionStyle: "Cho hiểu lầm được thu hồi ở vị trí buồn cười nhất, hoặc leo thang thành một tiếng cười lớn hơn.",
          chapterUnit: "Mỗi chương đẩy một tầng hiểu lầm mới hoặc một điểm thu hồi.",
          volumeReward: "Cuối tập hình thành một cảnh hiểu lầm kinh điển quy mô lớn.",
          mandatorySignals: ["Khoảng cách thông tin", "Đọc sai", "Lan rộng"],
          antiSignals: ["Hiểu lầm không có hậu lực", "Làm rõ quá nhanh khiến nhịp tắt ngóm"],
        }),
      },
      {
        id: "story_mode_absurd_subversion",
        name: "Sa điêu phản mô-típ",
        description: "Dùng diễn tiến lố bịch, sự thu hồi phản mô-típ và cú bẻ nhịp đột ngột để tạo cảm giác nhẹ nhàng mạnh mẽ.",
        template: "Phản mô-típ không chỉ là phá kỳ vọng, mà còn phải liên tục đưa ra cục diện mới thú vị hơn.",
        profile: buildProfile({
          coreDrive: "Duy trì sự mới mẻ qua việc liên tục phá vỡ kỳ vọng thông thường, rồi đưa ra một kết quả lố hơn nhưng lại hợp lý hơn.",
          readerReward: "Người đọc liên tục có cảm giác bất ngờ và nhẹ nhõm kiểu 'hoá ra còn có thể thế này'.",
          progressionUnits: ["Dựng kỳ vọng", "Bẻ ngoặt đột ngột", "Lố bịch leo thang", "Thu hồi phản mô-típ"],
          allowedConflictForms: ["Tương phản", "Lệch pha", "Tấu hài mất kiểm soát", "Chơi đùa với thiết lập"],
          forbiddenConflictForms: ["Chỉ còn phát điên vô nghĩa", "Lố bịch nhưng không có điểm tựa logic", "Chính kịch nặng nề liên tục"],
          conflictCeiling: "medium",
          resolutionStyle: "Thu hồi cục diện bằng một tầng phản mô-típ cao hơn, chứ không rơi trở lại xung đột chính thống nặng nề.",
          chapterUnit: "Mỗi chương ít nhất đẩy một vòng khép kín dựng kỳ vọng và thu hồi phản mô-típ.",
          volumeReward: "Cuối tập hình thành một cảnh lố bịch lan truyền mạnh hoặc một cao trào phản mô-típ.",
          mandatorySignals: ["Cảm giác bất ngờ", "Phản mô-típ", "Vòng khép kín thu hồi"],
          antiSignals: ["Hy sinh tính dễ đọc vì muốn gây cười", "Chồng chất mẩu chuyện mà không đẩy được truyện"],
        }),
      },
    ],
  },
  {
    id: "story_mode_mystery_root",
    name: "Đấu trí bí ẩn",
    description: "Đẩy sự đọc tiếp bằng khoảng cách thông tin, suy diễn, bày cục và sự thoả mãn trí tuệ khi đối kháng.",
    template: "Người đọc phải liên tục cảm thấy mình đang tiến sâu hơn về phía sự thật.",
    profile: buildProfile({
      coreDrive: "Tạo ham muốn đọc tiếp liên tục qua khoảng cách thông tin, suy diễn và sự leo thang của cuộc đấu trí.",
      readerReward: "Người đọc liên tục nhận được sự thoả mãn khi câu đố tiến triển, khoái cảm suy luận và sự thu hồi của thế cờ đã bày.",
      progressionUnits: ["Tung ra điểm nghi vấn", "Thu thập manh mối", "Suy diễn, kiểm chứng", "Cục diện đảo chiều"],
      allowedConflictForms: ["Khoảng cách thông tin", "Động cơ ẩn giấu", "Đối kháng trí tuệ"],
      forbiddenConflictForms: ["Vì giữ bí mật mà cố tình vô lý", "Đối kháng thuần thể lực nuốt mất cảm giác suy diễn"],
      conflictCeiling: "high",
      resolutionStyle: "Hoàn thành cú phản đòn qua chuỗi chứng cứ, suy diễn và thế cờ đã bày.",
      chapterUnit: "Mỗi chương đẩy một điểm nghi vấn mới hoặc kiểm chứng một điểm nghi vấn cũ.",
      volumeReward: "Cuối tập hé lộ một tầng sự thật lớn hơn hoặc hoàn thành một cuộc đấu trí then chốt.",
      mandatorySignals: ["Manh mối", "Suy diễn", "Phản đòn"],
      antiSignals: ["Câu đố chỉ chồng chất không giải", "Đáp án từ trên trời rơi xuống"],
      momentumSource: "information_revelation",
      perChapterChangeMenu: ["Tung ra hoặc khép lại một điểm nghi vấn", "Hé lộ một tầng sự thật và tạo ra một ẩn số lớn hơn", "Tái cấu trúc ý nghĩa của thông tin đã biết trước đó", "Bày cục hoặc phản đòn tiến thêm một bước", "Đảo nhận thức: sự thật người đọc tưởng là đúng bị lật đổ"],
      twistCadence: "dense",
      foreshadowHold: "cross_arc",
      endingHookStyle: "revelation",
    }),
    children: [
      {
        id: "story_mode_mystery_inference",
        name: "Trinh thám suy diễn",
        description: "Lấy manh mối, suy luận và nhịp hé lộ sự thật làm cốt lõi của việc đọc.",
        template: "Mỗi đoạn suy diễn phải dựa trên manh mối rõ ràng, không phải tác giả giải thích gượng.",
        profile: buildProfile({
          coreDrive: "Cho người đọc bám theo manh mối và suy diễn để liên tục tiến gần sự thật.",
          readerReward: "Người đọc liên tục nhận được sự thoả mãn trí tuệ kiểu 'mảnh ghép đang thành hình'.",
          progressionUnits: ["Nêu điểm nghi vấn", "Bổ sung manh mối", "Suy diễn khép lại", "Hé lộ sự thật"],
          allowedConflictForms: ["Manh mối mâu thuẫn", "Lời khai chọi nhau", "Động cơ ẩn giấu"],
          forbiddenConflictForms: ["Chứng cứ then chốt xuất hiện từ hư không", "Cố tình mập mờ để câu giờ"],
          resolutionStyle: "Phá cục bằng cách liên kết các manh mối và suy diễn logic.",
          chapterUnit: "Mỗi chương đẩy một thay đổi nhận thức về một điểm nghi vấn then chốt.",
          volumeReward: "Cuối tập vạch trần câu đố cốt lõi hoặc mở ra một cửa vào bí ẩn lớn hơn.",
          mandatorySignals: ["Cảm giác manh mối", "Chuỗi logic", "Sự thật áp sát"],
          antiSignals: ["Ra vẻ huyền bí", "Kết luận tách rời manh mối"],
          momentumSource: "information_revelation",
          perChapterChangeMenu: ["Bổ sung một manh mối then chốt", "Suy diễn khép lại làm thay đổi nhận thức về cục diện", "Vạch trần một lời nói dối hoặc một sự dẫn dắt sai", "Sự thật phân tầng: mở một tầng lộ ra tầng sâu hơn"],
          twistCadence: "dense",
          foreshadowHold: "cross_arc",
          endingHookStyle: "revelation",
        }),
      },
      {
        id: "story_mode_mind_game",
        name: "Đấu trí chiến lược",
        description: "Nhấn vào bày cục, đấu trí, tư duy của đối thủ và nhịp phản đòn.",
        template: "Đối thủ phải ra dáng đối thủ, cuộc đấu trí phải cảm nhận được.",
        profile: buildProfile({
          coreDrive: "Tạo khoái cảm đấu trí có độ dính cao qua nhiều vòng bày cục và gỡ chiêu.",
          readerReward: "Người đọc liên tục thấy sự tính toán, phản tính toán và sự thu hồi của những nước dự đoán trước.",
          progressionUnits: ["Bày cục", "Thăm dò", "Phản đòn", "Thu lưới"],
          allowedConflictForms: ["Đối kháng chiến lược", "Đấu trí tâm lý", "Tính toán tài nguyên"],
          forbiddenConflictForms: ["Đối thủ quá ngu", "Mọi chiến thắng đều nhờ nhân vật chính hack thông tin"],
          resolutionStyle: "Thắng cục diện bằng cách bày cục từ trước và phản đòn then chốt.",
          chapterUnit: "Mỗi chương đẩy một vòng thăm dò, đặt quân hoặc gỡ chiêu.",
          volumeReward: "Cuối tập hoàn thành một cú thu lưới đại cục hoặc để một đối thủ cấp cao hơn xuất hiện.",
          mandatorySignals: ["Cảm giác bày cục", "Sự áp bức của đối thủ", "Thu hồi phản đòn"],
          antiSignals: ["Thắng thua không có quá trình đấu trí", "Đối thủ bị công cụ hoá"],
          momentumSource: "information_revelation",
          perChapterChangeMenu: ["Một bên đặt quân hoặc thăm dò", "Nước hậu của đối thủ lộ ra làm thay đổi cục diện", "Một dự đoán then chốt được thu hồi hoặc bị phản đòn", "Khoảng cách thông tin dịch chuyển"],
          twistCadence: "dense",
          foreshadowHold: "arc",
          endingHookStyle: "revelation",
        }),
      },
      {
        id: "story_mode_survival_game",
        name: "Đấu trí sinh tồn",
        description: "Tạo cảm giác căng thẳng liên tục trong môi trường tài nguyên hạn chế, cao áp và cạnh tranh theo luật.",
        template: "Cao áp có thể tồn tại, nhưng phải phục vụ cho suy diễn luật lệ, cái giá của lựa chọn và sự phản đòn cục diện.",
        profile: buildProfile({
          coreDrive: "Tạo sự căng buộc phải đưa ra lựa chọn liên tục qua sự khan hiếm tài nguyên, áp lực môi trường và đối kháng theo luật.",
          readerReward: "Người đọc liên tục nhận được sự căng cứng khi giải cục diện, cân đo cái giá và lật ngược từ đường cùng.",
          progressionUnits: ["Áp lực áp sát", "Thăm dò luật lệ", "Tranh giành tài nguyên", "Phản đòn ngắn hạn"],
          allowedConflictForms: ["Khan hiếm tài nguyên", "Luật lệ đè ép", "Đe doạ môi trường", "Đấu trí theo nhóm"],
          forbiddenConflictForms: ["Thông quan thuần nhờ may mắn", "Chỉ có cận chiến không có chiến lược", "Lặp lại một kiểu khủng hoảng trong thời gian dài"],
          conflictCeiling: "high",
          resolutionStyle: "Phá cục dựa vào hiểu luật, phán đoán cục diện và bố trí tài nguyên hạn chế.",
          chapterUnit: "Một chương đẩy một vòng áp lực sinh tồn, một phát hiện về luật hoặc một lựa chọn then chốt.",
          volumeReward: "Cuối tập hoàn thành một lần sống sót theo giai đoạn, một cú phá luật hoặc viết lại cục diện phe phái.",
          mandatorySignals: ["Áp lực tài nguyên", "Cái giá của lựa chọn", "Tận dụng luật lệ"],
          antiSignals: ["Khủng hoảng bị làm cho rẻ tiền", "Luôn luôn lặp lại một kiểu khốn cảnh"],
          momentumSource: "survival_pressure",
          perChapterChangeMenu: ["Mức áp lực hoặc đe doạ nhảy vọt", "Phát hiện hoặc kiểm chứng một điều luật", "Được mất tài nguyên làm thay đổi xác suất sinh tồn", "Bị buộc phải đưa ra một lựa chọn có cái giá", "Quan hệ phe phái lật ngược"],
          twistCadence: "dense",
          foreshadowHold: "cross_arc",
          endingHookStyle: "escalation",
        }),
      },
      {
        id: "story_mode_apocalyptic_war",
        name: "Chiến tranh sinh tồn tuyệt vọng",
        description: "Một cộng đồng nhỏ bị dồn vào thế phải chiến đấu sinh tồn trước một mối đe doạ áp đảo mà họ chưa hiểu rõ; mỗi lần thắng nhỏ đều trả giá bằng mất mát, và sự thật về kẻ thù — hoặc về chính thế giới họ đang bảo vệ — lộ ra theo từng tầng, dần viết lại ai mới là kẻ thù thật sự. Phong cách các bộ chiến tranh sinh tồn kiểu \"Đại chiến Titan\": bi kịch, bí mật thế giới nhiều tầng và không có phe nào hoàn toàn đúng.",
        template: "Nhấn vào cái giá bằng mạng người của mỗi trận chiến, chuỗi mệnh lệnh quân sự hoặc tổ chức, và một bí mật thế giới được hé lộ theo tầng khiến người đọc phải viết lại nhận thức phe chính-tà. Không né tránh việc nhân vật quan trọng có thể hi sinh.",
        profile: buildProfile({
          coreDrive: "Đẩy truyện bằng một cuộc chiến sinh tồn không cân sức trước một mối đe doạ áp đảo, trong khi một bí mật về nguồn gốc thế giới hoặc kẻ thù dần lộ ra và lật đổ toàn bộ nhận thức ban đầu.",
          readerReward: "Người đọc liên tục nhận cao trào trận chiến trả giá bằng mất mát, cảm giác nhân vật mình gắn bó có thể hi sinh bất cứ lúc nào, và những lần bàng hoàng khi một tầng sự thật thế giới bị lật đổ.",
          progressionUnits: ["Mối đe doạ áp sát", "Trận chiến trả giá bằng mất mát", "Một mảnh sự thật thế giới lộ ra", "Nhận thức phe địch-ta bị viết lại"],
          allowedConflictForms: ["Đối đầu quân sự áp đảo về lực lượng", "Mâu thuẫn mệnh lệnh với lương tâm cá nhân", "Bí mật thể chế hoặc chính quyền bị che giấu", "Đồng đội hi sinh"],
          forbiddenConflictForms: ["Nhân vật chính bất tử hoá vô lý qua mọi trận đánh", "Kẻ thù chỉ là quái vật vô tri không có lịch sử hay bí mật đứng sau", "Mất mát bị giảm nhẹ hoặc không để lại hậu quả"],
          conflictCeiling: "high",
          resolutionStyle: "Sống sót và tiến lên bằng chiến thuật tập thể, cái giá về sinh mạng, và việc chấp nhận một sự thật mới dù nó phá vỡ niềm tin cũ.",
          chapterUnit: "Mỗi chương đẩy một đợt đối đầu với mối đe doạ hoặc một mảnh sự thật thế giới, kèm theo một cái giá cụ thể.",
          volumeReward: "Cuối tập, phe chính diện giành được một chỗ đứng sinh tồn mới, đồng thời một tầng bí mật lớn của thế giới được xác nhận, viết lại mục tiêu của tập sau.",
          mandatorySignals: ["Cái giá bằng sinh mạng hoặc tổn thất không thể đảo ngược", "Chuỗi mệnh lệnh và kỷ luật quân sự hoặc tổ chức", "Một manh mối về bí mật thế giới hoặc nguồn gốc kẻ thù"],
          antiSignals: ["Nhân vật chính đơn độc cân cả đội quân mà không trả giá", "Kẻ thù không có logic hay lịch sử đứng sau", "Bí mật thế giới bị bỏ quên, không được nhắc lại"],
          momentumSource: "survival_pressure",
          perChapterChangeMenu: ["Một đợt tấn công hoặc mối đe doạ mới xuất hiện", "Một nhân vật quan trọng hi sinh hoặc chịu mất mát không thể đảo ngược", "Một mảnh bí mật về kẻ thù hoặc thế giới được xác nhận", "Chuỗi mệnh lệnh bị thách thức bởi lương tâm cá nhân", "Ranh giới địch - ta bị viết lại bởi thông tin mới"],
          twistCadence: "dense",
          twistIntensity: "severe",
          twistFairness: "mixed",
          twistScope: "worldview_shattering",
          allowedTwistMechanisms: ["identity_concealment", "hidden_motive", "unreliable_narrator", "reality_break", "betrayal"],
          foreshadowHold: "cross_arc",
          endingHookStyle: "revelation",
        }),
      },
    ],
  },
  {
    id: "story_mode_relationship_root",
    name: "Quan hệ tình cảm",
    description: "Lấy sự tiến triển quan hệ, sự trả về cảm xúc và những giằng co thay đổi giữa các nhân vật làm động lực chính.",
    template: "Trọng tâm không phải chồng chất xung đột thuần tuý, mà là để trạng thái quan hệ liên tục thay đổi và trả về kỳ vọng của người đọc.",
    profile: buildProfile({
      coreDrive: "Tạo động lực đọc tiếp liên tục qua sự lại gần, giằng co, lệch pha và thu hồi trong quan hệ giữa các nhân vật.",
      readerReward: "Người đọc liên tục nhận được thay đổi quan hệ, sự căng cảm xúc và những lần trả về cảm xúc then chốt.",
      progressionUnits: ["Thiết lập quan hệ", "Giằng co cảm xúc", "Thay đổi lòng tin", "Trả về ở các cột mốc"],
      allowedConflictForms: ["Lệch pha quan hệ", "Lệch pha cảm xúc", "Trở lực thực tế", "Va chạm giá trị quan"],
      forbiddenConflictForms: ["Tuyến quan hệ giậm chân tại chỗ lâu dài", "Cẩu huyết vô nghĩa quẩn quanh lặp lại", "Sự tiến triển cảm xúc bị các tuyến khác nuốt chửng lâu dài"],
      conflictCeiling: "medium",
      resolutionStyle: "Hoàn thành sự tiến triển hoặc hàn gắn qua giao lưu cảm xúc, hành động trong quan hệ và những lựa chọn then chốt.",
      chapterUnit: "Mỗi chương đẩy một cột mốc quan hệ, một thay đổi cảm xúc hoặc một thay đổi trong nhận thức của hai bên về nhau.",
      volumeReward: "Cuối tập cho quan hệ then chốt có thay đổi rõ ràng hoặc hoàn thành một lần trả về cảm xúc giá trị cao.",
      mandatorySignals: ["Sự căng quan hệ", "Cột mốc cảm xúc", "Cảm giác được trả về"],
      antiSignals: ["Quan hệ giậm chân tại chỗ", "Chỉ có thiết lập mà không có tương tác"],
      momentumSource: "relationship_emotion",
      perChapterChangeMenu: ["Khoảng cách hoặc lòng tin trong quan hệ thay đổi thấy được", "Một lần lệch pha cảm xúc hoặc hiểu lầm được tạo ra / hoá giải", "Một cột mốc quan hệ được trả về", "Trở lực thực tế xen vào giữa hai người", "Nhận thức của hai bên về nhau thay đổi"],
      twistCadence: "rare",
      foreshadowHold: "arc",
      endingHookStyle: "emotional_pull",
    }),
    children: [
      {
        id: "story_mode_romantic_tension",
        name: "Giằng co yêu đương",
        description: "Tạo sức hút liên tục bằng sự mập mờ, lại gần, thoái lui và thăm dò quan hệ.",
        template: "Giằng co phải có chênh lệch nhiệt độ và có tiến triển, không thể chỉ dựa vào hiểu lầm để câu giờ.",
        profile: buildProfile({
          coreDrive: "Duy trì sự căng cảm xúc qua những lần giằng co lặp đi lặp lại giữa sức hút hai chiều và trở lực thực tế.",
          readerReward: "Người đọc liên tục thấy quan hệ ấm lên, sự thăm dò mất kiểm soát và cảm xúc được thu hồi.",
          progressionUnits: ["Thăm dò lại gần", "Va chạm ranh giới", "Cảm xúc mất cân bằng", "Quan hệ tiến triển"],
          allowedConflictForms: ["Mập mờ lệch pha", "Bày tỏ thất bại", "Trở lực thực tế", "Khác biệt giá trị quan"],
          forbiddenConflictForms: ["Cố tình tụt IQ không nói chuyện người", "Kéo dài quá lâu không tiến triển", "Tuyến quan hệ bị tuyến chính bên ngoài đè bẹp hoàn toàn"],
          conflictCeiling: "medium",
          resolutionStyle: "Hoàn thành sự tiến triển quan hệ qua nâng cấp tương tác, thừa nhận cảm xúc và lựa chọn hành động.",
          chapterUnit: "Một chương đẩy một lần thăm dò cảm xúc, một thay đổi nhận thức hoặc một lần ranh giới quan hệ lỏng ra.",
          volumeReward: "Cuối tập cho quan hệ bước vào giai đoạn mới, hoặc hoàn thành một lần xác nhận cảm xúc nồng độ cao.",
          mandatorySignals: ["Cảm giác mập mờ", "Sự căng hai chiều", "Trả về việc lại gần"],
          antiSignals: ["Chỉ có hiểu lầm câu giờ", "Không có thay đổi quan hệ thực chất"],
        }),
      },
      {
        id: "story_mode_chasing_wife",
        name: "Đuổi vợ nơi hoả táng",
        description: "Lấy tổn thương hoặc bỏ lỡ ở giai đoạn đầu làm tiền đề, đẩy truyện bằng sự bù đắp, hối hận và tái thiết quan hệ về sau.",
        template: "Cốt lõi là bù đắp và tái thiết, không phải một bên liên tục làm tổn thương.",
        profile: buildProfile({
          coreDrive: "Tạo lực kéo cảm xúc mạnh mẽ qua sự bù đắp, hối cải và tái thiết quan hệ sau khi đã mất đi.",
          readerReward: "Người đọc liên tục nhận được sự thoả mãn 'kẻ nên đuổi thì đang đuổi, món nên trả thì đang trả, chỗ nên đau thì có hồi đáp'.",
          progressionUnits: ["Hối hận hiện ra", "Hành động bù đắp", "Quan hệ chịu thử luyện", "Trả về việc tái thiết"],
          allowedConflictForms: ["Lòng tin đứt gãy", "Vết thương cũ phản kích", "Chênh lệch khi bù đắp", "Trở ngại thực tế"],
          forbiddenConflictForms: ["Bù đắp chỉ dừng ở lời nói", "Vòng lặp tổn thương lần hai vô hạn", "Bên bị đuổi hoàn toàn mất đi tính chủ thể"],
          conflictCeiling: "medium",
          resolutionStyle: "Đẩy sự tái thiết quan hệ bằng hành động liên tục, gánh chịu cái giá và tôn trọng ranh giới.",
          chapterUnit: "Một chương đẩy một hành động bù đắp, một lần va chạm vết thương cũ hoặc một lần quan hệ lỏng ra.",
          volumeReward: "Cuối tập hình thành một giai đoạn hàn gắn quan hệ rõ ràng hoặc một lần thu hồi cảm xúc mạnh.",
          mandatorySignals: ["Hối hận thành hiện thực", "Bù đắp bằng hành động", "Tái thiết ranh giới"],
          antiSignals: ["Chỉ biết xin lỗi bằng miệng", "Tái thiết quan hệ không có cái giá"],
        }),
      },
      {
        id: "story_mode_ensemble_bond",
        name: "Quần tượng gắn kết",
        description: "Tạo độ dính khi đọc qua mạng lưới quan hệ nhiều người, trải nghiệm chung và sự tiến hoá của mối gắn kết.",
        template: "Quần tượng không phải chồng chất danh sách, mà là mỗi nhân vật đều phải phát huy vai trò trong mạng lưới quan hệ.",
        profile: buildProfile({
          coreDrive: "Cho câu chuyện luôn có tia lửa quan hệ mới qua tương tác nhiều người và sự thay đổi của mối gắn kết.",
          readerReward: "Người đọc liên tục nhận được những kết nối mới, sự thay đổi phe cánh và cộng hưởng cảm xúc giữa các nhân vật.",
          progressionUnits: ["Nối kết quan hệ", "Sự kiện tập thể", "Thay đổi lập trường", "Mối gắn kết sâu thêm"],
          allowedConflictForms: ["Khác biệt lập trường", "Bất đồng trách nhiệm", "Lệch pha cảm xúc", "Áp lực đội nhóm"],
          forbiddenConflictForms: ["Nhân vật quần tượng bị công cụ hoá lâu dài", "Chỉ còn nhân vật chính độc diễn", "Mạng lưới quan hệ không có thay đổi"],
          conflictCeiling: "medium",
          resolutionStyle: "Hoàn thành sự tiến hoá quan hệ qua tương tác đội nhóm, trải nghiệm chung và những lựa chọn giữa các nhân vật.",
          chapterUnit: "Một chương đẩy một cột mốc tương tác tập thể hoặc một thay đổi quan hệ giữa một cặp nhân vật then chốt.",
          volumeReward: "Cuối tập cho kết cấu quần tượng vững hơn, hoặc cho đội nhóm / mạng lưới quan hệ bước vào giai đoạn mới.",
          mandatorySignals: ["Tương tác tập thể", "Quan hệ liên động", "Các nhân vật cùng nâng nhau lên"],
          antiSignals: ["Nhân vật chỉ nêu tên mà không làm gì", "Tuyến quần tượng đứt gãy thành độc diễn một người"],
        }),
      },
    ],
  },
  {
    id: "story_mode_growth_root",
    name: "Trưởng thành phiêu lưu",
    description: "Lấy lên cấp, thám hiểm, vượt ải và đột phá theo giai đoạn tạo thành động lực đọc tiếp chính.",
    template: "Người đọc cần liên tục cảm nhận được năng lực, nhận thức hoặc ranh giới thế giới của nhân vật đang mở rộng.",
    profile: buildProfile({
      coreDrive: "Tạo cảm giác tiến lên liên tục qua đường cong trưởng thành, tiến triển thám hiểm và đột phá theo giai đoạn.",
      readerReward: "Người đọc liên tục nhận được sự thoả mãn khi mạnh lên, mở khoá khu vực mới và đạt tới ngưỡng mới.",
      progressionUnits: ["Nhận mục tiêu", "Thử thách nâng cấp", "Phá vỡ bình cảnh", "Bước vào khu vực mới"],
      allowedConflictForms: ["Thử luyện", "Rủi ro khi thám hiểm", "Ngưỡng giai đoạn", "Cơn đau trưởng thành"],
      forbiddenConflictForms: ["Giậm chân tại chỗ không trưởng thành lâu dài", "Chỉ có chỉ số lên cấp mà trải nghiệm không thay đổi", "Tuyến thám hiểm vắng bóng lâu dài"],
      conflictCeiling: "high",
      resolutionStyle: "Phá cục qua tập luyện, thực hành, thám hiểm và đột phá theo giai đoạn.",
      chapterUnit: "Mỗi chương đẩy một động tác trưởng thành, một phát hiện khi thám hiểm hoặc một đoạn phản hồi khi vượt ải.",
      volumeReward: "Cuối tập cho nhân vật tới một giai đoạn cao hơn, hoặc mở ra một không gian phiêu lưu lớn hơn.",
      mandatorySignals: ["Cảm giác trưởng thành", "Cảm giác đột phá", "Thế giới mở rộng"],
      antiSignals: ["Lên cấp chỉ nói bằng miệng", "Tuyến phiêu lưu đứng máy"],
    }),
    children: [
      {
        id: "story_mode_growth_leveling",
        name: "Lên cấp trưởng thành",
        description: "Xây dựng khoái cảm đọc xoay quanh việc đột phá năng lực, nhận thức và ngưỡng giai đoạn của nhân vật.",
        template: "Lên cấp không chỉ viết kết quả, còn phải viết ngưỡng, cái giá và sự trả về.",
        profile: buildProfile({
          coreDrive: "Liên tục kéo người đọc đi tiếp qua đường cong trưởng thành cảm nhận được rõ ràng và những đột phá theo giai đoạn.",
          readerReward: "Người đọc liên tục thấy năng lực, địa vị hoặc tầng nhận thức được nâng lên thực chất.",
          progressionUnits: ["Tích luỹ điều kiện", "Bị chặn ở điểm nghẽn", "Hoàn thành đột phá", "Phô bày sự nâng lên"],
          allowedConflictForms: ["Bình cảnh", "Thử luyện", "Thiếu tài nguyên", "Cạnh tranh cùng tầng"],
          forbiddenConflictForms: ["Trưởng thành hoàn toàn bị lời dẫn lướt qua", "Đột phá không có cái giá và tích thế", "Lên cấp xong không có sự trả về nào"],
          conflictCeiling: "high",
          resolutionStyle: "Hoàn thành đột phá trưởng thành qua tích luỹ, tập luyện, thực chiến và khoảnh khắc bừng ngộ then chốt.",
          chapterUnit: "Một chương đẩy một lần tích luỹ, một lần thăm dò điểm nghẽn hoặc một lần trả về trưởng thành.",
          volumeReward: "Cuối tập hoàn thành một bước nhảy rõ ràng về cấp bậc, cảnh giới hoặc giai đoạn.",
          mandatorySignals: ["Ngưỡng trưởng thành", "Phản hồi đột phá", "Thay đổi theo giai đoạn"],
          antiSignals: ["Lên cấp như kể lể liệt kê", "Năng lực nâng lên không có hậu quả cốt truyện"],
        }),
      },
      {
        id: "story_mode_adventure_exploration",
        name: "Thám hiểm phiêu lưu",
        description: "Đẩy sự mới mẻ khi đọc bằng bản đồ mới, nền văn minh mới và rủi ro chưa biết.",
        template: "Thám hiểm phải mang lại thông tin mới, lựa chọn mới và hiểm nguy mới thật sự.",
        profile: buildProfile({
          coreDrive: "Giữ sự mới mẻ khi đọc qua việc liên tục bước vào khu vực chưa biết, tiếp xúc luật lệ mới và phát hiện bí mật mới.",
          readerReward: "Người đọc liên tục nhận được sự trả về của việc mở bản đồ, phát hiện và cảm giác chưa biết.",
          progressionUnits: ["Bước vào khu vực mới", "Phát hiện luật lệ mới", "Chạm trán rủi ro", "Mang về nhận thức mới"],
          allowedConflictForms: ["Đe doạ môi trường", "Luật lệ chưa biết", "Cạnh tranh thám hiểm", "Khác biệt văn minh"],
          forbiddenConflictForms: ["Bối cảnh chỉ là thay vỏ", "Thám hiểm không tạo ra thông tin mới", "Cứ ở lì một chỗ liên tục, không đẩy ranh giới thế giới"],
          conflictCeiling: "high",
          resolutionStyle: "Mở ra tầng thám hiểm sâu hơn qua quan sát, ứng phó, thích nghi và đột phá cục bộ.",
          chapterUnit: "Một chương đẩy một phát hiện mới, một lần ứng phó môi trường hoặc một lần thám hiểm bản đồ.",
          volumeReward: "Cuối tập mở ra tầng khu vực mới, cửa vào bí mật hoặc mục tiêu phiêu lưu mới.",
          mandatorySignals: ["Cảm giác chưa biết", "Cảm giác phát hiện", "Bản đồ mở rộng"],
          antiSignals: ["Thám hiểm chạy không tải", "Khu vực mới không có ý nghĩa tồn tại"],
        }),
      },
      {
        id: "story_mode_dungeon_challenge",
        name: "Vượt ải phó bản",
        description: "Tạo nhịp đẩy truyện mạnh bằng màn chơi theo giai đoạn, giải mã luật lệ và phản hồi khi thông quan.",
        template: "Phó bản không phải đánh quái lặp lại, phải viết rõ mục tiêu, cơ chế, rủi ro và phần thưởng thông quan.",
        profile: buildProfile({
          coreDrive: "Tạo khoái cảm đẩy truyện liên tục qua thử thách màn chơi theo giai đoạn và giải mã luật lệ.",
          readerReward: "Người đọc liên tục nhận được sự thoả mãn khi qua ải, phá cục và nhận phần thưởng.",
          progressionUnits: ["Vào phó bản", "Nhận diện cơ chế", "Phá điểm khó", "Kết toán thông quan"],
          allowedConflictForms: ["Cơ chế màn chơi", "Áp lực thời gian", "Phối hợp đội hình", "Giới hạn tài nguyên"],
          forbiddenConflictForms: ["Cơ chế phó bản hoàn toàn dựa vào cứng đầu chịu đòn", "Thông quan xong không có phản hồi phần thưởng", "Phó bản lặp lại đến mức không có gì mới"],
          conflictCeiling: "high",
          resolutionStyle: "Hoàn thành thông quan qua nhận diện luật lệ, phối hợp đội và thực thi then chốt.",
          chapterUnit: "Một chương đẩy một cột mốc màn chơi, một lần giải mã cơ chế hoặc một lần phản hồi thông quan.",
          volumeReward: "Cuối tập hoàn thành một hành trình phó bản trọn vẹn, nhận phần thưởng đáng kể hoặc cửa vào cấp cao hơn.",
          mandatorySignals: ["Cảm giác cơ chế", "Phản hồi khi vượt ải", "Trả về phần thưởng"],
          antiSignals: ["Các màn chơi đồng chất", "Chỉ còn chồng chất chỉ số không có cơ chế"],
        }),
      },
    ],
  },
];
