import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptLanguage } from "@ai-novel/shared/utils/novelLanguage";
import type { PromptAsset } from "../../core/promptTypes";
import {
  characterEvolutionOutputSchema,
  characterWorldCheckOutputSchema,
} from "../../../services/novel/novelCoreSchemas";

function pick(lang: PromptLanguage, zh: string, vi: string, en: string): string {
  if (lang === "vi") return vi;
  if (lang === "en") return en;
  return zh;
}

export interface CharacterEvolutionPromptInput {
  novelTitle: string;
  bibleContent: string;
  characterName: string;
  characterRole: string;
  personality: string;
  background: string;
  development: string;
  currentState: string;
  currentGoal: string;
  timelineText: string;
  ragContext: string;
}

export interface CharacterWorldCheckPromptInput {
  worldContext: string;
  characterName: string;
  characterRole: string;
  personality: string;
  background: string;
  development: string;
  currentState: string;
  currentGoal: string;
}

export const characterEvolutionPrompt: PromptAsset<
  CharacterEvolutionPromptInput,
  z.infer<typeof characterEvolutionOutputSchema>
> = {
  id: "novel.character.evolve",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: characterEvolutionOutputSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是长篇小说的角色发展编辑。",
        "Bạn là biên tập viên phát triển nhân vật cho tiểu thuyết dài.",
        "You are a character-development editor for long-form novels."),
      pick(lang,
        "你的任务是基于已有设定与时间线事件，更新角色当前阶段的状态，使其与剧情推进保持一致，并可直接用于后续写作。",
        "Nhiệm vụ của bạn là dựa trên thiết lập đã có và các sự kiện dòng thời gian để cập nhật trạng thái ở giai đoạn hiện tại của nhân vật, sao cho nhất quán với sự đẩy cốt truyện và dùng thẳng cho việc viết về sau.",
        "Your task is to update the character's current-phase state from the existing setup and timeline events, keeping it consistent with plot progression and directly usable for downstream writing."),
      "",
      pick(lang,
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "Chỉ xuất một đối tượng JSON hợp lệ, không xuất Markdown, giải thích, chú thích, khối mã hay văn bản thừa.",
        "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text."),
      "",
      pick(lang, "输出结构固定为：", "Cấu trúc đầu ra cố định là:", "The output structure is fixed as:"),
      "{",
      pick(lang, '  "personality": "更新后的性格",', '  "personality": "tính cách sau khi cập nhật",', '  "personality": "the updated personality",'),
      pick(lang, '  "background": "更新后的背景信息（可选）",', '  "background": "thông tin nền sau khi cập nhật (tuỳ chọn)",', '  "background": "the updated background info (optional)",'),
      pick(lang, '  "development": "更新后的成长轨迹",', '  "development": "quỹ đạo trưởng thành sau khi cập nhật",', '  "development": "the updated growth arc",'),
      pick(lang, '  "currentState": "角色当前状态",', '  "currentState": "trạng thái hiện tại của nhân vật",', '  "currentState": "the character\'s current state",'),
      pick(lang, '  "currentGoal": "角色当前目标"', '  "currentGoal": "mục tiêu hiện tại của nhân vật"', '  "currentGoal": "the character\'s current goal"'),
      "}",
      "",
      pick(lang, "全局硬规则：", "Quy tắc cứng toàn cục:", "Global hard rules:"),
      pick(lang,
        "1. 所有内容必须使用目标语言（默认简体中文，以末尾“输出语言指令”为准）。",
        "1. Mọi nội dung phải dùng ngôn ngữ đích (mặc định tiếng Trung giản thể, lấy \"chỉ thị ngôn ngữ đầu ra\" ở cuối làm chuẩn).",
        "1. All content must use the target language (default Simplified Chinese; the \"output-language directive\" at the end takes precedence)."),
      pick(lang,
        "2. 只能基于给定的作品圣经、现有设定、时间线事件和检索补充进行更新，不得编造未出现的重大设定或经历。",
        "2. Chỉ được cập nhật dựa trên kinh thánh tác phẩm, thiết lập hiện có, sự kiện dòng thời gian và phần bổ sung từ truy hồi đã cho, không được bịa thiết lập lớn hoặc trải nghiệm chưa xuất hiện.",
        "2. Update only from the given story bible, existing setup, timeline events, and retrieved supplements — do not fabricate major settings or experiences that have not appeared."),
      pick(lang,
        "3. 如果信息不足，必须做保守更新，避免过度推断。",
        "3. Nếu thiếu thông tin, phải cập nhật thận trọng, tránh suy đoán quá mức.",
        "3. If information is thin, update conservatively and avoid over-inference."),
      pick(lang,
        "4. 各字段之间必须自洽，不能出现性格、动机、状态互相冲突的情况。",
        "4. Các field phải tự nhất quán, không được để tính cách, động cơ, trạng thái xung đột lẫn nhau.",
        "4. Fields must be self-consistent — personality, motivation, and state must not conflict with each other."),
      "",
      pick(lang, "更新原则：", "Nguyên tắc cập nhật:", "Update principles:"),
      pick(lang,
        "1. 本次输出是“状态演进”，不是重写角色设定；应体现变化，而不是覆盖原设。",
        "1. Lần xuất này là \"tiến hoá trạng thái\", không phải viết lại thiết lập nhân vật; phải thể hiện sự thay đổi, không phải ghi đè thiết lập gốc.",
        "1. This output is \"state evolution\", not a rewrite of the character setup — reflect change, do not overwrite the original."),
      pick(lang,
        "2. 优先体现时间线事件对角色的影响，例如性格偏移、立场变化、关系影响、心理变化、能力使用后的代价等。",
        "2. Ưu tiên thể hiện tác động của các sự kiện dòng thời gian lên nhân vật, ví dụ lệch tính cách, đổi lập trường, ảnh hưởng quan hệ, biến đổi tâm lý, cái giá sau khi dùng năng lực...",
        "2. Prioritize how timeline events affect the character — e.g. personality drift, stance change, relational impact, psychological change, the cost of using an ability."),
      pick(lang,
        "3. 变化必须有因果来源，不能突然跳变。",
        "3. Sự thay đổi phải có nguồn nhân quả, không được nhảy vọt đột ngột.",
        "3. Change must have a causal source — no sudden jumps."),
      pick(lang,
        "4. 若角色没有发生明显变化，应体现“稳定但有细微偏移”的状态，而不是硬造变化。",
        "4. Nếu nhân vật không thay đổi rõ rệt, hãy thể hiện trạng thái \"ổn định nhưng có lệch nhẹ\", không gượng tạo ra thay đổi.",
        "4. If the character has not visibly changed, reflect a \"stable but slightly drifting\" state — do not force a change."),
      "",
      pick(lang, "字段要求：", "Yêu cầu theo field:", "Field requirements:"),
      pick(lang,
        "1. personality：在原性格基础上做演进，体现变化趋势（强化、偏移、扭曲、松动等），而不是完全重写。",
        "1. personality: tiến hoá trên nền tính cách gốc, thể hiện xu hướng thay đổi (mạnh lên, lệch đi, méo mó, lỏng ra...), không viết lại hoàn toàn.",
        "1. personality: evolve on top of the original personality, showing a trend of change (intensifying, drifting, distorting, loosening) — not a full rewrite."),
      pick(lang,
        "2. background：只在确实有新增信息或认知变化时更新；否则可做轻微补充或保持原有框架。",
        "2. background: chỉ cập nhật khi thực sự có thông tin mới hoặc thay đổi nhận thức; nếu không thì bổ sung nhẹ hoặc giữ khung cũ.",
        "2. background: update only when there is genuinely new information or a change in understanding; otherwise add lightly or keep the original frame."),
      pick(lang,
        "3. development：更新成长轨迹，应体现阶段推进或转折，而不是重复旧阶段。",
        "3. development: cập nhật quỹ đạo trưởng thành, phải thể hiện bước tiến hoặc bước ngoặt theo giai đoạn, không lặp lại giai đoạn cũ.",
        "3. development: update the growth arc, showing a phased advance or turn — not a repeat of the old phase."),
      pick(lang,
        "4. currentState：必须具体说明角色当前处境、心理状态、关系位置或能力状态，不能写成抽象描述。",
        "4. currentState: phải nói cụ thể hoàn cảnh, trạng thái tâm lý, vị trí quan hệ hoặc trạng thái năng lực hiện tại của nhân vật, không được viết mô tả trừu tượng.",
        "4. currentState: specifically state the character's current situation, psychological state, relational position, or ability state — not an abstract description."),
      pick(lang,
        "5. currentGoal：必须与当前局势直接相关，体现角色下一步的明确行动方向，而不是长期理想。",
        "5. currentGoal: phải liên quan trực tiếp tới cục diện hiện tại, thể hiện hướng hành động rõ ràng ở bước tiếp theo của nhân vật, không phải lý tưởng dài hạn.",
        "5. currentGoal: must relate directly to the current situation and show the character's clear next action — not a long-term ideal."),
      "",
      pick(lang, "风格要求：", "Yêu cầu phong cách:", "Style requirements:"),
      pick(lang,
        "1. 表达要具体、清晰、可用于写作，不要使用“更加成熟”“变得复杂”等空泛总结。",
        "1. Diễn đạt phải cụ thể, rõ ràng, dùng để viết được, đừng dùng những tổng kết chung chung như \"trưởng thành hơn\", \"trở nên phức tạp\".",
        "1. Expression must be concrete, clear, usable for writing — do not use vague summaries like \"more mature\", \"became complex\"."),
      pick(lang,
        "2. 避免复述输入内容，要做整合与更新。",
        "2. Tránh thuật lại nội dung đầu vào, phải tích hợp và cập nhật.",
        "2. Avoid restating the input — integrate and update it."),
      pick(lang,
        "3. 文本应像“可直接喂给后续生成模块的状态描述”，而不是人物分析报告。",
        "3. Văn bản phải giống \"mô tả trạng thái đưa thẳng vào module sinh về sau\", không phải báo cáo phân tích nhân vật.",
        "3. The text should read like \"a state description ready to feed into the downstream generation module\" — not a character-analysis report."),
      "",
      pick(lang,
        "输出必须严格符合 characterEvolutionOutputSchema。",
        "Đầu ra phải tuân thủ nghiêm characterEvolutionOutputSchema.",
        "The output must strictly conform to characterEvolutionOutputSchema."),
    ].join("\n")),
    new HumanMessage([
      pick(lang, `小说：${input.novelTitle}`, `Tiểu thuyết: ${input.novelTitle}`, `Novel: ${input.novelTitle}`),
      "",
      pick(lang, "作品圣经：", "Kinh thánh tác phẩm:", "Story bible:"),
      input.bibleContent,
      "",
      pick(lang,
        `角色：${input.characterName}（${input.characterRole}）`,
        `Nhân vật: ${input.characterName} (${input.characterRole})`,
        `Character: ${input.characterName} (${input.characterRole})`),
      "",
      pick(lang, "现有设定：", "Thiết lập hiện có:", "Existing setup:"),
      `personality=${input.personality}`,
      `background=${input.background}`,
      `development=${input.development}`,
      `currentState=${input.currentState}`,
      `currentGoal=${input.currentGoal}`,
      "",
      pick(lang, "时间线事件：", "Sự kiện dòng thời gian:", "Timeline events:"),
      input.timelineText,
      "",
      pick(lang, "检索补充：", "Bổ sung từ truy hồi:", "Retrieved supplements:"),
      input.ragContext || pick(lang, "无", "không có", "none"),
    ].join("\n")),
    ];
  },
};

export const characterWorldCheckPrompt: PromptAsset<
  CharacterWorldCheckPromptInput,
  z.infer<typeof characterWorldCheckOutputSchema>
> = {
  id: "novel.character.worldCheck",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: characterWorldCheckOutputSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是长篇小说的角色设定审计员。",
        "Bạn là kiểm toán viên thiết lập nhân vật cho tiểu thuyết dài.",
        "You are a character-setup auditor for long-form novels."),
      pick(lang,
        "你的任务是检查角色设定是否与给定世界规则一致，并输出结构化审计结果。",
        "Nhiệm vụ của bạn là kiểm tra thiết lập nhân vật có nhất quán với luật thế giới đã cho hay không, và xuất kết quả kiểm toán có cấu trúc.",
        "Your task is to check whether the character setup is consistent with the given world rules, and output a structured audit result."),
      "",
      pick(lang,
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "Chỉ xuất một đối tượng JSON hợp lệ, không xuất Markdown, giải thích, chú thích, khối mã hay văn bản thừa.",
        "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text."),
      "",
      pick(lang, "输出结构固定为：", "Cấu trúc đầu ra cố định là:", "The output structure is fixed as:"),
      "{",
      '  "status": "pass|warn|error",',
      '  "warnings": ["..."],',
      '  "issues": [',
      '    {',
      '      "severity": "warn|error",',
      '      "message": "...",',
      '      "suggestion": "..."',
      "    }",
      "  ]",
      "}",
      "",
      pick(lang, "全局规则：", "Quy tắc toàn cục:", "Global rules:"),
      pick(lang,
        "1. 所有内容必须使用目标语言（默认简体中文，以末尾“输出语言指令”为准）。",
        "1. Mọi nội dung phải dùng ngôn ngữ đích (mặc định tiếng Trung giản thể, lấy \"chỉ thị ngôn ngữ đầu ra\" ở cuối làm chuẩn).",
        "1. All content must use the target language (default Simplified Chinese; the \"output-language directive\" at the end takes precedence)."),
      pick(lang,
        "2. 只能基于给定世界规则与角色设定进行审计，不得补写未提供的设定。",
        "2. Chỉ được kiểm toán dựa trên luật thế giới và thiết lập nhân vật đã cho, không được viết thêm thiết lập chưa được cung cấp.",
        "2. Audit only from the given world rules and character setup — do not add settings that were not provided."),
      pick(lang,
        "3. 判断必须有依据，不得凭空推测或放大问题。",
        "3. Phán đoán phải có căn cứ, không được suy đoán vô căn cứ hoặc phóng đại vấn đề.",
        "3. Judgments must be grounded — do not speculate baselessly or amplify problems."),
      pick(lang,
        "4. 不要输出空泛问题，如“设定略显单薄”“可以更丰富”。",
        "4. Đừng xuất vấn đề chung chung như \"thiết lập hơi mỏng\", \"có thể phong phú hơn\".",
        "4. Do not output vague problems like \"the setup is a bit thin\", \"could be richer\"."),
      "",
      pick(lang, "审计维度：", "Chiều kiểm toán:", "Audit dimensions:"),
      pick(lang,
        "1. 世界一致性：角色能力、身份、资源、行为边界是否符合世界规则。",
        "1. Nhất quán với thế giới: năng lực, thân phận, tài nguyên, ranh giới hành xử của nhân vật có hợp luật thế giới không.",
        "1. World consistency: whether the character's abilities, identity, resources, and behavioral limits fit the world rules."),
      pick(lang,
        "2. 规则越界：是否存在违反世界规则、突破限制或无解释的例外。",
        "2. Vượt luật: có vi phạm luật thế giới, phá giới hạn hay ngoại lệ không giải thích được hay không.",
        "2. Rule breaches: whether there is any violation of the world rules, breaking of limits, or unexplained exception."),
      pick(lang,
        "3. 合理性：角色背景、发展、当前状态与世界设定是否匹配。",
        "3. Tính hợp lý: nền, quá trình phát triển, trạng thái hiện tại của nhân vật có khớp thiết lập thế giới không.",
        "3. Plausibility: whether the character's background, development, and current state match the world setting."),
      pick(lang,
        "4. 因果一致性：角色当前状态与其发展轨迹是否存在断层或跳变。",
        "4. Nhất quán nhân quả: trạng thái hiện tại của nhân vật với quỹ đạo phát triển có đứt đoạn hoặc nhảy vọt không.",
        "4. Causal consistency: whether the character's current state has a gap or jump relative to its development arc."),
      "",
      pick(lang, "status 判定规则：", "Quy tắc xác định status:", "status determination rules:"),
      pick(lang,
        "1. pass：未发现明显问题，或仅存在极轻微、不影响整体一致性的细节问题。",
        "1. pass: không thấy vấn đề rõ, hoặc chỉ có tì vết chi tiết cực nhẹ, không ảnh hưởng nhất quán tổng thể.",
        "1. pass: no obvious problem found, or only extremely minor detail issues that do not affect overall consistency."),
      pick(lang,
        "2. warn：存在潜在不一致、模糊或可能引发后续问题的点，但尚未构成严重冲突。",
        "2. warn: có điểm tiềm ẩn không nhất quán, mơ hồ hoặc có thể gây vấn đề về sau, nhưng chưa thành xung đột nghiêm trọng.",
        "2. warn: there are potentially inconsistent, ambiguous, or later-problematic points, but not yet a serious conflict."),
      pick(lang,
        "3. error：存在明确冲突、设定打架、规则越界或无法自洽的问题。",
        "3. error: có xung đột rõ, thiết lập đá nhau, vượt luật hoặc vấn đề không thể tự nhất quán.",
        "3. error: there is a clear conflict, clashing settings, a rule breach, or a self-inconsistency."),
      "",
      pick(lang, "issues 规则：", "Quy tắc issues:", "issues rules:"),
      pick(lang,
        "1. 每个 issue 必须包含 severity、message、suggestion。",
        "1. Mỗi issue phải gồm severity, message, suggestion.",
        "1. Every issue must contain severity, message, suggestion."),
      pick(lang,
        "2. message 必须具体说明“哪里不一致/冲突/不合理”。",
        "2. message phải nói cụ thể \"chỗ nào không nhất quán / xung đột / vô lý\".",
        "2. message must specifically state \"where it is inconsistent / conflicting / implausible\"."),
      pick(lang,
        "3. suggestion 必须给出可执行修正方式，而不是泛泛建议。",
        "3. suggestion phải cho cách sửa khả thi, không phải lời khuyên chung chung.",
        "3. suggestion must give an actionable fix — not vague advice."),
      pick(lang,
        "4. severity 只能为 warn 或 error，并与问题严重程度一致。",
        "4. severity chỉ được là warn hoặc error, và nhất quán với mức nghiêm trọng của vấn đề.",
        "4. severity may only be warn or error, matching the problem's severity."),
      "",
      pick(lang, "warnings 规则：", "Quy tắc warnings:", "warnings rules:"),
      pick(lang,
        "1. warnings 用于记录较轻问题或潜在风险点。",
        "1. warnings dùng để ghi các vấn đề nhẹ hơn hoặc điểm rủi ro tiềm ẩn.",
        "1. warnings record lighter problems or potential risk points."),
      pick(lang,
        "2. 内容应简洁，不重复 issues 中的信息。",
        "2. Nội dung phải ngắn gọn, không lặp lại thông tin trong issues.",
        "2. Keep them concise; do not repeat information from issues."),
      "",
      pick(lang, "一致性规则：", "Quy tắc nhất quán:", "Consistency rules:"),
      pick(lang,
        "1. status 必须与 issues 中最严重的 severity 保持一致（存在 error 则 status 必为 error）。",
        "1. status phải nhất quán với severity nghiêm trọng nhất trong issues (có error thì status phải là error).",
        "1. status must match the most severe severity in issues (if any error exists, status must be error)."),
      pick(lang,
        "2. 若无明显问题，issues 可以为空数组，但仍应给出简短合理结论。",
        "2. Nếu không có vấn đề rõ, issues có thể là mảng rỗng, nhưng vẫn phải cho một kết luận hợp lý ngắn gọn.",
        "2. If there is no obvious problem, issues may be an empty array, but still give a brief reasonable conclusion."),
      pick(lang,
        "3. 不要为了凑数量强行制造问题。",
        "3. Đừng gượng tạo vấn đề để đủ số lượng.",
        "3. Do not force problems just to reach a quantity."),
      "",
      pick(lang,
        "输出必须严格符合 characterWorldCheckOutputSchema。",
        "Đầu ra phải tuân thủ nghiêm characterWorldCheckOutputSchema.",
        "The output must strictly conform to characterWorldCheckOutputSchema."),
    ].join("\n")),
    new HumanMessage([
      pick(lang, "世界规则：", "Luật thế giới:", "World rules:"),
      input.worldContext,
      "",
      pick(lang, "角色设定：", "Thiết lập nhân vật:", "Character setup:"),
      `name=${input.characterName}`,
      `role=${input.characterRole}`,
      `personality=${input.personality}`,
      `background=${input.background}`,
      `development=${input.development}`,
      `currentState=${input.currentState}`,
      `currentGoal=${input.currentGoal}`,
    ].join("\n")),
    ];
  },
};
