import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import {
  DIRECTOR_CORRECTION_PRESETS,
  type DirectorCandidate,
  type DirectorCandidateBatch,
  type DirectorCorrectionPreset,
  type DirectorProjectContextInput,
} from "@ai-novel/shared/types/novelDirector";
import type { StoryMacroPlan } from "@ai-novel/shared/types/storyMacro";
import type { PromptLanguage } from "@ai-novel/shared/utils/novelLanguage";
import type { PromptAsset, PromptRenderContext } from "../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../core/renderContextBlocks";
import {
  buildDirectorBookContractContextBlocks,
  buildDirectorBlueprintContextBlocks,
  buildDirectorCandidateContextBlocks,
  formatProjectContext,
} from "./planningContextBlocks";
import {
  directorBookContractSchema,
  directorCandidateSchema,
  directorCandidateResponseSchema,
  directorPlanBlueprintSchema,
} from "../../../services/novel/director/runtime/novelDirectorSchemas";
import { NOVEL_PROMPT_BUDGETS } from "./promptBudgetProfiles";

export interface DirectorCandidatePromptInput {
  idea: string;
  context: DirectorProjectContextInput;
  count: number;
  batches: DirectorCandidateBatch[];
  presets: DirectorCorrectionPreset[];
  feedback?: string;
}

export interface DirectorCandidatePatchPromptInput {
  idea: string;
  context: DirectorProjectContextInput;
  candidate: DirectorCandidate;
  batches: DirectorCandidateBatch[];
  presets: DirectorCorrectionPreset[];
  feedback: string;
}

export interface DirectorBlueprintPromptInput {
  idea: string;
  context: DirectorProjectContextInput;
  candidate: DirectorCandidate;
  storyMacroPlan: StoryMacroPlan;
  targetChapterCount: number;
}

export interface DirectorBookContractPromptInput {
  idea: string;
  context: DirectorProjectContextInput;
  candidate: DirectorCandidate;
  storyMacroPlan: StoryMacroPlan | null;
  targetChapterCount: number;
}

function pick(lang: PromptLanguage, zh: string, vi: string, en: string): string {
  if (lang === "vi") return vi;
  if (lang === "en") return en;
  return zh;
}

function formatPresetHints(presets: DirectorCorrectionPreset[]): string {
  if (presets.length === 0) {
    return "none";
  }
  return presets
    .map((preset) => {
      const meta = DIRECTOR_CORRECTION_PRESETS.find((item) => item.value === preset);
      return meta ? `${meta.label}: ${meta.promptHint}` : preset;
    })
    .join("\n");
}

function formatCandidateDigest(candidate: DirectorCandidate, index: number): string {
  return [
    `option ${index + 1}: ${candidate.workingTitle}`,
    `logline: ${candidate.logline}`,
    `positioning: ${candidate.positioning}`,
    `selling point: ${candidate.sellingPoint}`,
    `core conflict: ${candidate.coreConflict}`,
    `protagonist path: ${candidate.protagonistPath}`,
    `hook strategy: ${candidate.hookStrategy}`,
    `progression loop: ${candidate.progressionLoop}`,
    `ending direction: ${candidate.endingDirection}`,
  ].join("\n");
}

function formatLatestBatchDigest(batches: DirectorCandidateBatch[]): string {
  const latestBatch = batches.at(-1);
  if (!latestBatch) {
    return "No previous batch.";
  }
  return [
    `${latestBatch.roundLabel}: ${latestBatch.refinementSummary?.trim() || "latest candidate round"}`,
    ...latestBatch.candidates.map((candidate, index) => formatCandidateDigest(candidate, index)),
  ].join("\n\n");
}

export const directorCandidatePrompt: PromptAsset<
  DirectorCandidatePromptInput,
  typeof directorCandidateResponseSchema._output
> = {
  id: "novel.director.candidates",
  version: "v2",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.directorCandidates,
    requiredGroups: ["idea_seed"],
    preferredGroups: ["project_context", "preset_hints", "freeform_feedback"],
    dropOrder: ["latest_batch"],
  },
  outputSchema: directorCandidateResponseSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
      new SystemMessage([
        pick(lang,
          "你是长篇小说书级方向规划导演，负责生成可以继续推进整本书规划的候选方向卡片。",
          "Bạn là đạo diễn lập hướng cấp độ toàn tiểu thuyết cho tác giả mới. Hãy tạo các thẻ hướng truyện cụ thể, có thể tiếp tục lập kế hoạch ngay.",
          "You are a book-level direction planner for new authors. Create concrete candidate direction cards that can immediately proceed to full-novel planning."),
        "",
        pick(lang, "【任务边界】", "[Ranh giới nhiệm vụ]", "[Task boundary]"),
        pick(lang,
          "当前阶段只生成书级候选卡片，不展开大纲、不进入章节、不进入场景细节、不补人物小传。",
          "Giai đoạn này chỉ sinh thẻ ứng viên cấp sách, không triển khai đề cương, không đi vào chương, không vào chi tiết cảnh, không viết tiểu sử nhân vật.",
          "This stage only produces book-level candidate cards — no outline expansion, no chapters, no scene detail, no character bios."),
        pick(lang,
          `必须精准输出 ${input.count} 套候选，数量不得多也不得少。`,
          `Phải xuất đúng ${input.count} bộ ứng viên, không nhiều hơn cũng không ít hơn.`,
          `Output exactly ${input.count} candidates — no more, no fewer.`),
        pick(lang,
          "只输出严格 JSON，不要输出 Markdown、解释、注释或额外文本。",
          "Chỉ xuất JSON hợp lệ nghiêm ngặt, không xuất Markdown, giải thích, chú thích hay văn bản thừa.",
          "Output only strict JSON — no Markdown, explanation, comments, or extra text."),
        "",
        pick(lang, "【字段要求】", "[Yêu cầu field]", "[Field requirements]"),
        pick(lang,
          "每个候选必须完整包含：workingTitle、logline、positioning、sellingPoint、coreConflict、protagonistPath、endingDirection、hookStrategy、progressionLoop、whyItFits、recommendedWritingPlatform、writingPlatformReason、toneKeywords、targetChapterCount。",
          "Mỗi ứng viên phải có đầy đủ: workingTitle, logline, positioning, sellingPoint, coreConflict, protagonistPath, endingDirection, hookStrategy, progressionLoop, whyItFits, recommendedWritingPlatform, writingPlatformReason, toneKeywords, targetChapterCount.",
          "Every candidate must fully include: workingTitle, logline, positioning, sellingPoint, coreConflict, protagonistPath, endingDirection, hookStrategy, progressionLoop, whyItFits, recommendedWritingPlatform, writingPlatformReason, toneKeywords, targetChapterCount."),
        pick(lang,
          "可选字段 titleOptions（最多 4 条）：为封面与点击向的书名备选。每条必须含 title、clickRate（35-99 的整数）、style。",
          "Field tuỳ chọn titleOptions (tối đa 4 mục): các tên sách dự phòng cho bìa và mục tiêu click. Mỗi mục phải có title, clickRate (số nguyên 35-99), style.",
          "Optional field titleOptions (up to 4 items): candidate cover/click-oriented titles. Each item must have title, clickRate (integer 35-99), style."),
        pick(lang,
          "style 只能是以下四个英文小写值之一：literary、conflict、suspense、high_concept（与标题工坊一致），不得使用中文标签、同义词或其它拼写。",
          "style chỉ được là một trong bốn giá trị tiếng Anh viết thường sau: literary, conflict, suspense, high_concept (khớp với xưởng tiêu đề), không được dùng nhãn tiếng Việt, từ đồng nghĩa hay cách viết khác.",
          "style must be exactly one of these four lowercase English values: literary, conflict, suspense, high_concept (matches the title workshop) — do not use localized labels, synonyms, or other spellings."),
        pick(lang,
          "angle、reason 可选；不要输出 titleOptions 以外的额外字段。",
          "angle, reason là tuỳ chọn; không xuất field nào ngoài titleOptions.",
          "angle and reason are optional; do not output any field beyond titleOptions."),
        pick(lang,
          "若不需要书名备选，可省略 titleOptions 或置为空数组。",
          "Nếu không cần tên sách dự phòng, có thể bỏ qua titleOptions hoặc để mảng rỗng.",
          "If no title alternatives are needed, omit titleOptions or set it to an empty array."),
        pick(lang,
          "不得缺漏字段，不得改名，不得新增 schema 之外字段。",
          "Không được thiếu field, không được đổi tên, không được thêm field ngoài schema.",
          "Do not omit fields, rename them, or add fields outside the schema."),
        "",
        pick(lang, "【核心要求】", "[Yêu cầu cốt lõi]", "[Core requirements]"),
        pick(lang,
          "1. workingTitle 必须是可读的暂定书名，适合封面展示，不要写成策划案口号、世界观概念短语或陈旧套壳名。",
          "1. workingTitle phải là tên sách tạm thời, đọc được, hợp để lên bìa, đừng viết thành khẩu hiệu đề án, cụm từ khái niệm thế giới quan hay tên sáo mòn.",
          "1. workingTitle must be a readable working title fit for a cover — not a pitch-deck slogan, a worldbuilding concept phrase, or a stale generic name."),
        pick(lang,
          "2. logline 必须清晰说明：这是谁，在什么处境下，面临什么核心冲突，会朝什么方向展开。",
          "2. logline phải nói rõ: đây là ai, trong hoàn cảnh nào, đối mặt xung đột cốt lõi gì, sẽ triển khai theo hướng nào.",
          "2. logline must clearly state: who this is, what situation they are in, what core conflict they face, and which direction it unfolds."),
        pick(lang,
          "3. positioning 必须说明这本书在题材、阅读满足或读者感知上的定位，而不是泛泛写“爽文”“成长文”。",
          "3. positioning phải nói rõ định vị của cuốn này về thể loại, sự thoả mãn khi đọc hoặc cảm nhận của độc giả, không được viết chung chung kiểu \"truyện sảng\", \"truyện trưởng thành\".",
          "3. positioning must state the book's positioning in terms of genre, reading satisfaction, or reader perception — not a generic label like \"power fantasy\" or \"coming-of-age\"."),
        pick(lang,
          "4. sellingPoint 必须突出这条方向最值得继续做整书规划的核心卖点。",
          "4. sellingPoint phải làm nổi bật điểm bán cốt lõi đáng để tiếp tục lập kế hoạch toàn sách nhất của hướng này.",
          "4. sellingPoint must foreground the single core selling point that most justifies carrying this direction into full-book planning."),
        pick(lang,
          "5. coreConflict 必须写清真正能支撑长篇连载的主要矛盾，不要只写一时事件。",
          "5. coreConflict phải viết rõ mâu thuẫn chính thực sự đủ sức nâng đỡ một bộ dài kỳ, không chỉ là một sự kiện nhất thời.",
          "5. coreConflict must state the main opposition that can genuinely sustain a long serial — not a one-off event."),
        pick(lang,
          "6. protagonistPath 必须体现主角长期变化方向，而不是静态人设描述。",
          "6. protagonistPath phải thể hiện hướng thay đổi lâu dài của nhân vật chính, không phải mô tả nhân thiết tĩnh.",
          "6. protagonistPath must show the protagonist's long-term direction of change, not a static character-sheet description."),
        pick(lang,
          "7. endingDirection 只给高层终局方向，不要写死详细结局。",
          "7. endingDirection chỉ cho hướng kết thúc ở tầm cao, đừng chốt cứng kết thúc chi tiết.",
          "7. endingDirection should give only a high-level ending direction — do not lock in a detailed ending."),
        pick(lang,
          "8. hookStrategy 必须说明前期如何抓住读者追读，而不是空泛写“制造悬念”。",
          "8. hookStrategy phải nói rõ giai đoạn đầu giữ chân người đọc bằng cách nào, không được viết chung chung \"tạo hồi hộp\".",
          "8. hookStrategy must explain concretely how the early chapters hook readers into reading on — not a vague \"build suspense\"."),
        pick(lang,
          "9. progressionLoop 必须说明这本书主要靠什么循环推进，比如升级、博弈、探索、关系裂变、任务兑现等。",
          "9. progressionLoop phải nói rõ cuốn này chủ yếu đẩy tới bằng vòng lặp nào, ví dụ: nâng cấp, đấu trí, thám hiểm, quan hệ rạn nứt, tất toán nhiệm vụ...",
          "9. progressionLoop must state the main loop that drives the book forward — e.g. power escalation, scheming, exploration, relationship fracture, mission payoff."),
        pick(lang,
          "10. whyItFits 必须说明这条候选为什么适合当前用户输入，而不是夸候选本身。",
          "10. whyItFits phải nói rõ vì sao ứng viên này hợp với đầu vào hiện tại của người dùng, không phải khen suông ứng viên.",
          "10. whyItFits must explain why this candidate fits the user's current input — not just praise the candidate itself."),
        pick(lang,
          "11. toneKeywords 必须是能帮助后续创作定调的关键词，避免空泛抒情词堆叠。",
          "11. toneKeywords phải là các từ khoá giúp định giọng cho sáng tác về sau, tránh chồng chất từ ngữ trữ tình chung chung.",
          "11. toneKeywords must be keywords that help downstream writing set its tone — avoid piling up vague, flowery words."),
        pick(lang,
          "12. recommendedWritingPlatform 只能是 fanqie_free、qidian_male、jinjiang_female。必须基于作品体验、受众、冲突引擎和推进方式判断，并在 writingPlatformReason 说明。若用户明确指定平台则采用指定值。不得用关键词或题材正则机械路由。",
          "12. recommendedWritingPlatform chỉ được là fanqie_free, qidian_male, jinjiang_female. Phải phán đoán dựa trên trải nghiệm tác phẩm, đối tượng đọc, động cơ xung đột và cách đẩy truyện, rồi giải thích trong writingPlatformReason. Nếu người dùng đã chỉ định nền tảng thì dùng đúng giá trị đó. Không được định tuyến máy móc theo từ khoá hay regex thể loại.",
          "12. recommendedWritingPlatform must be exactly one of fanqie_free, qidian_male, jinjiang_female. Judge it from the work's experience, audience, conflict engine, and progression style, and explain it in writingPlatformReason. If the user explicitly specified a platform, use that value. Do not mechanically route by keyword or genre regex."),
        pick(lang,
          "13. targetChapterCount 必须是合理的整书目标体量，与题材密度和推进方式相匹配。",
          "13. targetChapterCount phải là quy mô mục tiêu hợp lý cho toàn sách, khớp với mật độ thể loại và cách đẩy truyện.",
          "13. targetChapterCount must be a reasonable whole-book target scale that matches the genre's density and pacing style."),
        "",
        pick(lang, "【差异化要求】", "[Yêu cầu khác biệt hoá]", "[Differentiation requirements]"),
        pick(lang,
          "1. 候选之间必须有明显方向差异，不能只是换词、改名或轻微调整设定包装。",
          "1. Các ứng viên phải khác biệt rõ về hướng đi, không được chỉ đổi từ, đổi tên hay chỉnh nhẹ lớp vỏ thiết lập.",
          "1. Candidates must differ clearly in direction — not just swapped words, renamed elements, or a slightly repackaged setting."),
        pick(lang,
          "2. 差异优先体现在：主卖点、主冲突形态、主角路径、推进循环、情绪调性、结局方向。",
          "2. Sự khác biệt nên thể hiện trước hết ở: điểm bán chính, hình thái xung đột chính, lộ trình nhân vật chính, vòng lặp đẩy truyện, tông cảm xúc, hướng kết thúc.",
          "2. Differentiation should show up primarily in: main selling point, core-conflict shape, protagonist path, progression loop, emotional tone, ending direction."),
        pick(lang,
          "3. 不允许多套候选共享几乎相同的 hookStrategy 或 progressionLoop。",
          "3. Không được để nhiều ứng viên dùng chung gần như y hệt hookStrategy hay progressionLoop.",
          "3. Do not let multiple candidates share nearly identical hookStrategy or progressionLoop."),
        pick(lang,
          "4. 每个候选都必须是完整可继续规划的整书方向，而不是模糊概念或半成品。",
          "4. Mỗi ứng viên đều phải là một hướng toàn sách trọn vẹn, có thể tiếp tục lập kế hoạch, không phải khái niệm mơ hồ hay bán thành phẩm.",
          "4. Every candidate must be a complete, plannable whole-book direction — not a vague concept or a half-finished idea."),
        pick(lang,
          "5. 每套候选的 workingTitle 必须彼此不同，也不能只是增删标点、前后缀或替换少量近义词。",
          "5. workingTitle của mỗi ứng viên phải khác nhau, không được chỉ thêm bớt dấu câu, tiền/hậu tố hay thay vài từ đồng nghĩa.",
          "5. Each candidate's workingTitle must differ from the others — not just by punctuation, a prefix/suffix, or a few swapped synonyms."),
        "",
        pick(lang, "【深度校准】", "[Hiệu chỉnh độ sâu]", "[Depth calibration]"),
        pick(lang,
          "浅：logline 只写“一个少年获得神秘力量踏上冒险”。深：logline 写清谁、什么处境、核心冲突具体是什么两难、结局会朝哪个方向——例如“一名戒毒所护工发现自己能看见病人的‘下一次复发’，却救不了任何一个，因为每救一次都会让自己离清醒更远一步”。同样的具体度也要用在 coreConflict、hookStrategy 上：能不能让人复述出“谁、赌上什么、代价是什么”，复述不出就是太浅。",
          "Nông: logline chỉ viết \"một thiếu niên có sức mạnh bí ẩn lên đường phiêu lưu\". Sâu: logline nói rõ ai, hoàn cảnh gì, xung đột cốt lõi cụ thể là thế lưỡng nan nào, kết thúc sẽ theo hướng nào — ví dụ \"một hộ lý ở trung tâm cai nghiện phát hiện mình nhìn thấy được 'lần tái nghiện tiếp theo' của bệnh nhân, nhưng không cứu được ai cả, vì mỗi lần cứu lại khiến chính anh xa sự tỉnh táo thêm một bước\". Cùng mức độ cụ thể đó cũng phải áp cho coreConflict, hookStrategy: có thuật lại được \"ai, đánh cược cái gì, cái giá là gì\" không — không thuật lại được nghĩa là còn quá nông.",
          "Shallow: a logline that just says \"a teen gains mysterious power and goes on an adventure.\" Deep: a logline that states who, what situation, exactly what dilemma the core conflict is, and which direction the ending leans — e.g. \"a rehab-center aide discovers she can see a patient's 'next relapse' but cannot save any of them, because every save pushes her own sobriety one step further away.\" Apply that same specificity to coreConflict and hookStrategy: can someone restate \"who, what they're wagering, what the cost is\"? If not, it is still too shallow."),
        "",
        pick(lang, "【质量要求】", "[Yêu cầu chất lượng]", "[Quality requirements]"),
        pick(lang,
          "1. 优先生成对新手用户友好的清晰方向，不要故作复杂。",
          "1. Ưu tiên tạo hướng rõ ràng, thân thiện với người dùng mới, đừng cố tỏ ra phức tạp.",
          "1. Prioritize clear directions that are friendly to first-time users — do not force complexity for its own sake."),
        pick(lang,
          "2. 不要脱离上下文臆造庞杂设定块。",
          "2. Đừng thoát ly ngữ cảnh để bịa ra các khối thiết lập cồng kềnh.",
          "2. Do not invent bulky lore blocks disconnected from the context."),
        pick(lang,
          "3. 如果上一轮候选已有明显不合适方向，应主动避开重复。",
          "3. Nếu vòng ứng viên trước đã có hướng rõ ràng không hợp, phải chủ động tránh lặp lại.",
          "3. If the previous round already had a clearly unfit direction, proactively avoid repeating it."),
        pick(lang,
          "4. 信息不足时可以保守补全，但必须保证每个候选完整、可执行、可区分。",
          "4. Khi thiếu thông tin có thể bổ sung một cách thận trọng, nhưng phải đảm bảo mỗi ứng viên đều trọn vẹn, khả thi, phân biệt được.",
          "4. When information is thin, fill conservatively — but every candidate must still be complete, executable, and distinguishable."),
      ].join("\n")),
      new HumanMessage([
        pick(lang, "请基于以下上下文，生成书级候选方向。", "Hãy dựa vào ngữ cảnh dưới đây để tạo các hướng ứng viên cấp sách.", "Based on the context below, generate book-level candidate directions."),
        "",
        pick(lang, "【分层上下文】", "[Ngữ cảnh phân lớp]", "[Layered context]"),
        renderSelectedContextBlocks(context),
        "",
        pick(lang, "【项目上下文补充】", "[Bổ sung ngữ cảnh dự án]", "[Additional project context]"),
        formatProjectContext(input.context) || "none",
        "",
        pick(lang, "【上一轮候选】", "[Ứng viên vòng trước]", "[Previous round's candidates]"),
        formatLatestBatchDigest(input.batches),
        "",
        pick(lang, "【预设修正】", "[Chỉnh sửa theo mẫu]", "[Preset corrections]"),
        formatPresetHints(input.presets),
        "",
        pick(lang, "【自由修正意见】", "[Ý kiến chỉnh sửa tự do]", "[Freeform correction feedback]"),
        input.feedback?.trim() || "none",
        "",
        pick(lang, "【输出要求】", "[Yêu cầu đầu ra]", "[Output requirements]"),
        pick(lang, `- 必须精准输出 ${input.count} 套候选`, `- Phải xuất đúng ${input.count} bộ ứng viên`, `- Output exactly ${input.count} candidates`),
        pick(lang, "- 只输出严格 JSON", "- Chỉ xuất JSON hợp lệ nghiêm ngặt", "- Output only strict JSON"),
        pick(lang, "- 每套候选都必须可直接进入后续整书规划", "- Mỗi ứng viên đều phải có thể đi thẳng vào lập kế hoạch toàn sách tiếp theo", "- Every candidate must be able to proceed directly into full-book planning"),
        pick(lang, "- 优先保证候选差异度、可执行性与新手可理解性", "- Ưu tiên đảm bảo độ khác biệt, tính khả thi và dễ hiểu với người mới", "- Prioritize differentiation, executability, and beginner comprehensibility"),
      ].join("\n")),
    ];
  },
};

export const directorCandidatePatchPrompt: PromptAsset<
  DirectorCandidatePatchPromptInput,
  typeof directorCandidateSchema._output
> = {
  id: "novel.director.candidate_patch",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.directorCandidatePatch,
    requiredGroups: ["idea_seed"],
    preferredGroups: ["project_context", "preset_hints", "freeform_feedback", "latest_batch"],
    dropOrder: ["latest_batch"],
  },
  outputSchema: directorCandidateSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
      new SystemMessage([
        pick(lang,
          "你是长篇小说书级方向修正导演，负责根据反馈定向修正一套候选方向。",
          "Bạn là đạo diễn chỉnh sửa hướng truyện cấp độ toàn tiểu thuyết cho tác giả mới. Hãy chỉnh đúng một ứng viên theo phản hồi, không phát triển thành một hướng hoàn toàn khác.",
          "You refine book-level directions for new authors. Revise exactly one selected candidate according to the feedback without turning it into a completely different direction."),
        "",
        pick(lang, "【任务边界】", "[Ranh giới nhiệm vụ]", "[Task boundary]"),
        pick(lang,
          "本次只输出 1 套修正后的完整候选卡片。",
          "Lần này chỉ xuất 1 thẻ ứng viên đã sửa hoàn chỉnh.",
          "Output exactly 1 fully revised candidate card this time."),
        pick(lang,
          "必须保留原候选的核心方向，不要把它改成另一套完全不同的书。",
          "Phải giữ hướng cốt lõi của ứng viên gốc, không được biến nó thành một cuốn sách hoàn toàn khác.",
          "Preserve the core direction of the original candidate — do not turn it into a completely different book."),
        pick(lang,
          "只输出严格 JSON，不要输出 Markdown、解释、注释或额外文本。",
          "Chỉ xuất JSON hợp lệ nghiêm ngặt, không xuất Markdown, giải thích, chú thích hay văn bản thừa.",
          "Output only strict JSON — no Markdown, explanation, comments, or extra text."),
        "",
        pick(lang, "【修正原则】", "[Nguyên tắc chỉnh sửa]", "[Revision principles]"),
        pick(lang,
          "1. 优先响应用户反馈里真正不满意的偏差点，不要重做全部方向。",
          "1. Ưu tiên hồi đáp đúng điểm lệch mà người dùng thực sự không hài lòng trong phản hồi, đừng làm lại toàn bộ hướng đi.",
          "1. Prioritize responding to the specific points the user's feedback is actually unhappy with — do not redo the whole direction."),
        pick(lang,
          "2. 允许调整 workingTitle、logline、positioning、sellingPoint、coreConflict、protagonistPath、endingDirection、hookStrategy、progressionLoop、whyItFits、toneKeywords、targetChapterCount。",
          "2. Được phép điều chỉnh workingTitle, logline, positioning, sellingPoint, coreConflict, protagonistPath, endingDirection, hookStrategy, progressionLoop, whyItFits, toneKeywords, targetChapterCount.",
          "2. You may adjust workingTitle, logline, positioning, sellingPoint, coreConflict, protagonistPath, endingDirection, hookStrategy, progressionLoop, whyItFits, toneKeywords, targetChapterCount."),
        pick(lang,
          "3. 如果用户说“我就偏向这套，但有些地方不对”，要把这套修得更准，而不是重新另起炉灶。",
          "3. Nếu người dùng nói \"tôi thích hướng này, nhưng có vài chỗ chưa đúng\", hãy sửa cho hướng này chuẩn hơn, đừng làm lại từ đầu.",
          "3. If the user says \"I lean toward this one, but some parts are off\", refine this candidate more precisely — do not start over from scratch."),
        pick(lang,
          "4. 修正后仍然必须是完整、清晰、可继续推进整书规划的候选。",
          "4. Sau khi sửa vẫn phải là một ứng viên trọn vẹn, rõ ràng, có thể tiếp tục đẩy vào lập kế hoạch toàn sách.",
          "4. After revision it must still be a complete, clear candidate that can continue into full-book planning."),
        "",
        pick(lang, "【字段要求】", "[Yêu cầu field]", "[Field requirements]"),
        pick(lang,
          "输出字段必须完整包含：workingTitle、logline、positioning、sellingPoint、coreConflict、protagonistPath、endingDirection、hookStrategy、progressionLoop、whyItFits、recommendedWritingPlatform、writingPlatformReason、toneKeywords、targetChapterCount。",
          "Field đầu ra phải có đầy đủ: workingTitle, logline, positioning, sellingPoint, coreConflict, protagonistPath, endingDirection, hookStrategy, progressionLoop, whyItFits, recommendedWritingPlatform, writingPlatformReason, toneKeywords, targetChapterCount.",
          "Output fields must fully include: workingTitle, logline, positioning, sellingPoint, coreConflict, protagonistPath, endingDirection, hookStrategy, progressionLoop, whyItFits, recommendedWritingPlatform, writingPlatformReason, toneKeywords, targetChapterCount."),
        pick(lang,
          "可选字段 titleOptions（最多 4 条）：每条含 title、clickRate（35-99）、style；style 只能是 literary、conflict、suspense、high_concept 四者之一（英文小写）。",
          "Field tuỳ chọn titleOptions (tối đa 4 mục): mỗi mục có title, clickRate (35-99), style; style chỉ được là một trong bốn giá trị literary, conflict, suspense, high_concept (tiếng Anh viết thường).",
          "Optional field titleOptions (up to 4 items): each item has title, clickRate (35-99), style; style must be exactly one of literary, conflict, suspense, high_concept (lowercase English)."),
        pick(lang,
          "不需要书名备选时可省略 titleOptions 或置为空数组。",
          "Khi không cần tên sách dự phòng, có thể bỏ qua titleOptions hoặc để mảng rỗng.",
          "When no title alternatives are needed, omit titleOptions or set it to an empty array."),
        pick(lang,
          "不得缺漏字段，不得改名，不得新增 schema 之外字段。",
          "Không được thiếu field, không được đổi tên, không được thêm field ngoài schema.",
          "Do not omit fields, rename them, or add fields outside the schema."),
        "",
        pick(lang, "【质量要求】", "[Yêu cầu chất lượng]", "[Quality requirements]"),
        pick(lang,
          "1. 修正后要比原方案更贴近用户口味，而不是更抽象。",
          "1. Sau khi sửa phải sát gu người dùng hơn phương án gốc, không được trừu tượng hơn.",
          "1. After revision it must fit the user's taste better than the original — not become more abstract."),
        pick(lang,
          "2. 如果用户要求都市感、现实感、钩子更强、冲突更猛等，要落实到卖点、冲突和推进循环，而不只是改几个词。",
          "2. Nếu người dùng yêu cầu cảm giác đô thị, tính hiện thực, hook mạnh hơn, xung đột gắt hơn..., phải cụ thể hoá vào điểm bán, xung đột và vòng lặp đẩy truyện, không chỉ đổi vài từ.",
          "2. If the user asks for more urban feel, more realism, a stronger hook, sharper conflict, etc., ground it in the selling point, conflict, and progression loop — not just swap a few words."),
        pick(lang,
          "3. workingTitle 仍然必须适合中文网文封面展示，不要回退成概念短语或土味套壳名。",
          "3. workingTitle vẫn phải hợp để lên bìa truyện mạng, đừng lùi về thành cụm từ khái niệm hay tên sáo mòn quê mùa.",
          "3. workingTitle must still be fit for a web-novel cover — do not regress into a concept phrase or a generic, dated-sounding name."),
        pick(lang,
          "4. whyItFits 必须说明这次修正为什么更贴近用户反馈。",
          "4. whyItFits phải nói rõ vì sao lần sửa này sát với phản hồi của người dùng hơn.",
          "4. whyItFits must explain why this revision fits the user's feedback better."),
      ].join("\n")),
      new HumanMessage([
        pick(lang, "请基于以下上下文，对选中方案做定向修正。", "Hãy dựa vào ngữ cảnh dưới đây để chỉnh sửa đúng hướng phương án đã chọn.", "Based on the context below, make a targeted revision to the selected candidate."),
        "",
        pick(lang, "【分层上下文】", "[Ngữ cảnh phân lớp]", "[Layered context]"),
        renderSelectedContextBlocks(context),
        "",
        pick(lang, "【项目上下文补充】", "[Bổ sung ngữ cảnh dự án]", "[Additional project context]"),
        formatProjectContext(input.context) || "none",
        "",
        pick(lang, "【当前选中方案】", "[Phương án đang chọn]", "[Currently selected candidate]"),
        formatCandidateDigest(input.candidate, 0),
        "",
        pick(lang, "【上一轮候选】", "[Ứng viên vòng trước]", "[Previous round's candidates]"),
        formatLatestBatchDigest(input.batches),
        "",
        pick(lang, "【预设修正】", "[Chỉnh sửa theo mẫu]", "[Preset corrections]"),
        formatPresetHints(input.presets),
        "",
        pick(lang, "【用户反馈】", "[Phản hồi người dùng]", "[User feedback]"),
        input.feedback.trim(),
        "",
        pick(lang, "【输出要求】", "[Yêu cầu đầu ra]", "[Output requirements]"),
        pick(lang, "- 只输出 1 套修正后的完整候选 JSON", "- Chỉ xuất JSON của 1 ứng viên đã sửa hoàn chỉnh", "- Output only 1 fully revised candidate as JSON"),
        pick(lang, "- 保留原候选主方向，不要重做成完全不同的书", "- Giữ hướng chính của ứng viên gốc, đừng làm lại thành một cuốn sách hoàn toàn khác", "- Preserve the original candidate's main direction — do not remake it into a completely different book"),
        pick(lang, "- 优先修准用户指出的偏差点", "- Ưu tiên sửa đúng điểm lệch mà người dùng đã chỉ ra", "- Prioritize precisely fixing the deviations the user pointed out"),
      ].join("\n")),
    ];
  },
};

export const directorBlueprintPrompt: PromptAsset<
  DirectorBlueprintPromptInput,
  typeof directorPlanBlueprintSchema._output
> = {
  id: "novel.director.blueprint",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.directorBlueprint,
    requiredGroups: ["book_contract", "idea_seed", "macro_constraints"],
    preferredGroups: ["project_context"],
  },
  outputSchema: directorPlanBlueprintSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
      new SystemMessage([
        pick(lang,
          "你是长篇小说总规划导演，负责把确认后的书级方向展开成可执行蓝图。",
          "Bạn là đạo diễn lập kế hoạch tổng thể cho tiểu thuyết dài, chịu trách nhiệm triển khai hướng cấp sách đã chốt thành một bản thiết kế khả thi.",
          "You are the master-planning director for a long novel, responsible for expanding a confirmed book-level direction into an executable blueprint."),
        pick(lang,
          "你的任务不是写正文，也不是展开 scene，而是把整本书规划到 book -> arc -> chapter shell 这一层。",
          "Nhiệm vụ của bạn không phải viết chính văn, cũng không triển khai scene, mà là lập kế hoạch toàn sách tới tầng book -> arc -> chapter shell.",
          "Your task is not to write prose or expand scenes — it is to plan the whole book down to the book -> arc -> chapter-shell level."),
        "",
        pick(lang, "【任务边界】", "[Ranh giới nhiệm vụ]", "[Task boundary]"),
        pick(lang,
          "本阶段只生成 bookPlan 与 arcs，不进入 scene 级细化，不补人物百科，不补世界观百科。",
          "Giai đoạn này chỉ sinh bookPlan và arcs, không đi vào chi tiết cấp scene, không bổ sung bách khoa nhân vật, không bổ sung bách khoa thế giới quan.",
          "This stage only produces bookPlan and arcs — no scene-level detail, no character encyclopedia, no worldbuilding encyclopedia."),
        pick(lang,
          '输出必须是严格 JSON，结构只能是 {"bookPlan":{...},"arcs":[...]}。',
          'Đầu ra phải là JSON hợp lệ nghiêm ngặt, cấu trúc chỉ được là {"bookPlan":{...},"arcs":[...]}.',
          'Output must be strict JSON; the structure can only be {"bookPlan":{...},"arcs":[...]}.'),
        pick(lang,
          "不要输出 Markdown、解释、注释或额外文本。",
          "Không xuất Markdown, giải thích, chú thích hay văn bản thừa.",
          "Do not output Markdown, explanations, comments, or extra text."),
        "",
        pick(lang, "【chapter shell 字段要求】", "[Yêu cầu field chapter shell]", "[Chapter-shell field requirements]"),
        pick(lang,
          "每个 chapter 必须完整包含：title、objective、expectation、planRole、hookTarget、participants、reveals、riskNotes、mustAdvance、mustPreserve、scenes。",
          "Mỗi chapter phải có đầy đủ: title, objective, expectation, planRole, hookTarget, participants, reveals, riskNotes, mustAdvance, mustPreserve, scenes.",
          "Every chapter must fully include: title, objective, expectation, planRole, hookTarget, participants, reveals, riskNotes, mustAdvance, mustPreserve, scenes."),
        pick(lang,
          "其中 scenes 必须返回空数组，不允许在本阶段展开场景细节。",
          "Trong đó scenes phải trả về mảng rỗng, không được triển khai chi tiết cảnh ở giai đoạn này.",
          "scenes must be returned as an empty array — scene detail is not allowed at this stage."),
        pick(lang,
          "planRole 只能是：setup、progress、pressure、turn、payoff、cooldown。",
          "planRole chỉ được là: setup, progress, pressure, turn, payoff, cooldown.",
          "planRole must be exactly one of: setup, progress, pressure, turn, payoff, cooldown."),
        "",
        pick(lang, "【规划原则】", "[Nguyên tắc lập kế hoạch]", "[Planning principles]"),
        pick(lang,
          "1. 整体结构必须支持长篇连载，不要过早把后半本细化到场景级。",
          "1. Cấu trúc tổng thể phải hỗ trợ được truyện dài kỳ, đừng chi tiết hoá nửa sau xuống cấp scene quá sớm.",
          "1. The overall structure must support a long serial — do not detail the back half down to the scene level too early."),
        pick(lang,
          "2. bookPlan 负责整书级承诺、主线、阶段推进与总节奏控制。",
          "2. bookPlan chịu trách nhiệm cam kết cấp toàn sách, tuyến chính, đẩy tới theo giai đoạn và kiểm soát nhịp tổng thể.",
          "2. bookPlan is responsible for the whole-book promise, main line, staged progression, and overall pacing control."),
        pick(lang,
          "3. arcs 必须体现明确阶段功能，不能只是把章节机械分组。",
          "3. arcs phải thể hiện chức năng giai đoạn rõ ràng, không được chỉ là nhóm chương chia máy móc.",
          "3. arcs must express a clear staged function — not just a mechanical grouping of chapters."),
        pick(lang,
          "4. 每个 arc 都要说明自己为什么单独存在，它负责哪一段阶段性承诺、冲突升级或关系变化。",
          "4. Mỗi arc phải nói rõ vì sao nó tồn tại riêng, nó phụ trách cam kết giai đoạn nào, sự leo thang xung đột hay thay đổi quan hệ nào.",
          "4. Every arc must explain why it exists on its own — which staged promise, conflict escalation, or relationship change it owns."),
        pick(lang,
          "5. 每个 chapter shell 都要让新手用户一眼知道：这一章必须推进什么、必须保留什么、结尾要留下什么。",
          "5. Mỗi chapter shell phải để người dùng mới nhìn là hiểu ngay: chương này phải đẩy tới điều gì, phải giữ lại điều gì, cuối chương để lại điều gì.",
          "5. Every chapter shell must let a first-time user see at a glance: what this chapter must advance, what it must preserve, what it must leave at the end."),
        "",
        pick(lang, "【chapter shell 质量要求】", "[Yêu cầu chất lượng chapter shell]", "[Chapter-shell quality requirements]"),
        pick(lang,
          "1. title 必须像真实章节规划标题，能体现本章推进重点。",
          "1. title phải giống tiêu đề kế hoạch chương thực sự, thể hiện được trọng tâm đẩy tới của chương.",
          "1. title must read like a real chapter-planning title that conveys this chapter's main focus."),
        pick(lang,
          "2. objective 必须写清本章最核心的推进任务，不能写成泛泛总结。",
          "2. objective phải viết rõ nhiệm vụ đẩy tới cốt lõi nhất của chương, không được viết thành tóm tắt chung chung.",
          "2. objective must clearly state the chapter's single core advancing task — not a generic summary."),
        pick(lang,
          "3. expectation 必须说明读者在这一章主要期待看到什么兑现或变化。",
          "3. expectation phải nói rõ người đọc kỳ vọng thấy điều gì được tất toán hay thay đổi ở chương này.",
          "3. expectation must state what payoff or change the reader mainly expects to see in this chapter."),
        pick(lang,
          "4. hookTarget 必须说明本章结尾要把读者推向什么新的关注点或压力点。",
          "4. hookTarget phải nói rõ cuối chương sẽ đẩy người đọc tới điểm chú ý hay điểm áp lực mới nào.",
          "4. hookTarget must state what new point of interest or pressure the chapter's ending pushes the reader toward."),
        pick(lang,
          "5. participants 必须只包含本章实际关键参与者，不要泛滥堆角色。",
          "5. participants chỉ được gồm những người tham gia then chốt thực sự của chương, đừng nhồi nhét tràn lan nhân vật.",
          "5. participants must only include the chapter's actual key participants — do not pile on characters."),
        pick(lang,
          "6. reveals 必须写本章应揭出的关键信息或认知变化，没有则保守填写，不要硬造大反转。",
          "6. reveals phải viết thông tin then chốt hay thay đổi nhận thức cần hé lộ ở chương này, nếu không có thì điền thận trọng, đừng cố bịa cú lật lớn.",
          "6. reveals must state the key information or cognitive shift this chapter should expose; if there is none, fill it conservatively — do not force a big reversal."),
        pick(lang,
          "7. riskNotes 必须指出本章最容易写歪、写空或越界的风险。",
          "7. riskNotes phải chỉ ra rủi ro dễ bị viết lệch, viết rỗng hay vượt ranh giới nhất của chương này.",
          "7. riskNotes must point out this chapter's biggest risk of drifting off-course, going hollow, or overstepping boundaries."),
        pick(lang,
          "8. mustAdvance 和 mustPreserve 必须具体、短促、可执行，不能写空话。",
          "8. mustAdvance và mustPreserve phải cụ thể, ngắn gọn, khả thi, không được viết lời sáo rỗng.",
          "8. mustAdvance and mustPreserve must be concrete, terse, and executable — not empty talk."),
        "",
        pick(lang, "【节奏要求】", "[Yêu cầu nhịp độ]", "[Pacing requirements]"),
        pick(lang,
          "1. 前段 chapter shell 要快速建立局面、主卖点与追读钩子。",
          "1. Các chapter shell đầu phải nhanh chóng dựng cục diện, điểm bán chính và hook giữ chân người đọc.",
          "1. The early chapter shells must quickly establish the situation, the main selling point, and the read-on hook."),
        pick(lang,
          "2. 中段要体现升级、博弈、转向或代价抬升，避免平推。",
          "2. Đoạn giữa phải thể hiện leo thang, đấu trí, chuyển hướng hoặc cái giá tăng lên, tránh đẩy đều đều.",
          "2. The middle section must show escalation, scheming, a pivot, or a rising cost — avoid flat, even pacing."),
        pick(lang,
          "3. 后段要体现阶段性兑现、高潮集中与后续入口。",
          "3. Đoạn cuối phải thể hiện sự tất toán theo giai đoạn, cao trào tập trung và lối vào cho phần sau.",
          "3. The late section must show staged payoffs, a concentrated climax, and an entry point for what follows."),
        pick(lang,
          "4. 不同 arc 之间要有阶段差异，不能多个 arc 只是同义升级。",
          "4. Các arc phải có khác biệt theo giai đoạn, không được nhiều arc chỉ là leo thang đồng nghĩa với nhau.",
          "4. Different arcs must show staged differences — not multiple arcs that are all just synonymous escalations of each other."),
        "",
        pick(lang, "【禁止事项】", "[Điều cấm]", "[Prohibitions]"),
        pick(lang,
          "禁止生成新的核心设定块、人物小传或世界观百科。",
          "Cấm sinh thêm khối thiết lập cốt lõi mới, tiểu sử nhân vật hay bách khoa thế giới quan.",
          "Do not generate new core lore blocks, character bios, or a worldbuilding encyclopedia."),
        pick(lang, "禁止把 scenes 写出内容。", "Cấm viết nội dung vào scenes.", "Do not write any content into scenes."),
        pick(lang,
          "禁止用空泛词替代可执行规划，例如“增强张力”“推进剧情”。",
          "Cấm dùng từ ngữ chung chung thay cho kế hoạch khả thi, ví dụ \"tăng cường kịch tính\", \"đẩy cốt truyện\".",
          "Do not substitute vague words for an executable plan, e.g. \"increase tension\", \"advance the plot\"."),
        pick(lang,
          "禁止把每章写成同一种功能模板。",
          "Cấm viết mọi chương theo cùng một khuôn chức năng.",
          "Do not write every chapter to the same functional template."),
        "",
        pick(lang, "【生成原则】", "[Nguyên tắc sinh]", "[Generation principles]"),
        pick(lang,
          "信息不足时可以保守补全，但必须保证结构完整、阶段清晰、可继续细化。",
          "Khi thiếu thông tin có thể bổ sung một cách thận trọng, nhưng phải đảm bảo cấu trúc trọn vẹn, giai đoạn rõ ràng, có thể tiếp tục chi tiết hoá.",
          "When information is thin, fill conservatively — but the structure must stay complete, the stages clear, and it must remain fit for further refinement."),
      ].join("\n")),
      new HumanMessage([
        pick(lang, "请基于以下上下文，输出整书执行蓝图。", "Hãy dựa vào ngữ cảnh dưới đây để xuất bản thiết kế thực thi toàn sách.", "Based on the context below, output the whole-book execution blueprint."),
        "",
        pick(lang, "【分层上下文】", "[Ngữ cảnh phân lớp]", "[Layered context]"),
        renderSelectedContextBlocks(context),
        "",
        pick(lang, "【目标章节总数】", "[Tổng số chương mục tiêu]", "[Target total chapter count]"),
        String(input.targetChapterCount),
        "",
        pick(lang, "【输出要求】", "[Yêu cầu đầu ra]", "[Output requirements]"),
        pick(lang, "- 只输出严格 JSON", "- Chỉ xuất JSON hợp lệ nghiêm ngặt", "- Output only strict JSON"),
        pick(lang, '- 结构只能是 {"bookPlan":{...},"arcs":[...]}', '- Cấu trúc chỉ được là {"bookPlan":{...},"arcs":[...]}', '- The structure can only be {"bookPlan":{...},"arcs":[...]}'),
        pick(lang, "- 只规划到 chapter shell", "- Chỉ lập kế hoạch tới chapter shell", "- Only plan down to the chapter-shell level"),
        pick(lang, "- scenes 必须全部为空数组", "- scenes phải đều là mảng rỗng", "- scenes must all be empty arrays"),
        pick(lang, "- 优先保证长篇可连载性、阶段差异与新手可执行性", "- Ưu tiên đảm bảo tính khả thi dài kỳ, khác biệt theo giai đoạn và dễ thực thi với người mới", "- Prioritize long-serial viability, staged differentiation, and beginner executability"),
      ].join("\n")),
    ];
  },
};

export const directorBookContractPrompt: PromptAsset<
  DirectorBookContractPromptInput,
  typeof directorBookContractSchema._output
> = {
  id: "novel.director.book_contract",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.directorBookContract,
    requiredGroups: ["book_contract", "idea_seed"],
    preferredGroups: ["project_context", "macro_constraints"],
  },
  outputSchema: directorBookContractSchema,
  structuredOutputHint: {
    mode: "auto",
    note: (_input: DirectorBookContractPromptInput, context: PromptRenderContext) => pick(
      context.promptLanguage,
      "absoluteRedLines 必须输出 2 到 6 条，超过 6 条时先合并相近禁区再输出。",
      "absoluteRedLines phải xuất 2 đến 6 mục, nếu quá 6 mục thì gộp các điều kiêng kỵ gần nhau trước khi xuất.",
      "absoluteRedLines must output 2 to 6 items; if more than 6, merge similar red lines before output.",
    ),
    example: (_input: DirectorBookContractPromptInput, context: PromptRenderContext) => {
      const lang = context.promptLanguage;
      return {
        readingPromise: pick(lang, "示例：持续提供哪一种追读满足感。", "Ví dụ: liên tục mang lại kiểu thoả mãn nào khi đọc tiếp.", "Example: which kind of read-on satisfaction it keeps delivering."),
        protagonistFantasy: pick(lang, "示例：主角视角下最核心的代入爽点。", "Ví dụ: điểm sảng nhập vai cốt lõi nhất từ góc nhìn nhân vật chính.", "Example: the core immersive wish-fulfillment from the protagonist's viewpoint."),
        coreSellingPoint: pick(lang, "示例：整本书最不可替代的核心卖点。", "Ví dụ: điểm bán cốt lõi không thể thay thế của cả cuốn sách.", "Example: the whole book's single irreplaceable core selling point."),
        chapter3Payoff: pick(lang, "示例：前 3 章必须兑现的抓手。", "Ví dụ: điểm níu giữ phải tất toán trong 3 chương đầu.", "Example: the hook that must pay off within the first 3 chapters."),
        chapter10Payoff: pick(lang, "示例：第 10 章左右的阶段回报。", "Ví dụ: phần thưởng giai đoạn quanh chương 10.", "Example: the staged reward around chapter 10."),
        chapter30Payoff: pick(lang, "示例：第 30 章左右的中段承诺兑现。", "Ví dụ: tất toán cam kết đoạn giữa quanh chương 30.", "Example: the mid-book promise payoff around chapter 30."),
        escalationLadder: pick(lang, "示例：整本书的升级阶梯。", "Ví dụ: thang leo thang của cả cuốn sách.", "Example: the whole book's escalation ladder."),
        relationshipMainline: pick(lang, "示例：长期驱动推进的核心关系线。", "Ví dụ: tuyến quan hệ cốt lõi thúc đẩy lâu dài.", "Example: the core relationship line that drives long-term progression."),
        absoluteRedLines: lang === "vi"
          ? ["Ví dụ điều kiêng kỵ 1", "Ví dụ điều kiêng kỵ 2", "Ví dụ điều kiêng kỵ 3"]
          : lang === "en"
            ? ["Example red line 1", "Example red line 2", "Example red line 3"]
            : ["示例禁区 1", "示例禁区 2", "示例禁区 3"],
      };
    },
  },
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
      new SystemMessage([
        pick(lang,
          "你是长篇网文总导演，负责把已确认的书级方向收束成一本书的 Book Contract。",
          "Bạn là đạo diễn tổng của một bộ truyện mạng dài kỳ, chịu trách nhiệm gói hướng cấp sách đã chốt thành Book Contract của cuốn sách.",
          "You are the head director of a long web novel, responsible for distilling the confirmed book-level direction into the book's Book Contract."),
        pick(lang,
          "服务对象是不懂写作流程的新手用户。",
          "Đối tượng phục vụ là người dùng mới, không hiểu quy trình sáng tác.",
          "You serve first-time users who do not understand the writing pipeline."),
        pick(lang,
          "你的任务不是重写大纲，而是提炼这本书后续所有规划都必须服从的高层创作契约。",
          "Nhiệm vụ của bạn không phải viết lại đề cương, mà là chắt lọc ra khế ước sáng tác tầng cao mà mọi kế hoạch sau này của cuốn sách phải tuân theo.",
          "Your task is not to rewrite the outline — it is to distill the high-level creative contract that every later plan for this book must obey."),
        "",
        pick(lang, "【任务边界】", "[Ranh giới nhiệm vụ]", "[Task boundary]"),
        pick(lang,
          "只输出严格 JSON，不要输出解释文本、Markdown、注释或额外字段。",
          "Chỉ xuất JSON hợp lệ nghiêm ngặt, không xuất văn bản giải thích, Markdown, chú thích hay field thừa.",
          "Output only strict JSON — no explanatory text, Markdown, comments, or extra fields."),
        pick(lang,
          "必须输出字段：readingPromise、protagonistFantasy、coreSellingPoint、chapter3Payoff、chapter10Payoff、chapter30Payoff、escalationLadder、relationshipMainline、absoluteRedLines。",
          "Phải xuất các field: readingPromise, protagonistFantasy, coreSellingPoint, chapter3Payoff, chapter10Payoff, chapter30Payoff, escalationLadder, relationshipMainline, absoluteRedLines.",
          "You must output the fields: readingPromise, protagonistFantasy, coreSellingPoint, chapter3Payoff, chapter10Payoff, chapter30Payoff, escalationLadder, relationshipMainline, absoluteRedLines."),
        "",
        pick(lang, "【字段要求】", "[Yêu cầu field]", "[Field requirements]"),
        pick(lang,
          "1. readingPromise 必须写清这本书持续给读者什么阅读满足，说明读者为什么会追下去。",
          "1. readingPromise phải viết rõ cuốn này liên tục mang lại cho người đọc sự thoả mãn gì, giải thích vì sao người đọc sẽ theo dõi tiếp.",
          "1. readingPromise must state exactly what reading satisfaction this book keeps delivering, and why readers keep reading on."),
        pick(lang,
          "2. protagonistFantasy 必须写清主角视角下最核心的代入幻想或爽点承载，不要泛写成人设标签。",
          "2. protagonistFantasy phải viết rõ ảo tưởng nhập vai hoặc điểm sảng cốt lõi nhất từ góc nhìn nhân vật chính, đừng viết chung chung thành nhãn nhân thiết.",
          "2. protagonistFantasy must state the core wish-fulfillment or payoff carried from the protagonist's viewpoint — not a generic character-sheet label."),
        pick(lang,
          "3. coreSellingPoint 必须指出这本书最不可替代的主卖点，而不是多个卖点平均罗列。",
          "3. coreSellingPoint phải chỉ ra điểm bán chính không thể thay thế của cuốn này, không phải liệt kê đều nhiều điểm bán.",
          "3. coreSellingPoint must point out the book's single irreplaceable main selling point — not an even list of several selling points."),
        pick(lang,
          "4. chapter3Payoff、chapter10Payoff、chapter30Payoff 必须体现明确的连载兑现节奏，说明在对应阶段读者能拿到什么阶段性满足。",
          "4. chapter3Payoff, chapter10Payoff, chapter30Payoff phải thể hiện nhịp tất toán rõ ràng theo kỳ, nói rõ ở giai đoạn tương ứng người đọc nhận được thoả mãn giai đoạn nào.",
          "4. chapter3Payoff, chapter10Payoff, chapter30Payoff must show a clear serial payoff cadence, stating what staged satisfaction the reader gets at each point."),
        pick(lang,
          "5. escalationLadder 必须体现整书主要升级阶梯或压力抬升路径，而不是抽象写‘越来越难’。",
          "5. escalationLadder phải thể hiện thang leo thang chính hoặc lộ trình tăng áp lực của cả cuốn sách, không được viết trừu tượng kiểu 'ngày càng khó'.",
          "5. escalationLadder must show the book's main escalation ladder or rising-pressure path — not an abstract \"it gets harder over time\"."),
        pick(lang,
          "6. relationshipMainline 必须写清核心关系线如何驱动长期推进，不要只写人物关系现状。",
          "6. relationshipMainline phải viết rõ tuyến quan hệ cốt lõi thúc đẩy về lâu dài ra sao, đừng chỉ viết hiện trạng quan hệ nhân vật.",
          "6. relationshipMainline must state how the core relationship line drives long-term progression — not just the current state of a relationship."),
        pick(lang,
          "7. absoluteRedLines 必须是明确禁区，能防止故事写歪、卖点跑偏或角色失真。",
          "7. absoluteRedLines phải là các điều kiêng kỵ rõ ràng, ngăn được truyện viết lệch, điểm bán chệch hướng hay nhân vật mất chất.",
          "7. absoluteRedLines must be explicit red lines that prevent the story from drifting off-course, the selling point from straying, or characters losing their integrity."),
        "",
        pick(lang, "【核心原则】", "[Nguyên tắc cốt lõi]", "[Core principles]"),
        pick(lang,
          "1. Book Contract 必须足够短硬，能指导后续分卷、拆章、续写与审查。",
          "1. Book Contract phải đủ ngắn gọn và chắc, đủ sức chỉ đạo việc chia tập, tách chương, viết tiếp và soát xét về sau.",
          "1. The Book Contract must be short and firm enough to guide later volume splitting, chapter breakdown, continuation, and review."),
        pick(lang,
          "2. 它不是宣传文案，而是创作约束文件。",
          "2. Nó không phải văn án quảng cáo, mà là tài liệu ràng buộc sáng tác.",
          "2. It is not marketing copy — it is a creative-constraint document."),
        pick(lang,
          "3. 它必须同时服务前期抓力、中期续航、长期连载稳定性。",
          "3. Nó phải đồng thời phục vụ sức hút giai đoạn đầu, sức bền giai đoạn giữa và sự ổn định khi đăng dài kỳ.",
          "3. It must simultaneously serve early hook strength, mid-book endurance, and long-serial stability."),
        pick(lang,
          "4. 对新手用户要清晰，不能写成模糊抽象的文学评论。",
          "4. Phải rõ ràng với người dùng mới, không được viết thành lời bình văn học mơ hồ, trừu tượng.",
          "4. It must be clear to first-time users — not written as vague, abstract literary commentary."),
        "",
        pick(lang, "【质量要求】", "[Yêu cầu chất lượng]", "[Quality requirements]"),
        pick(lang,
          "1. chapter3Payoff 应偏向开书抓手与快速兑现。",
          "1. chapter3Payoff nên nghiêng về sức hút mở đầu và tất toán nhanh.",
          "1. chapter3Payoff should lean toward the opening hook and a fast payoff."),
        pick(lang,
          "2. chapter10Payoff 应体现中前段建立后的第一阶段回报或局面变化。",
          "2. chapter10Payoff nên thể hiện phần thưởng giai đoạn đầu hoặc thay đổi cục diện sau khi phần đầu-giữa đã được dựng xong.",
          "2. chapter10Payoff should reflect the first-stage reward or situation change after the early-mid setup is established."),
        pick(lang,
          "3. chapter30Payoff 应体现更稳定的中段承诺兑现或阶段性大跃迁。",
          "3. chapter30Payoff nên thể hiện sự tất toán cam kết đoạn giữa ổn định hơn hoặc một bước nhảy vọt theo giai đoạn.",
          "3. chapter30Payoff should reflect a steadier mid-book promise payoff or a staged major leap."),
        pick(lang,
          "4. escalationLadder 要能与题材、主卖点、成长逻辑相匹配。",
          "4. escalationLadder phải khớp với thể loại, điểm bán chính và logic trưởng thành.",
          "4. escalationLadder must match the genre, the main selling point, and the growth logic."),
        pick(lang,
          "5. absoluteRedLines 必须具体可执行，避免“不要崩”“保持一致”这类空话。",
          "5. absoluteRedLines phải cụ thể, khả thi, tránh lời sáo rỗng kiểu \"đừng để lệch\", \"giữ nhất quán\".",
          "5. absoluteRedLines must be concrete and actionable — avoid empty talk like \"don't break character\" or \"stay consistent\"."),
        "",
        pick(lang, "【生成原则】", "[Nguyên tắc sinh]", "[Generation principles]"),
        pick(lang,
          "信息不足时可以保守补全，但必须保证每个字段都能真实约束后续创作。",
          "Khi thiếu thông tin có thể bổ sung một cách thận trọng, nhưng phải đảm bảo mỗi field đều thực sự ràng buộc được sáng tác về sau.",
          "When information is thin, fill conservatively — but every field must genuinely constrain the downstream creative work."),
      ].join("\n")),
      new HumanMessage([
        pick(lang, "请基于以下上下文，输出这本书的 Book Contract。", "Hãy dựa vào ngữ cảnh dưới đây để xuất Book Contract của cuốn sách này.", "Based on the context below, output this book's Book Contract."),
        "",
        pick(lang, "【分层上下文】", "[Ngữ cảnh phân lớp]", "[Layered context]"),
        renderSelectedContextBlocks(context),
        "",
        pick(lang, "【目标章节总数】", "[Tổng số chương mục tiêu]", "[Target total chapter count]"),
        String(input.targetChapterCount),
        "",
        pick(lang, "【输出要求】", "[Yêu cầu đầu ra]", "[Output requirements]"),
        pick(lang, "- 只输出严格 JSON", "- Chỉ xuất JSON hợp lệ nghiêm ngặt", "- Output only strict JSON"),
        pick(lang, "- 必须完整输出所有指定字段", "- Phải xuất đầy đủ tất cả field đã chỉ định", "- Must fully output all specified fields"),
        pick(lang, "- 优先保证可约束性、可执行性与连载节奏指导价值", "- Ưu tiên đảm bảo tính ràng buộc, tính khả thi và giá trị chỉ đạo nhịp đăng dài kỳ", "- Prioritize constraint strength, executability, and serial-pacing guidance value"),
      ].join("\n")),
    ];
  },
};

export {
  buildDirectorBookContractContextBlocks,
  buildDirectorBlueprintContextBlocks,
  buildDirectorCandidateContextBlocks,
};
