import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptLanguage } from "@ai-novel/shared/utils/novelLanguage";
import type { PromptAsset } from "../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../core/renderContextBlocks";
import { fullAuditOutputSchema } from "../../../services/audit/auditSchemas";
import { chapterSummaryOutputSchema } from "../../../services/novel/chapterSummarySchemas";
import { NOVEL_PROMPT_BUDGETS } from "./promptBudgetProfiles";

function pick(lang: PromptLanguage, zh: string, vi: string, en: string): string {
  if (lang === "vi") return vi;
  if (lang === "en") return en;
  return zh;
}

export interface ChapterSummaryPromptInput {
  novelTitle: string;
  chapterOrder: number;
  chapterTitle: string;
  content: string;
}

export interface ChapterReviewPromptInput {
  novelTitle: string;
  chapterTitle: string;
  content: string;
  ragContext: string;
}

export interface ChapterRepairPromptInput {
  novelTitle: string;
  bibleContent: string;
  chapterTitle: string;
  chapterContent: string;
  issuesJson: string;
  ragContext: string;
  modeHint?: string;
}

export const chapterSummaryPrompt: PromptAsset<
  ChapterSummaryPromptInput,
  z.infer<typeof chapterSummaryOutputSchema>
> = {
  id: "novel.chapter.summary",
  version: "v1",
  taskType: "summary",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterSummary,
  },
  outputSchema: chapterSummaryOutputSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是中文网络小说章节摘要助手。",
        "Bạn là trợ lý tóm tắt chương cho tiểu thuyết mạng.",
        "You are a chapter-summarizing assistant for serialized web fiction."),
      pick(lang,
        "你的任务不是评价章节，也不是改写正文，而是基于当前章节内容提炼一个可用于记录、检索与回顾的章节摘要。",
        "Nhiệm vụ của bạn không phải đánh giá chương hay viết lại chính văn, mà là chắt lọc từ nội dung chương hiện tại thành một bản tóm tắt dùng để ghi lại, tra cứu và xem lại.",
        "Your task is not to evaluate the chapter or rewrite the prose, but to distill the current chapter into a summary usable for recording, retrieval, and review."),
      "",
      pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
      pick(lang,
        "只输出符合 schema 的严格 JSON。",
        "Chỉ xuất JSON nghiêm ngặt đúng schema.",
        "Output only strict JSON conforming to the schema."),
      pick(lang,
        "输出格式固定为：{\"summary\":\"...\",\"concreteFacts\":[{\"text\":\"...\",\"category\":\"...\"}]}。",
        "Định dạng đầu ra cố định là: {\"summary\":\"...\",\"concreteFacts\":[{\"text\":\"...\",\"category\":\"...\"}]}.",
        "The output format is fixed as: {\"summary\":\"...\",\"concreteFacts\":[{\"text\":\"...\",\"category\":\"...\"}]}."),
      pick(lang,
        "不要输出 Markdown、解释、注释、代码块或任何额外文本。",
        "Không xuất Markdown, giải thích, chú thích, khối mã hay bất kỳ văn bản thừa nào.",
        "Do not output Markdown, explanations, comments, code blocks, or any extra text."),
      "",
      pick(lang, "【摘要要求】", "【Yêu cầu tóm tắt】", "[Summary requirements]"),
      pick(lang,
        "1. summary 必须使用当前作品指定的输出语言，长度控制在 80-180 字。",
        "1. summary phải dùng ngôn ngữ đầu ra đã chỉ định của tác phẩm, độ dài trong khoảng 80-180 ký tự.",
        "1. summary must use the work's specified output language, kept to 80-180 characters."),
      pick(lang,
        "2. 摘要必须覆盖本章最关键的事件推进，而不是泛泛概述氛围。",
        "2. Tóm tắt phải phủ được diễn tiến sự kiện then chốt nhất của chương, không phải khái quát chung về bầu không khí.",
        "2. The summary must cover the chapter's most crucial event progression — not a vague overview of the mood."),
      pick(lang,
        "3. 摘要应尽量同时体现以下信息中的主要部分：关键事件、冲突推进、人物状态变化、本章结果或留下的悬念。",
        "3. Tóm tắt nên cố thể hiện các phần chính trong các thông tin sau: sự kiện then chốt, sự đẩy xung đột, thay đổi trạng thái nhân vật, kết quả của chương hoặc nút thắt để lại.",
        "3. The summary should try to reflect the main parts of: key events, conflict progression, character state changes, and the chapter's outcome or the suspense it leaves."),
      pick(lang,
        "4. 摘要必须基于正文实际内容提炼，不得臆造正文中不存在的发展。",
        "4. Tóm tắt phải chắt lọc từ nội dung chính văn thực tế, không được bịa diễn tiến không có trong chính văn.",
        "4. The summary must be distilled from the actual prose — do not invent developments not present in it."),
      pick(lang,
        "5. 摘要应写成自然可读的完整概述，不要写成要点列表或标签堆砌。",
        "5. Tóm tắt nên viết thành một bản khái quát trọn vẹn, dễ đọc, đừng viết thành danh sách gạch đầu dòng hay chồng chất nhãn.",
        "5. The summary should be a complete, naturally readable overview — not a bullet list or a pile of tags."),
      "",
      pick(lang,
        "【concreteFacts 抽取要求 — 至关重要，用于防止后续章节自相矛盾】",
        "【Yêu cầu trích concreteFacts — cực kỳ quan trọng, để ngăn các chương sau tự mâu thuẫn】",
        "[concreteFacts extraction — critical, to keep later chapters from contradicting this one]"),
      pick(lang,
        "concreteFacts 用于记录本章正文【即兴产生、且后续章节必须保持一致】的硬事实。请逐条抽取，每条不超过 40 字：",
        "concreteFacts dùng để ghi các sự thật cứng 【phát sinh ngẫu hứng trong chương này và các chương sau phải giữ nhất quán】. Trích từng mục, mỗi mục không quá 40 ký tự:",
        "concreteFacts records the hard facts that 【emerged improvised in this chapter and that later chapters must stay consistent with】. Extract them one by one, each at most 40 characters:"),
      pick(lang,
        "1. 主角（或关键角色）做出的承诺、约定、交易条款——必须带上具体的金额/数量/时间/地点/方式。",
        "1. Lời hứa, giao ước, điều khoản giao dịch mà nhân vật chính (hoặc nhân vật then chốt) đưa ra — phải kèm số tiền/số lượng/thời gian/địa điểm/cách thức cụ thể.",
        "1. Promises, agreements, or deal terms the protagonist (or a key character) makes — must include the specific amount/quantity/time/place/method."),
      pick(lang,
        "   例：‘与王家庄约定后天晚上私下放映一场电影，收3块辛苦费，不走厂里流程’。",
        "   Ví dụ: 'Hẹn với thôn Vương ngày kia chiếu lén một bộ phim, lấy 3 đồng công, không qua quy trình của xưởng'.",
        "   e.g. 'Agreed with Wang Village to privately screen a film the day after tomorrow, charging 3 yuan, not going through the factory's process'."),
      pick(lang,
        "2. 本章确立的事件性质——尤其是‘私下行为 vs 公开/官方行为’这类一旦定下不可更改的属性。",
        "2. Tính chất sự việc được xác lập trong chương — đặc biệt là thuộc tính kiểu 'hành vi riêng tư vs hành vi công khai/chính thức', một khi đã chốt thì không đổi.",
        "2. The nature of an event this chapter establishes — especially attributes like 'private act vs public/official act' that cannot change once set."),
      pick(lang,
        "   例：‘这次放映是私活，未走厂里加班审批’。",
        "   Ví dụ: 'Buổi chiếu này là việc riêng, không qua duyệt tăng ca của xưởng'.",
        "   e.g. 'This screening is a private job, not approved as factory overtime'."),
      pick(lang,
        "3. 关键数字、日期、场次、票据编号、人物身份等硬细节，后文不得漂移。",
        "3. Các chi tiết cứng như con số then chốt, ngày tháng, suất chiếu, số biên lai, thân phận nhân vật — về sau không được trôi lệch.",
        "3. Hard details like key numbers, dates, showings, receipt numbers, character identities — later text must not drift from them."),
      pick(lang,
        "4. category 取值：completed=本章已完成的过程性目标；revealed=本章已揭示的信息/秘密；state_changed=关系/状态/约定/交易的变化。",
        "4. Giá trị category: completed = mục tiêu tiến trình đã hoàn thành trong chương; revealed = thông tin/bí mật đã hé lộ trong chương; state_changed = thay đổi về quan hệ/trạng thái/giao ước/giao dịch.",
        "4. category values: completed = a process goal completed this chapter; revealed = information/secrets revealed this chapter; state_changed = a change in a relationship/state/agreement/deal."),
      pick(lang,
        "5. 只抽取正文真实写到的内容，不得臆造；本章若无明确硬事实，concreteFacts 可为空数组。",
        "5. Chỉ trích nội dung chính văn thực sự viết ra, không được bịa; nếu chương không có sự thật cứng rõ ràng thì concreteFacts có thể là mảng rỗng.",
        "5. Extract only what the prose actually states — do not invent; if the chapter has no clear hard facts, concreteFacts may be an empty array."),
      pick(lang,
        "6. 不要把抽象目标（如‘主角要翻身’）写进来，只记可被后文违背的【具体】事实。",
        "6. Đừng đưa các mục tiêu trừu tượng (như 'nhân vật chính muốn lật ngược thế cờ') vào đây, chỉ ghi các sự thật 【cụ thể】 mà văn sau có thể vi phạm.",
        "6. Do not put abstract goals (like 'the protagonist wants to turn things around') here — record only 【concrete】 facts that later text could violate."),
      "",
      pick(lang, "【质量要求】", "【Yêu cầu chất lượng】", "[Quality requirements]"),
      pick(lang,
        "1. 优先写‘本章发生了什么变化’，而不是背景信息重复。",
        "1. Ưu tiên viết 'chương này có thay đổi gì', không phải nhắc lại thông tin nền.",
        "1. Prioritize \"what changed this chapter\" over repeating background information."),
      pick(lang,
        "2. 不要照抄正文原句，要做压缩与重组。",
        "2. Đừng chép nguyên câu chính văn, phải nén và tái tổ chức.",
        "2. Do not copy sentences from the prose verbatim — compress and reorganize."),
      pick(lang,
        "3. 不要写成空泛句式，例如“剧情继续推进”“冲突进一步升级”。",
        "3. Đừng viết câu chung chung như \"cốt truyện tiếp tục đẩy tới\", \"xung đột leo thang thêm\".",
        "3. Do not write vague phrasing like \"the plot keeps advancing\", \"the conflict escalates further\"."),
      pick(lang,
        "4. 若本章结尾留下明确钩子，应在摘要末尾体现其结果或悬念方向。",
        "4. Nếu cuối chương để lại một móc câu rõ ràng, phần cuối tóm tắt phải thể hiện kết quả hoặc hướng nút thắt của nó.",
        "4. If the chapter ends on a clear hook, the end of the summary should reflect its outcome or the direction of the suspense."),
    ].join("\n")),
    new HumanMessage([
      pick(lang, `小说：${input.novelTitle}`, `Tiểu thuyết: ${input.novelTitle}`, `Novel: ${input.novelTitle}`),
      pick(lang,
        `章节：第 ${input.chapterOrder} 章 ${input.chapterTitle}`,
        `Chương: chương ${input.chapterOrder} ${input.chapterTitle}`,
        `Chapter: chapter ${input.chapterOrder} ${input.chapterTitle}`),
      "",
      pick(lang, "【正文】", "【Chính văn】", "[Prose]"),
      input.content,
      "",
      pick(lang, "请输出章节摘要 JSON。", "Hãy xuất JSON tóm tắt chương.", "Output the chapter-summary JSON."),
    ].join("\n")),
    ];
  },
};

export const chapterReviewPrompt: PromptAsset<
  ChapterReviewPromptInput,
  z.infer<typeof fullAuditOutputSchema>
> = {
  id: "novel.review.chapter",
  version: "v2",
  taskType: "critical_review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterReview,
    preferredGroups: [
      "chapter_mission",
      "reader_experience",
      "structure_obligations",
      "world_rules",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
    ],
  },
  outputSchema: fullAuditOutputSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      "repetition scoring: 0 means heavily repetitive, 100 means repetition is well controlled; higher is better.",
      pick(lang,
        "你是资深网络小说章节审校编辑。",
        "Bạn là biên tập viên soát chương kỳ cựu của tiểu thuyết mạng.",
        "You are a veteran chapter-review editor for serialized web fiction."),
      pick(lang,
        "你的任务不是重写章节，而是基于正文与给定上下文，对当前章节做结构化质量评估，并输出可供后续修文使用的审查结果。",
        "Nhiệm vụ của bạn không phải viết lại chương, mà là dựa trên chính văn và ngữ cảnh đã cho để đánh giá chất lượng chương hiện tại một cách có cấu trúc, và xuất kết quả soát dùng cho bước sửa văn sau.",
        "Your task is not to rewrite the chapter, but to produce a structured quality assessment of it from the prose and given context, and output a review result usable by the downstream repair step."),
      "",
      pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
      pick(lang, "只输出符合 schema 的严格 JSON。", "Chỉ xuất JSON nghiêm ngặt đúng schema.", "Output only strict JSON conforming to the schema."),
      pick(lang,
        "不要输出 Markdown、解释、注释、代码块或任何额外文本。",
        "Không xuất Markdown, giải thích, chú thích, khối mã hay bất kỳ văn bản thừa nào.",
        "Do not output Markdown, explanations, comments, code blocks, or any extra text."),
      pick(lang,
        "所有自然语言字段必须使用当前作品指定的输出语言；JSON key、枚举值和技术字段保持不变。",
        "Mọi field ngôn ngữ tự nhiên phải dùng ngôn ngữ đầu ra đã chỉ định của tác phẩm; JSON key, giá trị enum và field kỹ thuật giữ nguyên.",
        "All natural-language fields must use the work's specified output language; JSON keys, enum values, and technical fields stay unchanged."),
      pick(lang,
        "不能脑补未给出的前文、设定或隐藏剧情。",
        "Không được tự tưởng tượng ra phần trước, thiết lập hay cốt truyện ẩn không được cung cấp.",
        "Do not imagine prior text, settings, or hidden plot that were not provided."),
      "",
      pick(lang, "【评分要求】", "【Yêu cầu chấm điểm】", "[Scoring requirements]"),
      pick(lang,
        "score 必须完整包含：coherence、repetition、pacing、voice、engagement、overall。",
        "score phải gồm đủ: coherence, repetition, pacing, voice, engagement, overall.",
        "score must fully contain: coherence, repetition, pacing, voice, engagement, overall."),
      pick(lang,
        "每项评分都应基于正文实际表现，不得凭印象打分。",
        "Mỗi điểm phải dựa trên biểu hiện thực tế của chính văn, không chấm theo cảm tính.",
        "Each score must be based on the prose's actual performance — not on impression."),
      "",
      pick(lang, "【审查重点】", "【Trọng tâm soát】", "[Review focus]"),
      pick(lang,
        "1. coherence：事件衔接、人物行为、因果推进是否清楚稳定。",
        "1. coherence: sự nối kết sự kiện, hành vi nhân vật, sự đẩy nhân quả có rõ ràng ổn định không.",
        "1. coherence: whether event linkage, character behavior, and causal progression are clear and stable."),
      pick(lang,
        "2. repetition：是否存在信息重复、表达重复、动作重复或功能重复。",
        "2. repetition: có lặp thông tin, lặp diễn đạt, lặp hành động hay lặp chức năng không.",
        "2. repetition: whether there is repeated information, repeated phrasing, repeated action, or repeated function."),
      pick(lang,
        "3. pacing：节奏是否松散、失衡、过快跳跃或关键处压缩不足。",
        "3. pacing: nhịp có lỏng lẻo, mất cân bằng, nhảy quá nhanh hay nén không đủ ở chỗ then chốt không.",
        "3. pacing: whether it is slack, unbalanced, jumps too fast, or under-compresses at key points."),
      pick(lang,
        "4. voice：文风、叙述口吻、人物表达是否稳定且适配当前内容。",
        "4. voice: văn phong, giọng kể, cách thể hiện nhân vật có ổn định và hợp với nội dung hiện tại không.",
        "4. voice: whether the prose style, narrative tone, and character expression are stable and fit the current content."),
      pick(lang,
        "5. engagement：是否具有持续阅读动力，结尾钩子、冲突推进与信息揭示是否有效。",
        "5. engagement: có động lực đọc tiếp không, móc câu kết, sự đẩy xung đột và hé lộ thông tin có hiệu quả không.",
        "5. engagement: whether it sustains the drive to read on, and whether the ending hook, conflict progression, and information reveals are effective."),
      pick(lang,
        "6. overall：综合质量判断，应反映本章是否达到可发布或需重点修整的水平。",
        "6. overall: phán đoán chất lượng tổng hợp, phải phản ánh chương này đã đạt mức đăng được hay cần sửa trọng điểm.",
        "6. overall: an integrated quality judgment reflecting whether the chapter is publishable or needs significant repair."),
      "",
      pick(lang, "【issues 要求】", "【Yêu cầu issues】", "[issues requirements]"),
      pick(lang,
        "1. issues 必须只抓真正影响阅读与连载质量的问题，避免吹毛求疵式碎问题泛滥。",
        "1. issues chỉ được bắt các vấn đề thực sự ảnh hưởng đến trải nghiệm đọc và chất lượng đăng dài kỳ, tránh tràn lan các vấn đề vụn vặt bới lông tìm vết.",
        "1. issues must capture only problems that genuinely affect the reading experience and serialized quality — avoid a flood of nitpicks."),
      pick(lang,
        "2. 每条 issue 都必须具体，不能只写“节奏不好”“描写偏弱”“有点重复”这种空泛判断。",
        "2. Mỗi issue phải cụ thể, không được chỉ viết những phán đoán chung chung như \"nhịp không tốt\", \"miêu tả hơi yếu\", \"hơi lặp\".",
        "2. Every issue must be concrete — not vague judgments like \"pacing is off\", \"description is weak\", \"a bit repetitive\"."),
      pick(lang,
        "3. evidence 必须指向正文中的可观察现象，可以是某类段落问题、某种重复模式、某处逻辑断裂或某段失速现象。",
        "3. evidence phải chỉ tới hiện tượng quan sát được trong chính văn: một loại vấn đề đoạn văn, một kiểu lặp, một chỗ đứt gãy logic hoặc một đoạn hụt nhịp.",
        "3. evidence must point to an observable phenomenon in the prose: a class of paragraph problem, a repetition pattern, a logic break, or a stretch that stalls."),
      pick(lang,
        "4. fixSuggestion 必须可执行，应该说明‘如何修’，而不是只说‘加强张力’‘优化表达’。",
        "4. fixSuggestion phải khả thi, phải nói 'sửa thế nào', không chỉ nói 'tăng độ căng', 'tối ưu diễn đạt'.",
        "4. fixSuggestion must be actionable — state \"how to fix it\", not just \"add tension\", \"improve the wording\"."),
      "",
      pick(lang, "【上下文使用规则】", "【Quy tắc dùng ngữ cảnh】", "[Context-usage rules]"),
      pick(lang,
        "1. chapter_mission、structure_obligations、world_rules 只用于判断是否偏离任务或设定，不得拿来脑补正文未写出的内容。",
        "1. chapter_mission, structure_obligations, world_rules chỉ dùng để phán đoán có lệch nhiệm vụ hay thiết lập không, không được dùng để tưởng tượng nội dung chính văn chưa viết.",
        "1. chapter_mission, structure_obligations, and world_rules are only for judging whether the chapter deviates from its task or settings — not for imagining content the prose did not write."),
      pick(lang,
        "2. ragContext 仅作补充校验参考，优先以当前正文和分层上下文为准。",
        "2. ragContext chỉ là tham chiếu kiểm tra bổ sung, ưu tiên lấy chính văn hiện tại và ngữ cảnh phân tầng làm chuẩn.",
        "2. ragContext is only a supplementary verification reference — the current prose and layered context take precedence."),
      pick(lang,
        "3. 若某项上下文不足，允许保守判断，但不要凭空制造问题。",
        "3. Nếu một mục ngữ cảnh thiếu, cho phép phán đoán thận trọng, nhưng đừng bịa vấn đề từ hư không.",
        "3. If a piece of context is thin, a conservative judgment is allowed — but do not manufacture a problem out of nothing."),
      "",
      pick(lang, "【质量要求】", "【Yêu cầu chất lượng】", "[Quality requirements]"),
      pick(lang,
        "1. 重点关注：是否完成本章任务、是否有新推进、是否存在明显冗余、是否留下有效钩子。",
        "1. Tập trung vào: có hoàn thành nhiệm vụ chương không, có sự đẩy mới không, có dư thừa rõ rệt không, có để lại móc câu hiệu quả không.",
        "1. Focus on: whether the chapter's task is done, whether there is new progression, whether there is obvious redundancy, and whether it leaves an effective hook."),
      pick(lang,
        "2. 同类问题不要拆成多条近义 issue。",
        "2. Đừng tách vấn đề cùng loại thành nhiều issue gần nghĩa.",
        "2. Do not split same-kind problems into multiple near-synonymous issues."),
      pick(lang,
        "3. 审查结果应服务后续修文，既要指出问题，也要保留本章已经有效的部分。",
        "3. Kết quả soát phải phục vụ bước sửa văn sau: vừa chỉ ra vấn đề, vừa giữ lại các phần đã hiệu quả của chương.",
        "3. The review result should serve the downstream repair: point out problems and also note the parts of the chapter that already work."),
    ].join("\n")),
    new HumanMessage([
      pick(lang, `小说：${input.novelTitle}`, `Tiểu thuyết: ${input.novelTitle}`, `Novel: ${input.novelTitle}`),
      pick(lang, `章节：${input.chapterTitle}`, `Chương: ${input.chapterTitle}`, `Chapter: ${input.chapterTitle}`),
      "",
      pick(lang, "【分层上下文】", "【Ngữ cảnh phân tầng】", "[Layered context]"),
      renderSelectedContextBlocks(context),
      "",
      pick(lang, "【正文】", "【Chính văn】", "[Prose]"),
      input.content,
      "",
      pick(lang, "【检索补充】", "【Bổ sung từ truy hồi】", "[Retrieved supplements]"),
      input.ragContext || "none",
      "",
      pick(lang, "请输出章节审查 JSON。", "Hãy xuất JSON soát chương.", "Output the chapter-review JSON."),
    ].join("\n")),
    ];
  },
};

export const chapterRepairPrompt: PromptAsset<ChapterRepairPromptInput, string, string> = {
  id: "novel.review.repair",
  version: "v2",
  taskType: "repair",
  mode: "text",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterRepair,
    preferredGroups: [
      "repair_issues",
      "chapter_boundary",
      "chapter_mission",
      "reader_experience",
      "repair_boundaries",
      "world_rules",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
      "continuation_constraints",
    ],
  },
  slots: [
    {
      kind: "append" as const,
      key: "repair.customConstraints",
      label: "Custom repair constraints",
      description: "Extra constraints for this repair, injected as a context block. Leave empty to add nothing.",
      anchor: "repair_issues",
      default: "",
      maxLength: 2000,
      placeholderHint: "e.g. do not change dialogue; only compress repeated sentence patterns; do not introduce new information...",
    },
  ],
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是资深网络小说修文编辑。",
        "Bạn là biên tập viên sửa văn kỳ cựu của tiểu thuyết mạng.",
        "You are a veteran line editor for serialized web fiction."),
      pick(lang,
        "你的任务是根据问题清单与分层上下文，对当前章节进行最小必要修复，使其更符合任务要求、结构要求与阅读体验。",
        "Nhiệm vụ của bạn là dựa trên danh sách vấn đề và ngữ cảnh phân tầng để sửa tối thiểu cần thiết cho chương hiện tại, sao cho khớp hơn với yêu cầu nhiệm vụ, yêu cầu kết cấu và trải nghiệm đọc.",
        "Your task is to make the minimum necessary repairs to the current chapter, based on the issue list and layered context, so it better meets its task, structural, and reading-experience requirements."),
      "",
      pick(lang, "【任务边界】", "【Ranh giới nhiệm vụ】", "[Task boundary]"),
      pick(lang,
        "只输出修复后的完整章节正文，不要输出解释、提纲、注释或任何额外文本。",
        "Chỉ xuất toàn bộ chính văn chương sau khi sửa, không xuất giải thích, đề cương, chú thích hay bất kỳ văn bản thừa nào.",
        "Output only the complete repaired chapter prose — no explanations, outline, comments, or any extra text."),
      pick(lang,
        "修文以‘最小必要修改’为原则，不要无关重写，不要把原章整体推翻重来。",
        "Sửa văn theo nguyên tắc 'chỉnh sửa tối thiểu cần thiết', đừng viết lại chỗ không liên quan, đừng lật đổ cả chương gốc để làm lại.",
        "Repair by the principle of \"minimum necessary change\" — no unrelated rewriting, do not overturn the whole original chapter."),
      pick(lang,
        "不得引入新的核心角色、重大设定、主线转向或与上下文冲突的内容。",
        "Không được đưa vào nhân vật cốt lõi mới, thiết lập lớn mới, cú chuyển hướng tuyến chính hay nội dung xung đột với ngữ cảnh.",
        "Do not introduce new core characters, major settings, a mainline pivot, or content that conflicts with the context."),
      "",
      pick(lang, "【修复原则】", "【Nguyên tắc sửa】", "[Repair principles]"),
      pick(lang,
        "1. 优先修复 issuesJson 中明确指出的关键问题。",
        "1. Ưu tiên sửa các vấn đề then chốt được nêu rõ trong issuesJson.",
        "1. Prioritize the key problems explicitly named in issuesJson."),
      pick(lang,
        "2. 优先保证 chapter_mission、repair_boundaries、world_rules 的约束被满足。",
        "2. Ưu tiên đảm bảo các ràng buộc của chapter_mission, repair_boundaries, world_rules được thoả mãn.",
        "2. Prioritize satisfying the constraints of chapter_mission, repair_boundaries, and world_rules."),
      pick(lang,
        "2a. 同时保留 reader_experience 中已经兑现的读者价值，并定向补齐 promisedReward、主角主动性、关键转折、净变化或旧钩子承接缺口。",
        "2a. Đồng thời giữ lại giá trị người đọc đã được trả trong reader_experience, và bổ sung có định hướng các lỗ hổng: promisedReward, tính chủ động của nhân vật chính, bước ngoặt then chốt, thay đổi ròng hoặc việc nối tiếp móc câu cũ.",
        "2a. Also preserve the reader value already delivered in reader_experience, and targeted-fill any gaps in promisedReward, protagonist agency, a key turn, net change, or follow-through on an earlier hook."),
      pick(lang,
        "3. 保留原章已经有效的推进、情绪、细节与角色状态，不要把有用内容一起洗掉。",
        "3. Giữ lại sự đẩy, cảm xúc, chi tiết và trạng thái nhân vật đã hiệu quả của chương gốc, đừng gột luôn cả nội dung hữu ích.",
        "3. Keep the progression, emotion, detail, and character states that already work in the original chapter — do not wash away the useful content."),
      pick(lang,
        "4. 若多个问题冲突，优先修复影响主线推进、逻辑连贯和阅读节奏的问题。",
        "4. Nếu nhiều vấn đề xung đột nhau, ưu tiên sửa vấn đề ảnh hưởng đến sự đẩy tuyến chính, tính liền mạch logic và nhịp đọc.",
        "4. If multiple problems conflict, prioritize the ones affecting mainline progression, logical coherence, and reading rhythm."),
      "",
      pick(lang, "【具体要求】", "【Yêu cầu cụ thể】", "[Specific requirements]"),
      pick(lang,
        "1. 修复后章节必须仍然是自然可读的完整正文，而不是拼补痕迹明显的修改稿。",
        "1. Chương sau khi sửa phải vẫn là chính văn trọn vẹn, đọc tự nhiên, không phải bản sửa lộ rõ dấu vá.",
        "1. The repaired chapter must still be complete, naturally readable prose — not a draft with obvious patch marks."),
      pick(lang,
        "2. 必须尽量保留本章原有核心事件顺序，除非问题清单明确指出结构需要调整。",
        "2. Phải cố giữ thứ tự sự kiện cốt lõi vốn có của chương, trừ khi danh sách vấn đề nêu rõ kết cấu cần điều chỉnh.",
        "2. Keep the chapter's original core event order as far as possible, unless the issue list explicitly says the structure needs adjusting."),
      pick(lang,
        "3. 若存在重复、空转、失速问题，应通过压缩、合并、替换无效段落来修，不要只做表面润色。",
        "3. Nếu có vấn đề lặp, chạy không tải, hụt nhịp, hãy sửa bằng cách nén, gộp, thay các đoạn vô hiệu, đừng chỉ trau chuốt bề mặt.",
        "3. If there is repetition, spinning in place, or stalling, fix it by compressing, merging, or replacing ineffective paragraphs — not surface polish."),
      pick(lang,
        "4. 若存在逻辑、动机、衔接问题，应补足必要过桥与因果，而不是额外发明大设定。",
        "4. Nếu có vấn đề logic, động cơ, nối kết, hãy bổ sung cầu nối và nhân quả cần thiết, không phải phát minh thêm thiết lập lớn.",
        "4. If there is a logic, motivation, or linkage problem, fill in the necessary bridge and causality — do not invent extra major lore."),
      pick(lang,
        "5. 若存在钩子不足、结尾无力问题，应在不违背既有走向的前提下加强章末压力、悬念或决策点。",
        "5. Nếu có vấn đề móc câu yếu, kết chương hụt hơi, hãy tăng áp lực, nút thắt hoặc điểm quyết định ở cuối chương mà không đi ngược hướng đi đã có.",
        "5. If the hook is weak or the ending falls flat, strengthen the end-of-chapter pressure, suspense, or decision point without contradicting the established direction."),
      input.modeHint
        ? pick(lang,
          `6. 本次修复重点：${input.modeHint}`,
          `6. Trọng tâm sửa lần này: ${input.modeHint}`,
          `6. Focus of this repair: ${input.modeHint}`)
        : "",
      "",
      pick(lang, "【风格要求】", "【Yêu cầu phong cách】", "[Style requirements]"),
      pick(lang,
        "1. 保持与原章相近的叙述视角、语言风格与人物说话方式。",
        "1. Giữ ngôi kể, phong cách ngôn ngữ và cách nói của nhân vật gần với chương gốc.",
        "1. Keep the narrative POV, language style, and characters' way of speaking close to the original chapter."),
      pick(lang,
        "2. 不要把修文写成另一种风格的新章。",
        "2. Đừng biến bản sửa thành một chương mới với phong cách khác.",
        "2. Do not turn the repair into a new chapter in a different style."),
      pick(lang,
        "3. 控制 AI 味、总结味和说明味，优先用具体动作、对话、细节与局面变化完成修复。",
        "3. Kiểm soát \"vị AI\", giọng tổng kết và giọng thuyết minh, ưu tiên dùng hành động cụ thể, đối thoại, chi tiết và biến chuyển cục diện để hoàn thành việc sửa.",
        "3. Control AI flavor, summarizing tone, and explanatory tone — prefer concrete action, dialogue, detail, and situational change to complete the repair."),
      "",
      pick(lang, "【禁止事项】", "【Điều cấm】", "[Prohibitions]"),
      pick(lang,
        "禁止加入问题清单未要求的大幅扩写。",
        "Cấm thêm phần mở rộng lớn mà danh sách vấn đề không yêu cầu.",
        "Do not add large expansions the issue list did not request."),
      pick(lang,
        "禁止通过新增大事件掩盖原问题。",
        "Cấm thêm sự kiện lớn để che lấp vấn đề gốc.",
        "Do not add a big event to paper over the original problem."),
      pick(lang,
        "禁止输出‘修改说明’‘修复点如下’等额外内容。",
        "Cấm xuất các nội dung thừa như 'ghi chú sửa đổi', 'các điểm đã sửa như sau'.",
        "Do not output extras like \"change notes\" or \"repairs made:\"."),
    ].join("\n")),
    new HumanMessage([
      pick(lang, `小说：${input.novelTitle}`, `Tiểu thuyết: ${input.novelTitle}`, `Novel: ${input.novelTitle}`),
      pick(lang, `章节：${input.chapterTitle}`, `Chương: ${input.chapterTitle}`, `Chapter: ${input.chapterTitle}`),
      "",
      pick(lang, "【分层上下文】", "【Ngữ cảnh phân tầng】", "[Layered context]"),
      renderSelectedContextBlocks(context),
      "",
      pick(lang, "【作品圣经】", "【Kinh thánh tác phẩm】", "[Story bible]"),
      input.bibleContent || "none",
      "",
      pick(lang, "【当前正文】", "【Chính văn hiện tại】", "[Current prose]"),
      input.chapterContent,
      "",
      pick(lang, "【问题清单】", "【Danh sách vấn đề】", "[Issue list]"),
      input.issuesJson,
      "",
      pick(lang, "【检索补充】", "【Bổ sung từ truy hồi】", "[Retrieved supplements]"),
      input.ragContext || "none",
      "",
      pick(lang,
        "请直接输出修复后的完整章节正文。",
        "Hãy xuất trực tiếp toàn bộ chính văn chương sau khi sửa.",
        "Output the complete repaired chapter prose directly."),
    ].join("\n")),
    ];
  },
};
