import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type {
  StoryDecomposition,
  StoryExpansion,
  StoryMacroField,
  StoryMacroLocks,
} from "@ai-novel/shared/types/storyMacro";
import type { PromptLanguage } from "@ai-novel/shared/utils/novelLanguage";
import type { PromptAsset } from "../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../core/renderContextBlocks";
import { STORY_MACRO_RESPONSE_SCHEMA } from "../../../services/novel/storyMacro/storyMacroPlanSchema";
import { NOVEL_PROMPT_BUDGETS } from "./promptBudgetProfiles";

export interface StoryMacroDecompositionPromptInput {
  storyInput: string;
  projectContext: string;
}

export interface StoryMacroFieldRegenerationPromptInput {
  field: StoryMacroField;
  storyInput: string;
  expansion: StoryExpansion;
  decomposition: StoryDecomposition;
  constraints: string[];
  lockedFields: StoryMacroLocks;
  projectContext: string;
}

function pick(lang: PromptLanguage, zh: string, vi: string, en: string): string {
  if (lang === "vi") return vi;
  if (lang === "en") return en;
  return zh;
}

function buildExpansionAndDecompositionPrompt(
  lang: PromptLanguage,
  storyInput: string,
  projectContext = "",
): { system: string; user: string } {
  return {
    system: [
      pick(lang,
        "你是资深小说作者 + 剧情策划编辑。",
        "Bạn là một tác giả tiểu thuyết kỳ cựu kiêm biên tập viên hoạch định cốt truyện.",
        "You are a veteran novelist and story-development editor."),
      pick(lang,
        "你的任务不是润色用户想法，而是将其重构为一个具备持续叙事能力、可用于后续约束生成的「故事引擎原型」。",
        "Nhiệm vụ của bạn không phải trau chuốt ý tưởng của người dùng, mà là tái dựng nó thành một \"nguyên mẫu động cơ truyện\" có khả năng đẩy truyện dài hơi, dùng được để sinh ràng buộc cho các bước sau.",
        "Your task is not to polish the user's idea but to rebuild it into a \"story-engine prototype\" that can sustain a long narrative and serve as hard constraints for the downstream pipeline."),
      "",
      pick(lang, "任务目标：", "Mục tiêu nhiệm vụ:", "Goals:"),
      pick(lang,
        "1. 强化戏剧冲突，而不是平铺直叙地补全设定。",
        "1. Tăng cường xung đột kịch tính, không phải kể lể bổ sung thiết lập một cách phẳng lặng.",
        "1. Strengthen dramatic conflict, not flatly fill in worldbuilding."),
      pick(lang,
        "2. 构建故事能够长期推进的驱动力，而不是只做短篇式前提包装。",
        "2. Xây dựng động lực để câu chuyện đẩy tới về lâu dài, không chỉ đóng gói tiền đề kiểu truyện ngắn.",
        "2. Build the drive that lets the story advance long-term, not just a short-story-style premise wrapper."),
      pick(lang,
        "3. 优先处理人物处境、认知冲突、危机升级、关系压力、关键场面与叙事气质。",
        "3. Ưu tiên xử lý hoàn cảnh nhân vật, xung đột nhận thức, khủng hoảng leo thang, áp lực quan hệ, những cảnh then chốt và khí chất tự sự.",
        "3. Prioritize the protagonist's situation, cognitive conflict, escalating crisis, relational pressure, key setpieces, and narrative tone."),
      pick(lang,
        "4. 控制信息密度，避免无依据地扩展大量世界观设定。",
        "4. Kiểm soát mật độ thông tin, tránh mở rộng vô căn cứ một lượng lớn thiết lập thế giới quan.",
        "4. Control information density; do not baselessly expand large amounts of worldbuilding."),
      pick(lang,
        "5. 输出内容将作为后续创作流程的硬约束，必须稳定、明确、可执行。",
        "5. Nội dung đầu ra sẽ là ràng buộc cứng cho quy trình sáng tác về sau, phải ổn định, rõ ràng, khả thi.",
        "5. The output becomes a hard constraint for the downstream pipeline — it must be stable, explicit, and executable."),
      "",
      pick(lang, "阶段约束：", "Ràng buộc giai đoạn:", "Stage constraints:"),
      pick(lang,
        "1. 当前阶段位于角色创建之前，只允许使用抽象角色槽位，如：主角位、对立位、关系压力位、诱导位、观察位。",
        "1. Giai đoạn này ở trước bước tạo nhân vật, chỉ được dùng ô nhân vật trừu tượng, ví dụ: vai chính, vai đối lập, vai gây áp lực quan hệ, vai dẫn dụ, vai quan sát.",
        "1. This stage precedes character creation — use only abstract character slots, e.g. protagonist slot, antagonist slot, relational-pressure slot, tempter slot, observer slot."),
      pick(lang,
        "2. 禁止出现具体角色姓名、完整人物小传、固定角色名单。",
        "2. Cấm xuất hiện tên nhân vật cụ thể, tiểu sử nhân vật đầy đủ, danh sách nhân vật cố định.",
        "2. No specific character names, full character bios, or a fixed cast list."),
      pick(lang,
        "3. 禁止把角色系统提前做成人设表。",
        "3. Cấm dựng sẵn hệ thống nhân vật thành bảng nhân thiết.",
        "3. Do not turn the character system into a character sheet prematurely."),
      pick(lang,
        "4. 禁止为了制造复杂感而凭空新增大量组织、地理、历史、体系设定。",
        "4. Cấm bịa thêm một lượng lớn thiết lập về tổ chức, địa lý, lịch sử, hệ thống chỉ để tạo cảm giác phức tạp.",
        "4. Do not invent large amounts of organization/geography/history/system lore just to feel complex."),
      "",
      pick(lang, "你必须完成以下构建：", "Bạn phải hoàn thành các phần dựng sau:", "You must build the following:"),
      pick(lang,
        "1. 把主角困住，形成明确且无法轻易退出的处境。",
        "1. Đẩy nhân vật chính vào thế bị kẹt, tạo một hoàn cảnh rõ ràng và không thể dễ dàng rút lui.",
        "1. Trap the protagonist in a clear situation they cannot easily leave."),
      pick(lang,
        "2. 构建一个可以持续升级、反复变形、长期压迫主角的核心矛盾。",
        "2. Dựng một mâu thuẫn cốt lõi có thể leo thang liên tục, biến hình nhiều lần, đè ép nhân vật chính về lâu dài.",
        "2. Build a core conflict that can keep escalating, keep mutating, and pressure the protagonist over the long run."),
      pick(lang,
        "3. 设置一个能够持续牵引读者阅读的 mystery box，即：最关键但暂时无法完整知道的未知。",
        "3. Đặt một mystery box liên tục kéo người đọc đi tiếp, tức là: ẩn số then chốt nhất mà tạm thời chưa thể biết trọn vẹn.",
        "3. Set a mystery box that keeps pulling the reader forward — the most crucial unknown that cannot yet be fully known."),
      pick(lang,
        "4. 设计 2-3 个具有画面感、冲突性和后续可扩展性的高张力场面种子。",
        "4. Thiết kế 2-3 hạt giống cảnh cao trào có hình ảnh, có xung đột và có khả năng mở rộng về sau.",
        "4. Design 2-3 high-tension setpiece seeds that are vivid, conflict-laden, and expandable later."),
      pick(lang,
        "5. 明确叙事气质，让后续写作知道这本书应该怎么写，而不是只知道写什么。",
        "5. Xác định rõ khí chất tự sự, để bước viết về sau biết cuốn này nên viết thế nào, chứ không chỉ biết viết cái gì.",
        "5. Define the narrative tone so downstream writing knows how this book should be written, not just what to write."),
      "",
      pick(lang, "题材适配要求：", "Yêu cầu thích ứng theo thể loại:", "Genre-fit requirements:"),
      pick(lang,
        "1. 如果题材呈现克苏鲁 / 不可名状倾向，必须体现：认知崩塌、现实不可信、真相不可直视。",
        "1. Nếu thể loại nghiêng về Cthulhu / bất khả danh trạng, phải thể hiện: sụp đổ nhận thức, hiện thực không đáng tin, sự thật không thể nhìn thẳng.",
        "1. If the genre leans Lovecraftian / unnameable, express: cognitive collapse, an untrustworthy reality, a truth that cannot be looked at directly."),
      pick(lang,
        "2. 如果题材呈现悬疑 / 推理倾向，必须体现：信息揭示节奏、认知误导、真相分层推进。",
        "2. Nếu thể loại nghiêng về trinh thám / suy luận, phải thể hiện: nhịp hé lộ thông tin, sự dẫn dắt sai nhận thức, sự thật tiến triển theo tầng.",
        "2. If the genre leans mystery / deduction, express: a reveal cadence, cognitive misdirection, layered advancement of the truth."),
      pick(lang,
        "3. 如果题材呈现成长倾向，必须体现：阶段性认知变化、代价、认知纠偏与自我重构。",
        "3. Nếu thể loại nghiêng về trưởng thành, phải thể hiện: thay đổi nhận thức theo giai đoạn, cái giá, sự sửa lệch nhận thức và tái dựng bản thân.",
        "3. If the genre leans coming-of-age, express: phased cognitive shifts, costs, correction of misperception, and self-reconstruction."),
      "",
      pick(lang, "项目上下文使用规则：", "Quy tắc dùng ngữ cảnh dự án:", "Project-context rules:"),
      pick(lang,
        "1. 如果项目上下文包含“这本书会用到的世界设定”，必须优先使用其中已有的规则、组织、地点、冲突、边界与禁配。",
        "1. Nếu ngữ cảnh dự án có \"thiết lập thế giới cuốn này sẽ dùng\", phải ưu tiên dùng các luật lệ, tổ chức, địa điểm, xung đột, ranh giới và điều kiêng kỵ đã có trong đó.",
        "1. If the project context includes \"world settings this book will use\", prioritize its existing rules, organizations, places, conflicts, boundaries, and forbidden pairings."),
      pick(lang,
        "2. 不得越出这些边界随意扩写。",
        "2. Không được vượt ra ngoài các ranh giới đó để mở rộng tuỳ tiện.",
        "2. Do not expand beyond those boundaries arbitrarily."),
      pick(lang,
        "3. 如果故事想法与项目上下文存在明显冲突，必须在 issues 中标记 conflict。",
        "3. Nếu ý tưởng truyện xung đột rõ với ngữ cảnh dự án, phải đánh dấu conflict trong issues.",
        "3. If the story idea clearly conflicts with the project context, mark it as conflict in issues."),
      "",
      pick(lang, "生成原则：", "Nguyên tắc sinh:", "Generation principles:"),
      pick(lang,
        "1. 优先做“冲突重构”和“叙事驱动构建”，不要把重点放在设定说明。",
        "1. Ưu tiên \"tái dựng xung đột\" và \"xây dựng động lực tự sự\", không đặt trọng tâm vào giải thích thiết lập.",
        "1. Prioritize \"conflict reconstruction\" and \"building narrative drive\" — not exposition of settings."),
      pick(lang,
        "2. 所有字段都应服务于‘这本书为什么能一直写下去’。",
        "2. Mọi field đều phải phục vụ câu hỏi 'vì sao cuốn này có thể viết mãi'.",
        "2. Every field must serve the question 'why can this book keep being written'."),
      pick(lang,
        "3. expanded_premise 不是简介润色，而是强化后的故事前提。",
        "3. expanded_premise không phải trau chuốt phần giới thiệu, mà là tiền đề truyện đã được tăng cường.",
        "3. expanded_premise is not a polished blurb — it is a strengthened story premise."),
      pick(lang,
        "4. protagonist_core 不是人物介绍，而是主角被困结构 + 内在裂缝 + 可变化空间。",
        "4. protagonist_core không phải phần giới thiệu nhân vật, mà là kết cấu bị kẹt của nhân vật chính + vết nứt nội tâm + không gian có thể thay đổi.",
        "4. protagonist_core is not a character intro — it is the protagonist's trap structure + inner fracture + room to change."),
      pick(lang,
        "5. conflict_engine 必须回答：剧情为何能不断升级、变形、反转、继续推进。",
        "5. conflict_engine phải trả lời: vì sao cốt truyện có thể liên tục leo thang, biến hình, đảo chiều, đẩy tiếp.",
        "5. conflict_engine must answer: why the plot can keep escalating, mutating, reversing, and advancing."),
      pick(lang,
        "6. mystery_box 必须足够关键，且不能是无意义卖关子。",
        "6. mystery_box phải đủ then chốt, và không được là kiểu cố tình úp mở vô nghĩa.",
        "6. mystery_box must be genuinely crucial, not a meaningless tease."),
      pick(lang,
        "7. progression_loop 必须清晰体现：发现 -> 介入 -> 升级 -> 反噬/反转 -> 再发现 的循环逻辑。",
        "7. progression_loop phải thể hiện rõ vòng lặp: phát hiện -> can dự -> leo thang -> phản đòn/đảo chiều -> lại phát hiện.",
        "7. progression_loop must clearly show the loop: discover -> intervene -> escalate -> backlash/reversal -> discover again."),
      pick(lang,
        "8. constraints 必须是后续生成阶段可直接遵守的叙事规则，而不是空泛建议。",
        "8. constraints phải là các quy tắc tự sự mà bước sinh sau có thể tuân theo trực tiếp, không phải lời khuyên chung chung.",
        "8. constraints must be narrative rules the downstream steps can obey directly — not vague advice."),
      pick(lang,
        "9. mystery_layers（悬念分层树）：仅当上下文中的「流派模式约束」显示「反转/揭示密度」为 dense（高反转/高悬念，如进击的巨人式的多层真相）时才填写；把核心未知拆成 2-6 个分层条目，每层给出 question（读者此刻的疑问）、hidden_truth（只有作者知道的真相）、activates_arc（开始显形的大致卷/幕）、pays_off_arc（揭示兑现的大致卷/幕），需要时给出 reframes（此次揭示重构的旧信息）。层与层之间要能递进兑现，后一层应改写前一层的认知。其它题材一律输出空数组 []。",
        "9. mystery_layers (cây bí ẩn phân tầng): chỉ điền khi \"Ràng buộc Story Mode\" trong ngữ cảnh cho thấy \"Mật độ đảo chiều/hé lộ\" là dense (đảo chiều/hồi hộp cao, kiểu sự thật nhiều tầng như Attack on Titan); tách ẩn số cốt lõi thành 2-6 tầng, mỗi tầng cho question (câu hỏi người đọc lúc này), hidden_truth (sự thật chỉ tác giả biết), activates_arc (đại khái arc/hồi bắt đầu lộ diện), pays_off_arc (đại khái arc/hồi hé lộ tận thu), và khi cần thì reframes (thông tin cũ bị cú hé lộ này tái cấu trúc). Các tầng phải tận thu tăng tiến, tầng sau viết lại nhận thức của tầng trước. Các thể loại khác luôn xuất mảng rỗng [].",
        "9. mystery_layers (layered mystery tree): fill only when the \"Story-mode constraints\" in context show a \"Reversal / reveal density\" of dense (high-reversal / high-suspense, Attack-on-Titan-style layered truth); split the core unknown into 2-6 layers, each with question (the reader's question right now), hidden_truth (the truth only the author knows), activates_arc (roughly which arc/act it starts surfacing), pays_off_arc (roughly which arc/act it is revealed), and reframes where needed (earlier info this reveal recontextualizes). Layers must pay off progressively; each later layer rewrites the previous layer's understanding. For all other genres, always output an empty array []."),
      "",
      pick(lang, "具体性硬门槛（不满足则重写该字段，不要输出）：", "Cổng cụ thể bắt buộc (không đạt thì viết lại field đó, đừng xuất ra):", "Concreteness gates (if a field fails one, rewrite it before output):"),
      pick(lang,
        "1. mystery_box 必须写成读者能一句话复述的疑问句（“……到底是什么/为什么/是谁？”），而不是主题词或氛围词。禁止把“命运”“真相”“力量”“秘密”本身当作 mystery_box。",
        "1. mystery_box phải viết thành một câu hỏi mà người đọc thuật lại được trong một câu (\"...rốt cuộc là gì / vì sao / là ai?\"), không phải từ chủ đề hay từ tả không khí. Cấm lấy chính \"số phận\", \"sự thật\", \"sức mạnh\", \"bí mật\" làm mystery_box.",
        "1. mystery_box must be a question the reader can restate in one sentence (\"what/why/who exactly is...?\"), not a theme word or a mood word. Do not use \"fate\", \"the truth\", \"power\", \"a secret\" themselves as the mystery_box."),
      pick(lang,
        "2. expanded_premise 必须点名开局的引爆事件：谁、做了什么、在哪、造成什么无法撤回的后果。不能只写状态或设定。",
        "2. expanded_premise phải nêu tên biến cố châm ngòi ở phần mở đầu: ai, làm gì, ở đâu, gây ra hậu quả không thể rút lại nào. Không được chỉ viết trạng thái hay thiết lập.",
        "2. expanded_premise must name the opening's inciting incident: who, does what, where, and what irreversible consequence it causes. Not just a state or a setting."),
      pick(lang,
        "3. conflict_engine、core_conflict 的中心不能是抽象名词（“阶级矛盾”“正邪对立”）。必须写清相互冲突的两个具体利益/目标，以及为什么双方都无法退出。",
        "3. Trung tâm của conflict_engine, core_conflict không được là danh từ trừu tượng (\"mâu thuẫn giai cấp\", \"chính tà đối lập\"). Phải viết rõ hai lợi ích/mục tiêu cụ thể chọi nhau, và vì sao cả hai bên đều không thể rút lui.",
        "3. The core of conflict_engine / core_conflict must not be an abstract noun (\"class struggle\", \"good vs evil\"). State the two concrete clashing interests/goals and why neither side can walk away."),
      pick(lang,
        "4. major_payoffs 每一项都必须是一个具体的、可被后文违背或兑现的事件（“X 发现 Y 一直在骗他”），不能是情绪或成长描述（“主角变得更强”）。",
        "4. Mỗi mục major_payoffs phải là một sự kiện cụ thể, có thể bị văn sau vi phạm hoặc tận thu (\"X phát hiện Y đã lừa mình suốt\"), không được là mô tả cảm xúc hay trưởng thành (\"nhân vật chính mạnh hơn\").",
        "4. Every major_payoffs item must be a concrete event that later text can betray or deliver (\"X discovers Y has been lying all along\") — not an emotion or a growth statement (\"the protagonist gets stronger\")."),
      pick(lang,
        "5. mystery_layers 每层的 reframes 必须指名它推翻的是前面哪一条已知信息；无法指名的层不要输出。",
        "5. reframes của mỗi tầng mystery_layers phải chỉ tên nó lật đổ thông tin đã biết nào ở phía trước; tầng nào không chỉ tên được thì đừng xuất.",
        "5. Each mystery_layers layer's reframes must name which earlier known fact it overturns; do not output a layer that cannot name one."),
      "",
      pick(lang, "输出前的内部自检（不写进输出，只用于自我修正）：", "Tự kiểm nội bộ trước khi xuất (không viết vào đầu ra, chỉ để tự sửa):", "Internal self-check before output (not written into the output — only for self-correction):"),
      pick(lang,
        "逐字段检查：这句话换成任何一本同题材的书是否都成立？如果成立，说明太泛，改写到只适用于这一本书。检查 expanded_premise、conflict_engine、mystery_box、major_payoffs、setpiece_seeds 五项后再输出最终 JSON。",
        "Kiểm từng field: câu này đổi sang bất kỳ cuốn nào cùng thể loại có còn đúng không? Nếu còn đúng nghĩa là quá chung, viết lại cho chỉ đúng với riêng cuốn này. Kiểm expanded_premise, conflict_engine, mystery_box, major_payoffs, setpiece_seeds rồi mới xuất JSON cuối.",
        "Check each field: would this sentence still be true if pasted into any other book of the same genre? If yes, it is too generic — rewrite it so it only fits this book. Check expanded_premise, conflict_engine, mystery_box, major_payoffs, and setpiece_seeds, then output the final JSON."),
      pick(lang,
        "在 issues 中，除标记冲突/缺口外，还要列出你判断当前最弱、最套路的 1-3 个字段，type 用 missing_info，field 填该字段名，message 说明为什么弱以及应往哪个方向补。",
        "Trong issues, ngoài đánh dấu xung đột/lỗ hổng, còn phải liệt kê 1-3 field bạn cho là yếu nhất, sáo mòn nhất hiện tại, type dùng missing_info, field điền tên field đó, message nói vì sao yếu và nên bổ theo hướng nào.",
        "In issues, besides marking conflicts/gaps, also list the 1-3 fields you judge weakest / most formulaic right now: use type missing_info, put the field name in field, and in message explain why it is weak and which direction it should be strengthened."),
      "",
      pick(lang, "缺失与冲突处理：", "Xử lý thiếu thông tin và xung đột:", "Handling gaps and conflicts:"),
      pick(lang,
        "1. 如果信息不足，不要假装完整，不要硬编细节。",
        "1. Nếu thiếu thông tin, đừng giả vờ đầy đủ, đừng bịa chi tiết.",
        "1. If information is missing, do not fake completeness and do not hard-code details."),
      pick(lang,
        "2. 信息不足时，在 issues 中标记 missing_info。",
        "2. Khi thiếu thông tin, đánh dấu missing_info trong issues.",
        "2. When information is missing, mark missing_info in issues."),
      pick(lang,
        "3. 用户输入彼此冲突，或与项目上下文冲突时，在 issues 中标记 conflict。",
        "3. Khi đầu vào của người dùng mâu thuẫn với nhau, hoặc mâu thuẫn với ngữ cảnh dự án, đánh dấu conflict trong issues.",
        "3. When the user's inputs conflict with each other, or with the project context, mark conflict in issues."),
      pick(lang,
        "4. 即使存在问题，也仍要尽可能产出一个可用但克制的故事引擎原型。",
        "4. Dù có vấn đề, vẫn phải cố cho ra một nguyên mẫu động cơ truyện dùng được nhưng tiết chế.",
        "4. Even when there are problems, still produce a usable but restrained story-engine prototype."),
      "",
      pick(lang, "输出要求：", "Yêu cầu đầu ra:", "Output requirements:"),
      pick(lang,
        "1. 只输出严格合法的 JSON 对象。",
        "1. Chỉ xuất một đối tượng JSON hợp lệ nghiêm ngặt.",
        "1. Output only a strictly valid JSON object."),
      pick(lang,
        "2. 不要输出解释、备注、Markdown、代码块或任何额外文本。",
        "2. Không xuất lời giải thích, chú thích, Markdown, khối mã hay bất kỳ văn bản thừa nào.",
        "2. Do not output explanations, notes, Markdown, code blocks, or any extra text."),
      pick(lang,
        "3. 所有字段都必须填写；若无法完全确定，应给出最稳妥、最克制的结果，并在 issues 中说明。",
        "3. Mọi field đều phải điền; nếu không thể chắc chắn hoàn toàn, hãy cho kết quả an toàn nhất, tiết chế nhất, và giải thích trong issues.",
        "3. All fields must be filled; when not fully certain, give the safest, most restrained result and explain in issues."),
      "",
      pick(lang, "JSON 结构：", "Cấu trúc JSON:", "JSON structure:"),
      "{",
      '  "expansion": {',
      pick(lang,
        '    "expanded_premise": "强化冲突后的故事前提",',
        '    "expanded_premise": "tiền đề truyện sau khi tăng cường xung đột",',
        '    "expanded_premise": "the story premise after conflict has been strengthened",'),
      pick(lang,
        '    "protagonist_core": "主角被困的处境 + 内在裂缝 + 可变化空间",',
        '    "protagonist_core": "hoàn cảnh bị kẹt của nhân vật chính + vết nứt nội tâm + không gian có thể thay đổi",',
        '    "protagonist_core": "the protagonist\'s trapped situation + inner fracture + room to change",'),
      pick(lang,
        '    "conflict_engine": "驱动剧情持续推进并不断升级的核心机制",',
        '    "conflict_engine": "cơ chế cốt lõi đẩy cốt truyện tiến tới liên tục và không ngừng leo thang",',
        '    "conflict_engine": "the core mechanism that keeps the plot advancing and escalating",'),
      '    "conflict_layers": {',
      pick(lang,
        '      "external": "外部压迫/威胁",',
        '      "external": "sự đè ép / đe doạ từ bên ngoài",',
        '      "external": "external pressure / threat",'),
      pick(lang,
        '      "internal": "内在崩塌/欲望/恐惧",',
        '      "internal": "sự sụp đổ / ham muốn / nỗi sợ bên trong",',
        '      "internal": "inner collapse / desire / fear",'),
      pick(lang,
        '      "relational": "人与人之间的张力"',
        '      "relational": "sự căng giữa người với người"',
        '      "relational": "tension between people"'),
      "    },",
      pick(lang,
        '    "mystery_box": "读者持续想知道但暂时拿不到答案的核心未知",',
        '    "mystery_box": "ẩn số cốt lõi mà người đọc liên tục muốn biết nhưng tạm thời chưa có câu trả lời",',
        '    "mystery_box": "the core unknown the reader keeps wanting to know but cannot yet get an answer to",'),
      pick(lang,
        '    "mystery_layers": [{"question":"读者此刻想知道的问题","hidden_truth":"只有作者知道的真相","activates_arc":"开始显形的卷/幕","pays_off_arc":"揭示兑现的卷/幕","reframes":"被此次揭示重构的旧信息（可选）"}],',
        '    "mystery_layers": [{"question":"câu hỏi người đọc muốn biết lúc này","hidden_truth":"sự thật chỉ tác giả biết","activates_arc":"arc/hồi bắt đầu lộ diện","pays_off_arc":"arc/hồi hé lộ tận thu","reframes":"thông tin cũ bị cú hé lộ này tái cấu trúc (tuỳ chọn)"}],',
        '    "mystery_layers": [{"question":"the reader\'s question right now","hidden_truth":"the truth only the author knows","activates_arc":"the arc/act it starts surfacing","pays_off_arc":"the arc/act it is revealed","reframes":"earlier info this reveal recontextualizes (optional)"}],'),
      pick(lang,
        '    "emotional_line": "情绪推进逻辑",',
        '    "emotional_line": "logic đẩy cảm xúc",',
        '    "emotional_line": "the emotional-progression logic",'),
      pick(lang,
        '    "setpiece_seeds": ["高张力场面1", "高张力场面2"],',
        '    "setpiece_seeds": ["cảnh cao trào 1", "cảnh cao trào 2"],',
        '    "setpiece_seeds": ["high-tension setpiece 1", "high-tension setpiece 2"],'),
      pick(lang,
        '    "tone_reference": "叙事气质和写法方向"',
        '    "tone_reference": "khí chất tự sự và hướng cách viết"',
        '    "tone_reference": "the narrative tone and stylistic direction"'),
      "  },",
      '  "decomposition": {',
      pick(lang,
        '    "selling_point": "一句话卖点",',
        '    "selling_point": "điểm hấp dẫn trong một câu",',
        '    "selling_point": "the one-sentence selling point",'),
      pick(lang,
        '    "core_conflict": "长期不可调和的对立",',
        '    "core_conflict": "sự đối lập không thể hoà giải về lâu dài",',
        '    "core_conflict": "a long-term irreconcilable opposition",'),
      pick(lang,
        '    "main_hook": "带未知的主线问题",',
        '    "main_hook": "câu hỏi tuyến chính mang ẩn số",',
        '    "main_hook": "the mainline question carrying an unknown",'),
      pick(lang,
        '    "progression_loop": "故事如何发现 -> 升级 -> 反转地循环推进",',
        '    "progression_loop": "câu chuyện đẩy tới theo vòng lặp phát hiện -> leo thang -> đảo chiều ra sao",',
        '    "progression_loop": "how the story advances in a discover -> escalate -> reverse loop",'),
      pick(lang,
        '    "growth_path": "主角认知或状态如何阶段性变化",',
        '    "growth_path": "nhận thức hoặc trạng thái của nhân vật chính thay đổi theo giai đoạn ra sao",',
        '    "growth_path": "how the protagonist\'s perception or state changes in phases",'),
      pick(lang,
        '    "major_payoffs": ["爆点1", "爆点2"],',
        '    "major_payoffs": ["điểm bùng nổ 1", "điểm bùng nổ 2"],',
        '    "major_payoffs": ["payoff 1", "payoff 2"],'),
      pick(lang,
        '    "ending_flavor": "结局风格"',
        '    "ending_flavor": "phong vị kết thúc"',
        '    "ending_flavor": "the ending\'s flavor"'),
      "  },",
      pick(lang,
        '  "constraints": ["必须遵守的叙事规则1", "必须遵守的叙事规则2"],',
        '  "constraints": ["quy tắc tự sự bắt buộc tuân thủ 1", "quy tắc tự sự bắt buộc tuân thủ 2"],',
        '  "constraints": ["mandatory narrative rule 1", "mandatory narrative rule 2"],'),
      pick(lang,
        '  "issues": [{"type":"conflict|missing_info","field":"expanded_premise|protagonist_core|conflict_engine|conflict_layers|mystery_box|emotional_line|setpiece_seeds|tone_reference|selling_point|core_conflict|main_hook|progression_loop|growth_path|major_payoffs|ending_flavor|constraints|global","message":"说明"}]',
        '  "issues": [{"type":"conflict|missing_info","field":"expanded_premise|protagonist_core|conflict_engine|conflict_layers|mystery_box|emotional_line|setpiece_seeds|tone_reference|selling_point|core_conflict|main_hook|progression_loop|growth_path|major_payoffs|ending_flavor|constraints|global","message":"giải thích"}]',
        '  "issues": [{"type":"conflict|missing_info","field":"expanded_premise|protagonist_core|conflict_engine|conflict_layers|mystery_box|emotional_line|setpiece_seeds|tone_reference|selling_point|core_conflict|main_hook|progression_loop|growth_path|major_payoffs|ending_flavor|constraints|global","message":"explanation"}]'),
      "}",
    ].join("\n"),
    user: [
      projectContext
        ? pick(lang,
            `项目上下文：\n${projectContext}`,
            `Ngữ cảnh dự án:\n${projectContext}`,
            `Project context:\n${projectContext}`)
        : "",
      pick(lang,
        `故事想法：\n${storyInput}`,
        `Ý tưởng truyện:\n${storyInput}`,
        `Story idea:\n${storyInput}`),
    ].filter(Boolean).join("\n\n"),
  };
}

function buildFieldRegenerationPrompt(input: {
  lang: PromptLanguage;
  field: StoryMacroField;
  storyInput: string;
  expansion: StoryExpansion | null;
  decomposition: StoryDecomposition;
  constraints: string[];
  lockedFields: StoryMacroLocks;
  projectContext?: string;
}): { system: string; user: string } {
  const { lang } = input;
  const fieldFormat = input.field === "conflict_layers"
    ? "{\"value\":{\"external\":\"...\",\"internal\":\"...\",\"relational\":\"...\"}}"
    : (input.field === "major_payoffs" || input.field === "setpiece_seeds" || input.field === "constraints")
      ? "{\"value\":[\"...\"]}"
      : "{\"value\":\"...\"}";

  return {
    system: [
      pick(lang,
        "你是小说故事引擎字段重写助手。",
        "Bạn là trợ lý viết lại từng field của động cơ truyện tiểu thuyết.",
        "You are an assistant that rewrites a single field of a novel's story engine."),
      pick(lang,
        "你的任务是：仅重写一个指定字段，使其与现有故事引擎原型保持一致，并直接可替换原字段使用。",
        "Nhiệm vụ của bạn: chỉ viết lại một field được chỉ định, sao cho nhất quán với nguyên mẫu động cơ truyện hiện có và có thể dùng để thay thế trực tiếp field cũ.",
        "Your task: rewrite only one specified field so it stays consistent with the existing story-engine prototype and can directly replace the old field."),
      "",
      pick(lang, "硬性要求：", "Yêu cầu bắt buộc:", "Hard requirements:"),
      pick(lang,
        "1. 你只能重写目标字段，不能修改、补写、影射改动其他字段。",
        "1. Bạn chỉ được viết lại field mục tiêu, không được sửa, viết thêm hay ám chỉ thay đổi các field khác.",
        "1. You may only rewrite the target field — do not modify, extend, or implicitly change other fields."),
      pick(lang,
        "2. 其他字段一律视为硬上下文，只能参考，不能推翻。",
        "2. Các field khác đều coi là ngữ cảnh cứng, chỉ được tham khảo, không được lật lại.",
        "2. Treat all other fields as hard context — reference only, do not override."),
      pick(lang,
        "3. 当前阶段位于角色创建之前，只允许使用抽象角色槽位，如：主角位、对立位、关系压力位、诱导位、观察位。",
        "3. Giai đoạn này ở trước bước tạo nhân vật, chỉ được dùng ô nhân vật trừu tượng, ví dụ: vai chính, vai đối lập, vai gây áp lực quan hệ, vai dẫn dụ, vai quan sát.",
        "3. This stage precedes character creation — use only abstract character slots, e.g. protagonist slot, antagonist slot, relational-pressure slot, tempter slot, observer slot."),
      pick(lang,
        "4. 禁止输出具体角色姓名、详细人物小传、固定角色名单。",
        "4. Cấm xuất tên nhân vật cụ thể, tiểu sử nhân vật chi tiết, danh sách nhân vật cố định.",
        "4. No specific character names, detailed bios, or a fixed cast list."),
      pick(lang,
        "5. 如果项目上下文包含“这本书会用到的世界设定”，则重写结果必须严格服从其中已有规则、地点、组织、边界、禁配与冲突，不得越界扩写。",
        "5. Nếu ngữ cảnh dự án có \"thiết lập thế giới cuốn này sẽ dùng\", kết quả viết lại phải tuân thủ nghiêm các luật lệ, địa điểm, tổ chức, ranh giới, điều kiêng kỵ và xung đột đã có, không được mở rộng vượt ranh giới.",
        "5. If the project context includes \"world settings this book will use\", the rewrite must strictly obey its existing rules, places, organizations, boundaries, forbidden pairings, and conflicts — no out-of-bounds expansion."),
      pick(lang,
        "6. 必须遵守已有 constraints。",
        "6. Phải tuân thủ các constraints đã có.",
        "6. You must obey the existing constraints."),
      pick(lang,
        "7. 必须尊重 lockedFields 所代表的既定方向，不得通过重写目标字段去间接破坏已锁定字段的成立基础。",
        "7. Phải tôn trọng hướng đã chốt mà lockedFields đại diện, không được qua việc viết lại field mục tiêu để gián tiếp phá vỡ nền tảng của các field đã khoá.",
        "7. Respect the fixed direction that lockedFields represents — do not use the rewrite to indirectly undermine the basis of any locked field."),
      "",
      pick(lang, "重写原则：", "Nguyên tắc viết lại:", "Rewrite principles:"),
      pick(lang,
        "1. 重写不是换一种说法重复原文，而是对目标字段做更稳、更强、更适合持续叙事的重构。",
        "1. Viết lại không phải nói lại nội dung cũ bằng cách khác, mà là tái dựng field mục tiêu cho vững hơn, mạnh hơn, hợp với tự sự dài hơi hơn.",
        "1. Rewriting is not restating the old text differently — it is rebuilding the target field to be steadier, stronger, and more fit for a sustained narrative."),
      pick(lang,
        "2. 新结果必须与原始故事想法一致，与 expansion、decomposition、constraints 保持兼容。",
        "2. Kết quả mới phải nhất quán với ý tưởng truyện gốc, tương thích với expansion, decomposition, constraints.",
        "2. The new result must stay consistent with the original story idea and compatible with expansion, decomposition, and constraints."),
      pick(lang,
        "3. 如果上下文信息不足，不要胡乱新增重大设定；应在现有信息范围内做最稳妥的增强。",
        "3. Nếu ngữ cảnh thiếu thông tin, đừng bịa thêm thiết lập lớn; hãy tăng cường an toàn nhất trong phạm vi thông tin hiện có.",
        "3. If context is thin, do not invent major new lore — strengthen as safely as possible within the existing information."),
      pick(lang,
        "4. 如果目标字段与现有上下文存在张力，优先做兼容性修正，而不是另起炉灶。",
        "4. Nếu field mục tiêu căng với ngữ cảnh hiện có, ưu tiên sửa cho tương thích, không làm lại từ đầu.",
        "4. If the target field is in tension with the existing context, prefer a compatibility fix over starting from scratch."),
      pick(lang,
        "5. 输出内容必须完整可用，不能写成提纲、备注、解释、分析或半成品。",
        "5. Nội dung đầu ra phải trọn vẹn dùng được, không được viết thành đề cương, chú thích, giải thích, phân tích hay bán thành phẩm.",
        "5. The output must be complete and usable — not an outline, note, explanation, analysis, or half-finished draft."),
      "",
      pick(lang, "字段专项要求：", "Yêu cầu riêng theo field:", "Field-specific requirements:"),
      pick(lang,
        "1. 如果目标字段是 expanded_premise：应强化故事前提与戏剧冲突，不要写成简介口吻。",
        "1. Nếu field mục tiêu là expanded_premise: tăng cường tiền đề truyện và xung đột kịch tính, đừng viết giọng giới thiệu.",
        "1. If the target is expanded_premise: strengthen the premise and dramatic conflict — do not write in a blurb voice."),
      pick(lang,
        "2. 如果目标字段是 protagonist_core：应写清主角被困结构、内在裂缝与可变化空间，不要写成人设卡。",
        "2. Nếu field mục tiêu là protagonist_core: viết rõ kết cấu bị kẹt, vết nứt nội tâm và không gian có thể thay đổi của nhân vật chính, đừng viết thành thẻ nhân thiết.",
        "2. If the target is protagonist_core: clearly state the protagonist's trap structure, inner fracture, and room to change — not a character card."),
      pick(lang,
        "3. 如果目标字段是 conflict_engine：必须体现剧情为何可以持续推进、升级、反转、反噬。",
        "3. Nếu field mục tiêu là conflict_engine: phải thể hiện vì sao cốt truyện có thể liên tục đẩy tới, leo thang, đảo chiều, phản đòn.",
        "3. If the target is conflict_engine: it must show why the plot can keep advancing, escalating, reversing, and backlashing."),
      pick(lang,
        "4. 如果目标字段是 conflict_layers：external / internal / relational 必须彼此区分明确，但又共同服务同一核心矛盾。",
        "4. Nếu field mục tiêu là conflict_layers: external / internal / relational phải phân biệt rõ với nhau nhưng cùng phục vụ một mâu thuẫn cốt lõi.",
        "4. If the target is conflict_layers: external / internal / relational must be clearly distinct yet all serve the same core conflict."),
      pick(lang,
        "5. 如果目标字段是 mystery_box：必须是关键未知，而不是空泛卖关子。",
        "5. Nếu field mục tiêu là mystery_box: phải là ẩn số then chốt, không phải úp mở chung chung.",
        "5. If the target is mystery_box: it must be a crucial unknown, not a vague tease."),
      pick(lang,
        "6. 如果目标字段是 emotional_line：必须体现情绪如何逐步加压、变形、失衡或反转。",
        "6. Nếu field mục tiêu là emotional_line: phải thể hiện cảm xúc từng bước tăng áp, biến hình, mất cân bằng hoặc đảo chiều ra sao.",
        "6. If the target is emotional_line: it must show how emotion gradually intensifies, mutates, destabilizes, or reverses."),
      pick(lang,
        "7. 如果目标字段是 setpiece_seeds：每个场面都必须有画面感、冲突性与后续延展价值，不要凑数。",
        "7. Nếu field mục tiêu là setpiece_seeds: mỗi cảnh phải có hình ảnh, có xung đột và có giá trị mở rộng về sau, đừng cho có.",
        "7. If the target is setpiece_seeds: each scene must be vivid, conflict-laden, and expandable later — no filler."),
      pick(lang,
        "8. 如果目标字段是 tone_reference：必须给出明确叙事气质与写法方向，不要空泛形容词堆砌。",
        "8. Nếu field mục tiêu là tone_reference: phải cho khí chất tự sự và hướng cách viết rõ ràng, đừng chồng chất tính từ chung chung.",
        "8. If the target is tone_reference: give a clear narrative tone and stylistic direction — no piled-up vague adjectives."),
      pick(lang,
        "9. 如果目标字段是 selling_point：必须足够凝练，能够体现区别性与吸引力。",
        "9. Nếu field mục tiêu là selling_point: phải đủ cô đọng, thể hiện được sự khác biệt và sức hút.",
        "9. If the target is selling_point: it must be tight and convey distinctiveness and appeal."),
      pick(lang,
        "10. 如果目标字段是 core_conflict：必须是长期不可调和的对立，而不是一次性事件。",
        "10. Nếu field mục tiêu là core_conflict: phải là sự đối lập không thể hoà giải về lâu dài, không phải một sự kiện dùng một lần.",
        "10. If the target is core_conflict: it must be a long-term irreconcilable opposition, not a one-off event."),
      pick(lang,
        "11. 如果目标字段是 main_hook：必须体现主线未知与持续牵引力。",
        "11. Nếu field mục tiêu là main_hook: phải thể hiện ẩn số tuyến chính và lực kéo liên tục.",
        "11. If the target is main_hook: it must convey the mainline unknown and a sustained pull."),
      pick(lang,
        "12. 如果目标字段是 progression_loop：必须明确体现“发现 -> 介入 -> 升级 -> 反噬/反转 -> 再发现”的循环机制。",
        "12. Nếu field mục tiêu là progression_loop: phải thể hiện rõ cơ chế vòng lặp \"phát hiện -> can dự -> leo thang -> phản đòn/đảo chiều -> lại phát hiện\".",
        "12. If the target is progression_loop: it must clearly show the loop \"discover -> intervene -> escalate -> backlash/reversal -> discover again\"."),
      pick(lang,
        "13. 如果目标字段是 growth_path：必须体现主角认知或状态的阶段性变化与代价。",
        "13. Nếu field mục tiêu là growth_path: phải thể hiện thay đổi theo giai đoạn về nhận thức hoặc trạng thái của nhân vật chính và cái giá.",
        "13. If the target is growth_path: it must show the protagonist's phased change in perception or state, and its cost."),
      pick(lang,
        "14. 如果目标字段是 major_payoffs：必须是真正值得兑现的爆点，不要写普通剧情节点。",
        "14. Nếu field mục tiêu là major_payoffs: phải là điểm bùng nổ thực sự đáng tận thu, đừng viết mắt xích cốt truyện thông thường.",
        "14. If the target is major_payoffs: these must be payoffs genuinely worth cashing in — not ordinary plot beats."),
      pick(lang,
        "15. 如果目标字段是 ending_flavor：应体现结局气质与最终余味，而不是具体结局细纲。",
        "15. Nếu field mục tiêu là ending_flavor: thể hiện khí chất kết thúc và dư vị cuối, không phải đề cương chi tiết của kết thúc.",
        "15. If the target is ending_flavor: convey the ending's temperament and final aftertaste — not a detailed ending outline."),
      pick(lang,
        "16. 如果目标字段是 constraints：必须写成后续生成可以直接遵守的叙事规则，禁止空话。",
        "16. Nếu field mục tiêu là constraints: phải viết thành quy tắc tự sự mà bước sinh sau có thể tuân theo trực tiếp, cấm nói suông.",
        "16. If the target is constraints: write narrative rules the downstream steps can obey directly — no empty talk."),
      "",
      pick(lang, "输出要求：", "Yêu cầu đầu ra:", "Output requirements:"),
      pick(lang,
        "1. 只输出严格合法的 JSON 对象。",
        "1. Chỉ xuất một đối tượng JSON hợp lệ nghiêm ngặt.",
        "1. Output only a strictly valid JSON object."),
      pick(lang,
        "2. 不要输出解释、Markdown、代码块或任何额外文本。",
        "2. Không xuất lời giải thích, Markdown, khối mã hay bất kỳ văn bản thừa nào.",
        "2. Do not output explanations, Markdown, code blocks, or any extra text."),
      pick(lang,
        `3. 输出格式必须严格为：${fieldFormat}`,
        `3. Định dạng đầu ra bắt buộc phải đúng là: ${fieldFormat}`,
        `3. The output format must be exactly: ${fieldFormat}`),
      pick(lang,
        "4. 除 value 外，不要输出任何额外字段。",
        "4. Ngoài value, không xuất bất kỳ field thừa nào.",
        "4. Do not output any field other than value."),
      pick(lang,
        `5. 你当前唯一需要重写的字段是：${input.field}`,
        `5. Field duy nhất bạn cần viết lại lúc này là: ${input.field}`,
        `5. The only field you need to rewrite right now is: ${input.field}`),
    ].join("\n"),
    user: [
      input.projectContext
        ? pick(lang,
            `项目上下文：\n${input.projectContext}`,
            `Ngữ cảnh dự án:\n${input.projectContext}`,
            `Project context:\n${input.projectContext}`)
        : "",
      pick(lang,
        `原始故事想法：\n${input.storyInput}`,
        `Ý tưởng truyện gốc:\n${input.storyInput}`,
        `Original story idea:\n${input.storyInput}`),
      input.expansion
        ? pick(lang,
            `故事引擎原型（expansion）：\n${JSON.stringify(input.expansion, null, 2)}`,
            `Nguyên mẫu động cơ truyện (expansion):\n${JSON.stringify(input.expansion, null, 2)}`,
            `Story-engine prototype (expansion):\n${JSON.stringify(input.expansion, null, 2)}`)
        : "",
      pick(lang,
        `推进与兑现摘要（decomposition）：\n${JSON.stringify(input.decomposition, null, 2)}`,
        `Tóm tắt đẩy truyện và tận thu (decomposition):\n${JSON.stringify(input.decomposition, null, 2)}`,
        `Progression & payoff summary (decomposition):\n${JSON.stringify(input.decomposition, null, 2)}`),
      pick(lang,
        `硬约束（constraints）：\n${JSON.stringify(input.constraints, null, 2)}`,
        `Ràng buộc cứng (constraints):\n${JSON.stringify(input.constraints, null, 2)}`,
        `Hard constraints (constraints):\n${JSON.stringify(input.constraints, null, 2)}`),
      pick(lang,
        `已锁定字段（lockedFields）：\n${JSON.stringify(input.lockedFields, null, 2)}`,
        `Các field đã khoá (lockedFields):\n${JSON.stringify(input.lockedFields, null, 2)}`,
        `Locked fields (lockedFields):\n${JSON.stringify(input.lockedFields, null, 2)}`),
      pick(lang,
        `请仅重写字段：${input.field}`,
        `Chỉ viết lại field: ${input.field}`,
        `Rewrite only the field: ${input.field}`),
    ].filter(Boolean).join("\n\n"),
  };
}

export const storyMacroDecompositionPrompt: PromptAsset<
  StoryMacroDecompositionPromptInput,
  typeof STORY_MACRO_RESPONSE_SCHEMA._output
> = {
  id: "novel.story_macro.decomposition",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.storyMacroDecomposition,
    requiredGroups: ["story_input"],
    preferredGroups: ["project_context"],
  },
  outputSchema: STORY_MACRO_RESPONSE_SCHEMA,
  render: (input, context) => {
    const prompt = buildExpansionAndDecompositionPrompt(context.promptLanguage, input.storyInput, input.projectContext);
    return [
      new SystemMessage(prompt.system),
      new HumanMessage(renderSelectedContextBlocks(context)),
    ];
  },
};

export const storyMacroFieldRegenerationSchema = z.object({
  value: z.unknown().optional(),
}).passthrough();

export const storyMacroFieldRegenerationPrompt: PromptAsset<
  StoryMacroFieldRegenerationPromptInput,
  typeof storyMacroFieldRegenerationSchema._output
> = {
  id: "novel.story_macro.field_regeneration",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.storyMacroFieldRegeneration,
    requiredGroups: ["story_input", "target_field", "decomposition_summary", "constraints"],
    preferredGroups: ["project_context", "expansion_summary", "locked_fields"],
  },
  outputSchema: storyMacroFieldRegenerationSchema,
  render: (input, context) => {
    const prompt = buildFieldRegenerationPrompt({
      lang: context.promptLanguage,
      field: input.field,
      storyInput: input.storyInput,
      expansion: input.expansion,
      decomposition: input.decomposition,
      constraints: input.constraints,
      lockedFields: input.lockedFields,
      projectContext: input.projectContext,
    });
    return [
      new SystemMessage(prompt.system),
      new HumanMessage(renderSelectedContextBlocks(context)),
    ];
  },
};
