import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptLanguage } from "@ai-novel/shared/utils/novelLanguage";
import type { PromptAsset, PromptRenderContext } from "../../core/promptTypes";
import { snapshotExtractionOutputSchema } from "../../../services/state/stateSchemas";

export interface StateSnapshotPromptInput {
  novelId: string;
  chapterOrder: number;
  chapterTitle: string;
  chapterGoal: string;
  charactersText: string;
  summaryText: string;
  factsText: string;
  timelineText: string;
  previousSummary: string;
  content: string;
}

function pick(lang: PromptLanguage, zh: string, vi: string, en: string): string {
  if (lang === "vi") return vi;
  if (lang === "en") return en;
  return zh;
}

function buildStateSnapshotExample(lang: PromptLanguage): unknown {
  const a = pick(lang, "林青", "Lâm Thanh", "Lin Qing");
  const b = pick(lang, "苏雨", "Tô Vũ", "Su Yu");
  return {
    summary: pick(lang,
      "本章结束后，主角暂时稳住局面，但关键误会和回收线索仍在持续发酵。",
      "Sau chương này, nhân vật chính tạm giữ được cục diện, nhưng hiểu lầm then chốt và các manh mối chờ thu hồi vẫn đang tiếp tục lên men.",
      "After this chapter, the protagonist holds the situation for now, but the key misunderstanding and the threads awaiting payoff keep simmering."),
    characterStates: [
      {
        characterName: a,
        currentGoal: pick(lang, "先稳住身份，再追查异常来源", "Giữ vững thân phận trước, rồi truy nguồn của điều dị thường", "Secure the identity first, then trace the source of the anomaly"),
        emotion: pick(lang, "警惕", "cảnh giác", "wary"),
        summary: pick(lang,
          `${a}确认危险已经逼近，不再把异常当作偶然。`,
          `${a} xác nhận nguy hiểm đã áp sát, không còn coi điều dị thường là ngẫu nhiên.`,
          `${a} confirms danger has closed in and no longer treats the anomaly as coincidence.`),
      },
    ],
    relationStates: [
      {
        sourceCharacterName: a,
        targetCharacterName: b,
        summary: pick(lang,
          `${a}开始把${b}视为可以试探合作的对象。`,
          `${a} bắt đầu xem ${b} là đối tượng có thể thăm dò hợp tác.`,
          `${a} starts to see ${b} as someone worth probing for cooperation.`),
      },
    ],
    informationStates: [
      {
        holderType: "reader",
        fact: pick(lang,
          "异常信号并非幻觉，而是有人为痕迹的真实事件。",
          "Tín hiệu dị thường không phải ảo giác, mà là sự việc có thật mang dấu vết con người.",
          "The anomalous signal is not a hallucination but a real event bearing human traces."),
        status: "known",
        summary: pick(lang,
          "读者已经确认异常背后存在人为力量。",
          "Người đọc đã xác nhận phía sau điều dị thường có bàn tay con người.",
          "The reader has confirmed there is a human hand behind the anomaly."),
      },
      {
        holderType: "character",
        holderRefName: a,
        fact: pick(lang,
          `${b}并没有把自己知道的线索全部说出来。`,
          `${b} không nói ra hết những manh mối mình biết.`,
          `${b} has not told everything they know.`),
        status: "misbelief",
        summary: pick(lang,
          `${a}误以为${b}仍在完全被动地应对局面。`,
          `${a} lầm tưởng ${b} vẫn hoàn toàn bị động ứng phó với cục diện.`,
          `${a} mistakenly believes ${b} is still purely reacting to the situation.`),
      },
    ],
    foreshadowStates: [
      {
        title: pick(lang, "回收旧实验记录", "Thu hồi hồ sơ thí nghiệm cũ", "Pay off the old experiment records"),
        summary: pick(lang,
          "本章只完成铺垫，后续仍需兑现。",
          "Chương này mới chỉ hoàn thành phần tích thế, sau này vẫn cần thu hồi.",
          "This chapter only completes the setup; it still needs to be paid off later."),
        status: "setup",
      },
    ],
  };
}

export const stateSnapshotPrompt: PromptAsset<
  StateSnapshotPromptInput,
  z.infer<typeof snapshotExtractionOutputSchema>
> = {
  id: "state.snapshot.extract",
  version: "v4",
  taskType: "summary",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  structuredOutputHint: {
    example: (_input: StateSnapshotPromptInput, context: PromptRenderContext) => buildStateSnapshotExample(context.promptLanguage),
    note: (_input: StateSnapshotPromptInput, context: PromptRenderContext) => pick(context.promptLanguage,
      "targetCharacterId、setupChapterId、payoffChapterId 在无法稳定确认时必须省略，不要输出 null。不要编造 chapter_1、placeholder_chapter_id 之类的占位 ID。",
      "Khi không thể xác nhận ổn định thì phải bỏ targetCharacterId, setupChapterId, payoffChapterId — đừng xuất null. Đừng bịa các ID giữ chỗ kiểu chapter_1, placeholder_chapter_id.",
      "Omit targetCharacterId, setupChapterId, and payoffChapterId when they cannot be confirmed stably — do not output null. Do not invent placeholder IDs like chapter_1 or placeholder_chapter_id."),
  },
  outputSchema: snapshotExtractionOutputSchema,
  render: (input, context) => {
    const lang = context.promptLanguage;
    return [
    new SystemMessage([
      pick(lang,
        "你是长篇中文小说的状态快照提取器。",
        "Bạn là bộ trích ảnh chụp trạng thái cho tiểu thuyết dài.",
        "You extract state snapshots for a long-form novel."),
      pick(lang,
        "你的任务是基于当前章节材料，提取“本章结束后”的全局状态快照，供后续规划、续写与一致性校验直接使用。",
        "Nhiệm vụ của bạn là dựa trên tài liệu chương hiện tại, trích ảnh chụp trạng thái toàn cục \"sau khi chương này kết thúc\", để bước lập kế hoạch, viết tiếp và kiểm tra nhất quán về sau dùng trực tiếp.",
        "Your task is to extract the global state snapshot \"after this chapter ends\" from the current chapter materials, for direct use by downstream planning, continuation, and consistency checks."),
      "",
      pick(lang,
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或任何额外文本。",
        "Chỉ xuất một đối tượng JSON hợp lệ, không xuất Markdown, giải thích, chú thích, khối mã hay bất kỳ văn bản thừa nào.",
        "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or any extra text."),
      pick(lang,
        "顶层只能包含：summary、characterStates、relationStates、informationStates、foreshadowStates。",
        "Cấp trên cùng chỉ được gồm: summary, characterStates, relationStates, informationStates, foreshadowStates.",
        "The top level may contain only: summary, characterStates, relationStates, informationStates, foreshadowStates."),
      "",
      pick(lang, "全局硬规则：", "Quy tắc cứng toàn cục:", "Global hard rules:"),
      pick(lang,
        "1. 所有内容必须使用目标语言（默认简体中文，以末尾“输出语言指令”为准）。",
        "1. Mọi nội dung phải dùng ngôn ngữ đích (mặc định tiếng Trung giản thể, lấy \"chỉ thị ngôn ngữ đầu ra\" ở cuối làm chuẩn).",
        "1. All content must use the target language (default Simplified Chinese; the \"output-language directive\" at the end takes precedence)."),
      pick(lang,
        "2. 只能依据提供的材料提取，不得补写正文里没有出现或无法稳定推出的新事实。",
        "2. Chỉ được trích dựa trên tài liệu đã cung cấp, không được viết thêm sự thật mới không xuất hiện trong chính văn hoặc không suy ra ổn định được.",
        "2. Extract only from the provided materials — do not add new facts that do not appear in the prose or cannot be inferred stably."),
      pick(lang,
        "3. 输出的是“章节结束后的状态”，不是剧情复述，也不是摘要扩写。",
        "3. Đầu ra là \"trạng thái sau khi chương kết thúc\", không phải thuật lại cốt truyện, cũng không phải mở rộng tóm tắt.",
        "3. The output is \"the state after the chapter ends\" — not a plot retelling, not an expanded summary."),
      pick(lang,
        "4. 信息不足时宁可省略该条，也不要把猜测写成事实。",
        "4. Khi thiếu thông tin, thà bỏ mục đó còn hơn viết phỏng đoán thành sự thật.",
        "4. When information is thin, omit the item rather than writing a guess as fact."),
      pick(lang,
        "5. 各字段之间必须一致，不得互相冲突。",
        "5. Các field phải nhất quán với nhau, không được xung đột lẫn nhau.",
        "5. Fields must be consistent with each other and must not conflict."),
      "",
      pick(lang, "缺失引用规则：", "Quy tắc khi tham chiếu bị thiếu:", "Missing-reference rules:"),
      pick(lang,
        "1. 如果 targetCharacterId 不确定，优先保留 targetCharacterName，并直接省略 targetCharacterId。",
        "1. Nếu targetCharacterId không chắc, ưu tiên giữ targetCharacterName và bỏ luôn targetCharacterId.",
        "1. If targetCharacterId is uncertain, keep targetCharacterName and just omit targetCharacterId."),
      pick(lang,
        "2. 如果 setupChapterId / payoffChapterId 无法稳定确认，就直接省略字段，不要输出 null。",
        "2. Nếu setupChapterId / payoffChapterId không xác nhận ổn định được thì bỏ luôn field, đừng xuất null.",
        "2. If setupChapterId / payoffChapterId cannot be confirmed stably, omit the field — do not output null."),
      pick(lang,
        "3. 不要编造 chapter_1、chapter_x、placeholder_chapter_id 之类的占位 ID。",
        "3. Đừng bịa các ID giữ chỗ kiểu chapter_1, chapter_x, placeholder_chapter_id.",
        "3. Do not invent placeholder IDs like chapter_1, chapter_x, placeholder_chapter_id."),
      pick(lang,
        "4. 若 holderType=character 且角色 ID 不明确，可用 holderRefName 指代；holderType=reader 时不要强行补角色引用。",
        "4. Nếu holderType=character và ID nhân vật không rõ, có thể dùng holderRefName để chỉ; khi holderType=reader thì đừng cố nhét tham chiếu nhân vật.",
        "4. If holderType=character and the character ID is unclear, use holderRefName; when holderType=reader, do not force a character reference."),
      "",
      pick(lang, "字段目标：", "Mục tiêu từng field:", "Field goals:"),
      pick(lang,
        "1. summary：简洁描述本章结束后整体局面处于什么状态。",
        "1. summary: mô tả ngắn gọn cục diện tổng thể đang ở trạng thái nào sau khi chương kết thúc.",
        "1. summary: concisely describe what state the overall situation is in after the chapter ends."),
      pick(lang,
        "2. characterStates：只保留会持续影响后续创作的重要角色状态。",
        "2. characterStates: chỉ giữ các trạng thái nhân vật quan trọng sẽ tiếp tục ảnh hưởng đến việc viết về sau.",
        "2. characterStates: keep only important character states that will keep affecting downstream writing."),
      pick(lang,
        "3. relationStates：只记录本章实际发生变化的关系状态。",
        "3. relationStates: chỉ ghi các trạng thái quan hệ thực sự thay đổi trong chương này.",
        "3. relationStates: record only relationship states that actually changed this chapter."),
      pick(lang,
        "4. informationStates：只记录会影响认知差、误会、悬念或冲突推进的关键信息状态。",
        "4. informationStates: chỉ ghi các trạng thái thông tin then chốt ảnh hưởng đến khoảng cách nhận thức, hiểu lầm, hồi hộp hoặc sự đẩy xung đột.",
        "4. informationStates: record only key information states that affect knowledge gaps, misunderstandings, suspense, or conflict progression."),
      pick(lang,
        "5. foreshadowStates：只记录本章中被建立、强化、等待兑现、已经兑现或失效的伏笔状态。",
        "5. foreshadowStates: chỉ ghi các trạng thái foreshadow được dựng, được củng cố, đang chờ thu hồi, đã thu hồi hoặc mất hiệu lực trong chương này.",
        "5. foreshadowStates: record only foreshadowing states that were established, reinforced, awaiting payoff, paid off, or invalidated this chapter."),
      "",
      pick(lang, "质量要求：", "Yêu cầu chất lượng:", "Quality requirements:"),
      pick(lang,
        "1. 输出要短、准、稳，服务系统读取，而不是写成人类点评。",
        "1. Đầu ra phải ngắn, chính xác, ổn định, phục vụ hệ thống đọc, không viết thành lời bình của con người.",
        "1. The output must be short, accurate, and stable — for the system to read, not a human review."),
      pick(lang,
        "2. 不要把 summary 和各状态字段写成同义重复。",
        "2. Đừng viết summary và các field trạng thái thành trùng nghĩa.",
        "2. Do not write summary and the state fields as synonyms."),
      pick(lang,
        "3. 优先保留真正会影响下一章或后续阶段的状态变化，过滤噪音。",
        "3. Ưu tiên giữ các thay đổi trạng thái thực sự ảnh hưởng chương sau hoặc giai đoạn về sau, lọc bỏ nhiễu.",
        "3. Prioritize state changes that genuinely affect the next chapter or later phases; filter out noise."),
      "",
      pick(lang,
        "输出必须严格符合 snapshotExtractionOutputSchema。",
        "Đầu ra phải tuân thủ nghiêm snapshotExtractionOutputSchema.",
        "The output must strictly conform to snapshotExtractionOutputSchema."),
    ].join("\n")),
    new HumanMessage([
      pick(lang, `小说ID：${input.novelId}`, `ID tiểu thuyết: ${input.novelId}`, `Novel ID: ${input.novelId}`),
      pick(lang,
        `章节：第${input.chapterOrder}章《${input.chapterTitle}》`,
        `Chương: chương ${input.chapterOrder} "${input.chapterTitle}"`,
        `Chapter: chapter ${input.chapterOrder} "${input.chapterTitle}"`),
      pick(lang, `章节目标：${input.chapterGoal}`, `Mục tiêu chương: ${input.chapterGoal}`, `Chapter goal: ${input.chapterGoal}`),
      "",
      pick(lang, "角色清单：", "Danh sách nhân vật:", "Character list:"),
      input.charactersText,
      "",
      pick(lang, "章节摘要：", "Tóm tắt chương:", "Chapter summary:"),
      input.summaryText,
      "",
      pick(lang, "事实：", "Sự thật:", "Facts:"),
      input.factsText,
      "",
      pick(lang, "角色时间线：", "Dòng thời gian nhân vật:", "Character timeline:"),
      input.timelineText,
      "",
      input.previousSummary || pick(lang, "前置状态摘要：无", "Tóm tắt trạng thái trước: không có", "Prior state summary: none"),
      "",
      pick(lang, "正文：", "Chính văn:", "Prose:"),
      input.content,
      "",
      pick(lang, "输出提醒：", "Nhắc nhở đầu ra:", "Output reminders:"),
      pick(lang,
        "1. characterStates 中每个角色最多一条。",
        "1. Trong characterStates, mỗi nhân vật tối đa một mục.",
        "1. In characterStates, at most one entry per character."),
      pick(lang,
        "2. relationStates 只保留本章实际变化的关系。",
        "2. relationStates chỉ giữ các quan hệ thực sự thay đổi trong chương này.",
        "2. relationStates: keep only relationships that actually changed this chapter."),
      pick(lang,
        "3. informationStates 的 holderType 只能是 reader 或 character；status 只能是 known 或 misbelief。",
        "3. holderType của informationStates chỉ được là reader hoặc character; status chỉ được là known hoặc misbelief.",
        "3. informationStates holderType may only be reader or character; status may only be known or misbelief."),
      pick(lang,
        "4. foreshadowStates 的 status 只能是 setup、hinted、pending_payoff、paid_off、failed。",
        "4. status của foreshadowStates chỉ được là setup, hinted, pending_payoff, paid_off, failed.",
        "4. foreshadowStates status may only be setup, hinted, pending_payoff, paid_off, failed."),
      pick(lang,
        "5. 不知道 targetCharacterId 时就省略，不要写 null。",
        "5. Không biết targetCharacterId thì bỏ, đừng viết null.",
        "5. When targetCharacterId is unknown, omit it — do not write null."),
      pick(lang,
        "6. 不知道 setupChapterId / payoffChapterId 时就省略，不要写 null，也不要写占位 ID。",
        "6. Không biết setupChapterId / payoffChapterId thì bỏ, đừng viết null, cũng đừng viết ID giữ chỗ.",
        "6. When setupChapterId / payoffChapterId is unknown, omit it — do not write null, and do not write a placeholder ID."),
      pick(lang,
        "7. summary 必须描述本章结束后的全局状态，而不是过程复述。",
        "7. summary phải mô tả trạng thái toàn cục sau khi chương kết thúc, không phải thuật lại quá trình.",
        "7. summary must describe the global state after the chapter ends — not a retelling of the process."),
    ].join("\n")),
    ];
  },
};
